### ISSUE TITLE
[🐛 Bug]: Making Examples better and in common format in the site

### ISSUE THREAD

**Issue by MrRahulR** [SeleniumHQ/seleniumhq.github.io#1000]
### What happened?

It looks like the document has many examples for each of the methods, which is a good thing but the example formats are different in each of the codes. I think it should be better to have the same code format in each of the examples and should be focused on the method only rather than pasting the entire example. 

i.e. For `sendKeys`, we don't need to enter the entire example including the class and driver initialization code. 

I would suggest that we can make uniformity for all the codes on the site would make it better for someone who is learning can check straight to the code which they are looking for.

### What browsers and operating systems are you seeing the problem on?

System Version: macOS 12.3.1 (21E258)
Kernel Version: Darwin 21.4.0
Browser - Google Chrome v100

**Comment by harsha509** [comment]
Hi @MrRahulR,

I know where you're coming from !

There is a reason for pasting entire code sample in few places.

If we focus on '**method only**', the users are getting confused (as they want full code with imports to make it work). Someone who is new to selenium is unable to understand how "**sendKeys**" works without class and driver initialization code/imports.

Ex: https://github.com/SeleniumHQ/seleniumhq.github.io/issues/953

Also, there are few new things in Selenium that required entire code sample (ex: devtools usage).

But anyway we're trying to keep uniformity by moving all working code samples to github!

Also, you can help us on this, See https://www.selenium.dev/documentation/about/style/#link-to-github

Thanks,
Sri Harsha

**Comment by MrRahulR** [comment]
Okay @harsha509 , I got it now. 

> But anyway we're trying to keep uniformity by moving all working code samples to github!

I like this idea, I'll try to add more GitHub snippets in the code and make it uniform across the site.
