### ISSUE TITLE
[🐛 Bug]: Docs - First Mouse Action example is wrong

### ISSUE THREAD

**Issue by ennioVisco** [SeleniumHQ/seleniumhq.github.io#1005]
### What happened?

At line 14 of the first code block in Java example at [Mouse actions | Selenium](https://www.selenium.dev/documentation/webdriver/actions_api/mouse/) they want to search for the button to start a search, not to sign in, so the `"Sign In"` string should probably be replaced by `"Google Search"`.
The same issue is present also in the other languages.

### What browsers and operating systems are you seeing the problem on?

Any

**Comment by diemol** [comment]
Would you like to send a PR to fix it?
