### ISSUE TITLE
[🚀 Feature]: Use code examples for Key up for the languages CSharp, Ruby, JavaScript, and Kotlin for the code examples for sendKeys for the same languages

### ISSUE THREAD

**Issue by ollie-iterators** [SeleniumHQ/seleniumhq.github.io#1009]
### Feature and motivation

I just noticed that the code examples for the "Key down" and "Key up" areas for the different languages on the URL: https://www.selenium.dev/documentation/webdriver/actions_api/keyboard/, both have the sendKeys function (in whatever form it is used in for the various languages). This means that those code examples could be an example of how to use the SendKeys code.

**Comment by diemol** [comment]
I do not understand the point of this issue, there are already examples for `sendKeys`

https://www.selenium.dev/documentation/webdriver/elements/interactions/#send-keys

**Comment by ollie-iterators** [comment]
I am talking about the examples on this URL: https://www.selenium.dev/documentation/webdriver/actions_api/keyboard/

**Comment by diemol** [comment]
I still don't understand. We have examples on both pages... Is there something that needs to be fixed?

**Comment by ollie-iterators** [comment]
<img width="1299" alt="2022-05-15_11-15-26" src="https://user-images.githubusercontent.com/46904826/168480143-47136606-6370-42a4-b8f7-722e95195326.png">
<img width="1299" alt="2022-05-15_11-15-08" src="https://user-images.githubusercontent.com/46904826/168480147-9ef770be-df65-48a5-a980-f1ad27b0fe51.png">
<img width="1299" alt="2022-05-15_11-14-54" src="https://user-images.githubusercontent.com/46904826/168480148-af07b8ef-f576-445e-8870-cc5c4b10550f.png">

**Comment by ollie-iterators** [comment]
<img width="1299" alt="2022-05-15_11-16-51" src="https://user-images.githubusercontent.com/46904826/168480199-87bc6b9d-9665-4869-82af-2973132d8816.png">
<img width="1299" alt="2022-05-15_11-16-44" src="https://user-images.githubusercontent.com/46904826/168480201-0dd13b28-7400-42f7-94c2-6be71ef6bd41.png">
<img width="1299" alt="2022-05-15_11-16-37" src="https://user-images.githubusercontent.com/46904826/168480203-c0ce0348-08e3-40de-a23c-5a93627595f5.png">

**Comment by harsha509** [comment]
Closing as Code samples are in place for all tabs in here now

https://www.selenium.dev/documentation/webdriver/actions_api/keyboard/#send-keys
