### ISSUE TITLE
 [documentation] Broken link in shared capability page

### ISSUE THREAD

**Issue by alliv8** [SeleniumHQ/seleniumhq.github.io#1025]
### What happened?

https://www.selenium.dev/documentation/webdriver/capabilities/shared/

https://www.selenium.dev/webdriver/waits gives a `404`

Not able to select documentation issue in the previous form

### What browsers and operating systems are you seeing the problem on?

Mac Chrome

**Comment by harsha509** [comment]
Hi @[alliv8](https://github.com/alliv8),
Thank you for raising the issue!

I have fixed with new commit!
