### ISSUE TITLE
[🐛 Bug]: Page loops in documentation

### ISSUE THREAD

**Issue by til-gsouza** [SeleniumHQ/seleniumhq.github.io#1033]
### What happened?

On the [Install browser drivers page](https://www.selenium.dev/documentation/webdriver/getting_started/install_drivers/) text there is a reference for the [driver configuration page](https://www.selenium.dev/documentation/webdriver/drivers/), which has only a single line and a reference back to the  [Install browser drivers page](https://www.selenium.dev/documentation/webdriver/getting_started/install_drivers/). Looks like a documentation bug to the user.

### What browsers and operating systems are you seeing the problem on?

Chrome, Edge

**Comment by Qiuyangfeng** [comment]
I have the same problem as you，really annoying

**Comment by diemol** [comment]
Yes, this content is missing. We'd be happy if you can help us to add that content, @til-gsouza @Qiuyangfeng

**Comment by diemol** [comment]
@titusfortner what is the content you were thinking for https://www.selenium.dev/documentation/webdriver/drivers/?

**Comment by eaccmk** [comment]
I have found the issue , fix coming soon @diemol
