### ISSUE TITLE
[🐛 Bug]: JavaScript Code for First Script Components 2 to 4 do not have any code in them

### ISSUE THREAD

**Issue by ollie-iterators** [SeleniumHQ/seleniumhq.github.io#1038]
### What happened?

I checked out the Selenium.dev/documentation site for the first script of Selenium and I noticed that the JavaScript First Script Components 2 - 4 JavaScript code does not contain any code.
<img width="1394" alt="2022-06-07_13-13-44" src="https://user-images.githubusercontent.com/46904826/172443442-d7971281-e174-4281-9b9c-4ad5ca35b917.png">
<img width="1394" alt="2022-06-07_13-13-57" src="https://user-images.githubusercontent.com/46904826/172443450-7d2b6699-f06f-4d89-8192-21b9a6227b97.png">

### What browsers and operating systems are you seeing the problem on?

MacOS 12.4 > Chrome 102

**Comment by harsha509** [comment]
Hi @ollie-iterators,

Thanks for reporting the issue.

Looks like my commit to fix #1035 broke it!

Will fix it!

**Comment by harsha509** [comment]
Fixed with commit https://github.com/SeleniumHQ/seleniumhq.github.io/commit/e748e98f10d8ff7fd6fa7e4f483e0117286233ea !
