### ISSUE TITLE
[🐛 Bug]: The Driver throws error when the Url is passed without "http://" or "https://"

### ISSUE THREAD

**Issue by svadivel0006** [SeleniumHQ/seleniumhq.github.io#1042]
### What happened?

The WebDriverManager/Driver throws error when the Url is passed without "http://" or "https://"

Screenshot:

Error Details:

![image](https://user-images.githubusercontent.com/85741928/172981226-a41015a8-bb85-4e1f-86c1-f82e07d2a8db.png)

Version Details:

![image](https://user-images.githubusercontent.com/85741928/172981256-ca4f32f6-ad6a-45b8-8998-8e9f33cc99b4.png)

Browser .exe downloaded and available details:

![image](https://user-images.githubusercontent.com/85741928/172981310-501dd1de-c5b2-48dc-9bf9-edcc36dc7548.png)

### What browsers and operating systems are you seeing the problem on?

Win 10
Chrome
Edge
Firefox

**Comment by diemol** [comment]
This is expected, urls should be provided with the protocol.
