### ISSUE TITLE
[🐛 Bug]: In the blog for upgrading to Selenium 4 (Firefox)

### ISSUE THREAD

**Issue by boris779** [SeleniumHQ/seleniumhq.github.io#1047]
### What happened?

In the Upgrade to Selenium 4 in the Section for Firefox there seems to be an issue. The Before and After Codeexample are identical in the Browser Type section

[browsertype](https://www.selenium.dev/documentation/webdriver/getting_started/upgrade_to_selenium_4/#browsertype)

### What browsers and operating systems are you seeing the problem on?

Firefox 101, geckodriver 0.31.0

**Comment by diemol** [comment]
They are not the same, one is the old `BrowserType` interface, on the right there is the new **`Browser`** one. 

![image](https://user-images.githubusercontent.com/5992658/173569231-e8d6dcd2-02c6-4d7d-a53e-0fc89e7f7e77.png)

**Comment by boris779** [comment]
Thx and sorry, I compared it three times and didn't saw the difference
