### ISSUE TITLE
[🐛 Bug]:  Ruby bindings link in download page

### ISSUE THREAD

**Issue by jlafleur93** [SeleniumHQ/seleniumhq.github.io#1049]
### What happened?

1) Go to https://www.selenium.dev/downloads/
2) Scroll down to Ruby Bindings
3) Click on Ruby 4.2.2
4) Notice the page is not found on the ruby gems page
The last version of the bindings atm is 4.2.1 updated in pr below
#1048 

### What browsers and operating systems are you seeing the problem on?

Chrome Windows 10

**Comment by harsha509** [comment]
Thank you for fixing it @jlafleur93 !

This is fixed with PR https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1048!
