### ISSUE TITLE
[🐛 Bug]: Linked video from Web Elements -> Is Displayed Section no longer available

### ISSUE THREAD

**Issue by lread** [SeleniumHQ/seleniumhq.github.io#1052]
### What happened?

First: Thanks for all the hard work and docs!

While reading up on how elements are displayed I noticed that, for me, the linked video shows on YouTube as "This video isn't available anymore".

- Section in docs: https://www.selenium.dev/documentation/webdriver/elements/information/#is-displayed
- Link from docs: [impossibility of covering all potential conditions](https://www.youtube.com/watch?v=hTa1KI6fQpg).
- Source on GitHub (for English): https://github.com/SeleniumHQ/seleniumhq.github.io/blob/3ec4cc6a207b9d41d96af614e29ec5f55787c18a/website_and_docs/content/documentation/webdriver/elements/information.en.md?plain=1#L20

### What browsers and operating systems are you seeing the problem on?

Firefox on macOS from Canada.

**Comment by diemol** [comment]
Link needs to be replaced with https://www.youtube.com/watch?v=LAD_XPGP_kk

**Comment by diemol** [comment]
Fixed via #1085
