### ISSUE TITLE
Hub Is Not Starting[🐛 Bug]: 

### ISSUE THREAD

**Issue by Hidalgo71** [SeleniumHQ/seleniumhq.github.io#1054]
### What happened?

`java -jar selenium-server-standalone.jar -role hub` is not working for me, it gives an error. 
I'm trying a different method for standup Grid: `java -jar selenium-server-4.2.2.jar standalone` works, but I can't use a config like 
`java -jar selenium-server-4.2.2.jar standalone [options]`
or
`java -jar selenium-server-4.2.2.jar standalone -hubConfig hubconfig.json`

### What browsers and operating systems are you seeing the problem on?

Windows 10, java version 8

**Comment by diemol** [comment]
@Hidalgo71 Grid 4 is a complete new implementation and while most of the previous configs can be mapped, they need to be rewritten. Please have a look at the docs.
https://www.selenium.dev/documentation/grid/

**Comment by Hidalgo71** [comment]
Thank you for your fast and straightforward help.
