### ISSUE TITLE
[🐛 Bug]: [Documentation] : Javascript code snippet is missing for Mouse Events

### ISSUE THREAD

**Issue by himanshu-sin** [SeleniumHQ/seleniumhq.github.io#1055]
### What happened?

**Steps:**

1.Navigate to https://www.selenium.dev/documentation/webdriver/actions_api/mouse/ 
2.Click on Javascript tab for any mouse event .

**Actual Result:**
Sample javascript code is missing 

**Expected Result:**
Sample Javascript code should be present.

### What browsers and operating systems are you seeing the problem on?

Browser : Chrome
OS : MAC

**Comment by diemol** [comment]
Would you like to send a PR to include the code?

**Comment by himanshu-sin** [comment]
@diemol , I don't want to raise the PR . I am requesting if other who is well versed with javascript to raise the PR.

**Comment by diemol** [comment]
@harsha509 do you know how these ones can be implemented?
- https://www.selenium.dev/documentation/webdriver/actions_api/mouse/#back-click
- https://www.selenium.dev/documentation/webdriver/actions_api/mouse/#forward-click

**Comment by harsha509** [comment]
Hi @diemol,

I have added support in JS bindings with commit https://github.com/SeleniumHQ/selenium/commit/845e47d43f03d6638ae550c805235defbb69c0d9

Added code sample here
https://www.selenium.dev/documentation/webdriver/actions_api/mouse/#back-click
https://www.selenium.dev/documentation/webdriver/actions_api/mouse/#forward-click

_**NOTE**_: The tests are skipped as the code sample depends on the next release

Thanks,
Harsha

**Comment by diemol** [comment]
Thank you!

**Comment by diemol** [comment]
We still have some code examples to complete, but there is progress.

**Comment by harsha509** [comment]
Updated all code samples accordingly in docs! 

Closing as resolved!
