### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by mahiiraaj** [SeleniumHQ/seleniumhq.github.io#1056]
### What happened?

Clicking on python tab does not change code from java to python

### What browsers and operating systems are you seeing the problem on?

not matter what tab I click it only shows java code example.
https://www.selenium.dev/documentation/webdriver/capabilities/shared/#tabs-1-1

**Comment by diemol** [comment]
I cannot reproduce this issue, what needs to happen for this to be reproducible?

**Comment by diemol** [comment]
Closing as we did not get more information.
