### ISSUE TITLE
[🐛 Bug]: Python BiDi documentation contradicts source code examples

### ISSUE THREAD

**Issue by jsfehler** [SeleniumHQ/seleniumhq.github.io#1060]
### What happened?

At https://www.selenium.dev/documentation/webdriver/bidirectional/bidi_api/
The python version for the example `Listen to console.log events` uses the Log class directly.

The source code at https://github.com/SeleniumHQ/selenium/blob/9de853d91adeca219d8230fe73ca7e579f769999/py/selenium/webdriver/common/log.py

Specifies `This class is not to be used directly and should be used from the webdriver base classes.`

### What browsers and operating systems are you seeing the problem on?

N/A

**Comment by shbenzer** [comment]
@harsha509 Documentation at referenced link has been removed from site - this issue can likely be closed.

**Comment by harsha509** [comment]
Thank you for reviewing this, @shbenzer!

I’ll go ahead and close it as not valid.
