### ISSUE TITLE
Add language installationrequirements

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/seleniumhq.github.io#1072]
Based on a recent request in Selenium Slack, this page should also include links/info for language installation & probably minimum versions (or a link to where minimum version can be found in repo).

https://www.selenium.dev/documentation/webdriver/getting_started/install_library/

**Comment by diemol** [comment]
The current page has now information about minimum version and also where to find it in the repository. It does not include a link for language installation, and I spent a while looking for links and they all have either outdated information or incomplete information. 

I'd say we can close this for now and the language installation part ideally should be done by the users themselves.
