### ISSUE TITLE
[🚀 Feature]: Add PHP code examples

### ISSUE THREAD

**Issue by CViniciusSDias** [SeleniumHQ/seleniumhq.github.io#1074]
### Feature and motivation

There are code examples for some languages in the documentation and PHP has a great Selenium integration using [php-webdriver](https://github.com/php-webdriver/php-webdriver).

The PHP examples should be added to the documentation.

**Comment by diemol** [comment]
Not really because we do not provide docs and examples for other languages different to the ones we provide officially. Ideally, those examples should be created by that project in their documentation.
