### ISSUE TITLE
[🐛 Bug]: Documentation example for BiDirectional API is not full

### ISSUE THREAD

**Issue by kool79** [SeleniumHQ/seleniumhq.github.io#1078]
### What happened?

Open 
https://www.selenium.dev/documentation/webdriver/bidirectional/bidi_api_remotewebdriver/
and look into example for Register Basic Auth on java.
Example contains variable devToolsAtomicReference which is not defined in example. See: 

![scr_2022_07_19T01_29_04](https://user-images.githubusercontent.com/4625317/179628266-3c7162f2-efe9-45d3-b39f-c869ab73caf8.png)
 

### What browsers and operating systems are you seeing the problem on?

all

**Comment by diemol** [comment]
Fixed the links that show the code, and you can click on 
![image](https://user-images.githubusercontent.com/5992658/185914525-44791555-62b4-4730-ab02-1447e52564e5.png)

to see the full code example.
