### ISSUE TITLE
[🐛 Bug]: Unclear documentation for Selenium Grid Router

### ISSUE THREAD

**Issue by kool79** [SeleniumHQ/seleniumhq.github.io#1079]
### What happened?

In a [documentation for Router](https://www.selenium.dev/documentation/grid/components/) we have:

> It is the entry point of the Grid, all external requests will be received by it. The Router behaves differently depending on the request. If it is a new session request, the Router will add it to the New Session Queue. The Distributor regularly checks if there is a free slot. If so, the first matching request is removed from the New Session Queue. _The Router will receive the event and poll the New Session Queue to get the new session request._ If the request belongs to an existing session, the Router will send the session id to the Session Map, and the Session Map will return the Node where the session is running. After this, the Router will forward the request to the Node.

For me the sentence marked with italic font is unclear: 
1. How Router will recieve the event if there are no connection (see picture) between EventBus and Distributor with Router?

2.Why Router should poll Session Queue for new session requests? 
why it requires "new session request" if sessions should be created by Distributor? 
Also in a  previous sentence there is: "request is removed from the New Session Queue" -- so what data Router expect to find here? 

![scr_2022_07_19T01_49_32](https://user-images.githubusercontent.com/4625317/179631654-93039039-2567-4128-af34-afad639110d0.png)

### What browsers and operating systems are you seeing the problem on?

all

**Comment by diemol** [comment]
Good catch, @kool79! Seems we updated the code and the diagram, but not the docs. Just pushed something to fix that.
