### ISSUE TITLE
[🐛 Bug]: The sample for SeleniumJS has a typo in it that prevents it from executing

### ISSUE THREAD

**Issue by jamesmortensen** [SeleniumHQ/seleniumhq.github.io#1096]
### What happened?

On the page:  https://www.selenium.dev/selenium/docs/api/javascript/index.html

Under Usage:

```
const {Builder, By, Key, until} = require('selenium-webdriver');

(async function example() {
  let driver = await new Builder().forBrowser('firefox').build();
  try {
    await driver.get('http://www.google.com/ncr');
    await driver.findElement(By.name('q'));.sendKeys('webdriver', Key.RETURN);
    await driver.wait(until.titleIs('webdriver - Google Search'), 1000);
  } finally {
    await driver.quit();
  }
})();
```

`await driver.findElement(By.name('q'));.sendKeys('webdriver', Key.RETURN);`

There is a `.` right after the semicolon.  

### What browsers and operating systems are you seeing the problem on?

Chrome latest on Mac M1, but I don't think it matters.

**Comment by harsha509** [comment]
Hi @jamesmortensen,

The current documentation is generated with JS-dossier and generating docs with it now is hard as the package is not maintained anymore.

JS API docs needs to be updated, but It may take a while as am moving API docs to JSHint/typedoc!

Thanks,
Harsha

**Comment by harsha509** [comment]
Will attach to existing issue!
https://github.com/SeleniumHQ/selenium/issues/10185
