### ISSUE TITLE
[🐛 Bug]: Hugo is not installed in Gitpod, when spinning up Selenium docs

### ISSUE THREAD

**Issue by jags14385** [SeleniumHQ/seleniumhq.github.io#1098]
### What happened?

Every time I reopen my Gitpod workspace, I need to do `brew install hugo` before I can run `hugo server`

### What browsers and operating systems are you seeing the problem on?

on Gitpod.io

**Comment by diemol** [comment]
If you reopen the same workspace, you probably need to do it always if the first time it did not work. You should try to open a complete new workspace.

**Comment by jags14385** [comment]
Okay. Will give it a go and let you know the results

**Comment by jags14385** [comment]
Yes, it works . Thanks @diemol !! . Closing this issue.
