### ISSUE TITLE
[🚀 Feature]: Update selenium js docs to have a working code example at the end

### ISSUE THREAD

**Issue by nadvolod** [SeleniumHQ/seleniumhq.github.io#1122]
### Feature and motivation

I'm trying to help a customer and myself get up and running with selenium in JS. Going through the setup documentation and it's good. After the ["First Script"](https://www.selenium.dev/documentation/webdriver/getting_started/first_script/) step, it would be nice to have a link to an actual repo that runs. Instead, I find myself having to copy and paste code and setup an environment where I can run the test. Maybe add the example to Gitpod so that anyone can run it in a virtual environment. 

If I can get this example working for myself, I'll be happy to pass it along and configure it into Gitpod. Lemme know 😉

**Comment by diemol** [comment]
You can click on the link at the bottom right to get to the repository and full example.

![image](https://user-images.githubusercontent.com/5992658/184897141-8cfcf17a-1dc6-42aa-ab21-7019fa360753.png)

If you were looking for something else, please let me know and I can reopen this.

**Comment by nadvolod** [comment]
@diemol thanks man. Yea, that's working 👍 Maybe an upgrade could be to also add a link that says "run in Gitpod" and have the code run there? Avoids having to download and install stuff.

**Comment by diemol** [comment]
I'd love to get a PR for that!
