### ISSUE TITLE
[🐛 Bug]: Getting Started Open Browser starter code

### ISSUE THREAD

**Issue by jlafleur93** [SeleniumHQ/seleniumhq.github.io#1143]
### What happened?

https://www.selenium.dev/documentation/webdriver/getting_started/open_browser/
1) Open Link
2) Click JavaScript on the code samples
3) You can notice that the starter code includes suite tests
4) if you run this as your code it will not run either

I wouldn't mind PRing this, but I was wondering where would I include new files for the starter code on this page?

### What browsers and operating systems are you seeing the problem on?

All browsers/OS
Incorrect documentation

**Comment by harsha509** [comment]
Hi @jlafleur93 ,

Thank you for raising an issue. I believe the code samples are precise!

You need to follow the below steps to run the tests:
1. Install `selenium-webdriver `via npm
2. Install `chromedriver` via npm
3. Run tests with the command `mocha <testfile.js>`

looks like we need to add docs for running code samples, if you'd like to help us, can you send a PR on the instructions to run tests?

Thanks,
Harsha

**Comment by Dor-bl** [comment]
I think users should first refer to the [Install Library](https://www.selenium.dev/documentation/webdriver/getting_started/install_library/) page, where they can find the 1st step.
regarding docs for installing chrome driver via npm, something we should consider adding in the [Install Drivers](https://www.selenium.dev/documentation/webdriver/getting_started/install_drivers/) page

**Comment by diemol** [comment]
@jlafleur93 I do not understand what is missing here. That file is part of a test suite placed here https://github.com/SeleniumHQ/seleniumhq.github.io/tree/trunk/examples/javascript, which also runs in GitHub actions. 

What are you missing in the docs?

**Comment by diemol** [comment]
Closing this as we never got more information.
