### ISSUE TITLE
[🐛 Bug]: Step 5: Rebase seems to not work

### ISSUE THREAD

**Issue by Dor-bl** [SeleniumHQ/seleniumhq.github.io#1144]
### What happened?

on the  [Contributing page](https://www.selenium.dev/documentation/about/contributing/)
while trying to execute step 5: Rebase the below code doesn't work, at least for me. 
`% git fetch upstream`
`% git rebase upstream/trunk`

while using the below does work:
`% git fetch origin`
`% git rebase origin/trunk`

is it just me or others who experience this issue and need to update the docs?

**Disclaimer**
not so familiar with git actions, that's why I opened this issue.

### What browsers and operating systems are you seeing the problem on?

Not relevant

**Comment by diemol** [comment]
In general `upstream` is whatever origin the repository has. Nowadays, `origin` seems to be more common. I just updated the docs.

**Comment by Dor-bl** [comment]
> In general `upstream` is whatever origin the repository has. Nowadays, `origin` seems to be more common. I just updated the docs.

Cool, thanks for the info @diemol!
