### ISSUE TITLE
[🐛 Bug]: The search doesn't work on https://www.selenium.dev

### ISSUE THREAD

**Issue by JulienBreton** [SeleniumHQ/seleniumhq.github.io#1148]
### What happened?

1. Go to https://www.selenium.dev/documentation/
2. In the search field ("Search this site...) type Wait
3. Press entrer

Result :
The search results are empty and there is an error in the consol :

`js@3:8 Uncaught TypeError: Cannot read properties of null (reading '__k')
    at Ae (js@3:8:18218)
    at js@3:8:107254
    at ?q=search:19:30`

![search_site_selenium](https://user-images.githubusercontent.com/2854856/186904657-835baad9-23f4-41b4-93bf-5fdde7d3fa19.png)

### What browsers and operating systems are you seeing the problem on?

Firefox 104.0 (64 bits) / Ubuntu
Chrome Version 104.0.5112.79 (Build officiel) (64 bits) / Ubuntu

**Comment by Dor-bl** [comment]
This repro for all search input

**Comment by Dor-bl** [comment]
Fixed by recent updates to docsy and Hugo made by @diemol  
The issue can be closed
