### ISSUE TITLE
 SearchContext link broken on Locating elements documentation pag

### ISSUE THREAD

**Issue by NelsonPython** [SeleniumHQ/seleniumhq.github.io#115]
## 🐛 Bug Report
A link is broken in the documentation

## To Reproduce
Click this link:
https://selenium.dev/selenium/docs/api/java/org/openqa/selenium/SearchContext.html%3ESearchContext

Or you can navigate to the Locating elements page (link below) and find this sentence, then click the SearchContext link:
You can do this because both the WebDriver and WebElement types implement the SearchContext interface.

Link to Locating elements page:
https://selenium.dev/documentation/en/getting_started_with_webdriver/locating_elements/

## Expected behavior
I expected to see a page describing
![selBug](https://user-images.githubusercontent.com/34105635/70200277-ba1db200-16c8-11ea-835f-ec276ff37d11.png)

## Environment
Google Chrome Version 78.0.3904.108 (Official Build) (64-bit)
Microsoft Edge

**Comment by Harsha509** [comment]
Hi @NelsonPython,

Thanks for reporting the issue. This will be resolved with commit https://github.com/SeleniumHQ/seleniumhq.github.io/pull/116

Happy Testing!
