### ISSUE TITLE
[🐛 Bug]: Can't Capture Network API Fetch response using JavaScript

### ISSUE THREAD

**Issue by JessNah** [SeleniumHQ/seleniumhq.github.io#1155]
### What happened?

Hi, I've seen that it is possible to retrieve network API response body's using Selenium and Chrome DevTools.
I have the goal of retrieving the response body strings from API requests such as those that can be seen over the Chrome browser Network tab. 
I do not intend to manipulate the response, I only wish to be able to extract these strings to a log.
I have made numerous efforts using cdpConnection and selenium-webdriver (also using sendAndGetDevToolsCommand)...

I've gotten close by copying and changing the code seen here:
https://github.com/SeleniumHQ/selenium/blob/85a785684d8ce37f99cb64c22597c44021d6fb34/javascript/node/selenium-webdriver/lib/webdriver.js#L1365-L1384

I cannot straight up use .onIntercept method because I do not intend to manipulate/provide a new response body, I only wish to obtain the original FETCH response body. 

I have it so that the "Fetch.requestPaused" method message triggers and I from there do 2 things:
execute 'Fetch.getResponseBody' and execute 'Fetch.continueRequest'
The continueRequest works but it doesn't seem like the getResponseBody is working, I only receive undefined. I cannot find any helpful documentation anywhere on how I can achieve this. Would really appreciate some help to even know if this is possible.

### How can we reproduce the issue?

```shell
This code is close to working - fetch.requestPaused works 
and then I can look at the request params and I can then successfully do a 
Fetch.continueRequest with the requestId from the params.


const chromeOptions = new Options();
     chromeOptions.addArguments("--no-sandbox");
     chromeOptions.addArguments("--dsiable-dev-shm-usage");
     chromeOptions.addArguments("--disable-gpu");
     chromeOptions.addArguments("--runInBand");
     chromeOptions.addArguments('--ignore-ssl-errors=yes');
     chromeOptions.addArguments('--ignore-certificate-errors');
     const chromeCapabilities = Capabilities.chrome();
     chromeCapabilities.setPageLoadStrategy('eager');
 
     const serviceBuilder = new ServiceBuilder(path);
     const driver = await new Builder()
       .forBrowser('chrome')
       .setChromeService(serviceBuilder)
       .setChromeOptions(chromeOptions)
       .withCapabilities(chromeCapabilities)
       .build();

const cdpConnection = await driver.createCDPConnection('page');
    
await cdpConnection.execute('Fetch.enable', {
  patterns: [{ requestStage: "Response" }]
}, null);
await cdpConnection.execute(
  'Network.setCacheDisabled',
  {
	cacheDisabled: true,
  },
  null
);    

cdpConnection._wsConnection.addEventListener("message", async (e) => { 
      if(e && e.data){
        const message = e.data;
        const obj = JSON.parse(message);\
        if(obj.method && obj.params){
          if(obj.method === "Fetch.requestPaused"){
            if (obj.params.request.url.includes(baseAddress + "/my/api")) {
              let test = await cdpConnection.execute('Fetch.getResponseBody', {
                requestId: obj.params.requestId,
              });
              console.log(test); // ------>  THIS RETURNS UNDEFINED !!!!
          }
          cdpConnection.execute('Fetch.continueRequest', {  // ------>  THIS SEEMS LIKE ITS WORKING FOR CONTINUEREQUEST
              requestId: obj.params.requestId
            })
        }
      }
    });


```

### Relevant log output

```shell
<Not applicable>
```

### Operating System

Windows

### Selenium version

Node v14.16.1 javascript

### What are the browser(s) and version(s) where you see this issue?

Chrome 104

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 104

**Comment by JessNah** [comment]
Sorry I closed the issue because I was going to re-open a new issue as I made some progress on my original problem so my request has changed a little. Instead, just re-opened updated the details and title of the current issue.

**Comment by tenbits** [comment]
The problem is, that the `CDPConnection` class is not properly implemented yet: [CDPConnection.js#L18](https://github.com/SeleniumHQ/selenium/blob/1a73c3f9f37c3f6a424fff92a7f48966c41d3cc0/javascript/node/selenium-webdriver/devtools/CDPConnection.js#L18) It doesn't return any promise. This is message-based communication, though it adds the Message ID, to retrieve later the Response Message from the WebSocket, but it doesn't  handle that response message here [webdriver.js#L1239](https://github.com/SeleniumHQ/selenium/blob/1a73c3f9f37c3f6a424fff92a7f48966c41d3cc0/javascript/node/selenium-webdriver/lib/webdriver.js#L1239)

Until it is implemented you can use custom CDPConnection class. Here is the TypeScript implementation.

```ts
let ID = 0;

type TAwaiter = {
    id: number
    resolve: (value: any) => void
    reject: (reason?: any) => void
};

export class CDPConnection {

    private requests: Map<number, TAwaiter> = new Map();

    constructor(private wsConnection, private sessionId: string) {
        wsConnection.on('message', this.onMessage.bind(this));
        wsConnection.on('close', this.onClose.bind(this));
        wsConnection.on('error', this.rejectAll.bind(this));
    }

    execute <T = any> (method, params, onMessageSent: (err) => any = null): Promise<T> {

        let message = {
            sessionId: this.sessionId,
            method,
            params,
            id: ++ID,
        };
        let listener = {
            id: message.id,
            resolve: null,
            reject: null,
        };
        let promise = new Promise<T>((resolve, reject) => {
            listener.resolve = resolve;
            listener.reject = reject;
        });

        this.requests.set(listener.id, listener);

        this.wsConnection.send(JSON.stringify(message), onMessageSent)
        return promise;
    }

    private onMessage (message: Buffer) {
        let params = JSON.parse(message.toString());
        let { id, result } = params;

        if (id != null && this.requests.has(id)) {
            this.requests.get(id)?.resolve?.(result);
            this.requests.delete(id);
        }
    }

    private onClose () {
        this.rejectAll(new Error(`CDPConnection: The underlying connection was closed`));
    }

    private rejectAll(error: Error) {

        let awaiters = this.requests.values();
        this.requests = new Map();

        for (let awaiter of awaiters) {
            awaiter.reject(error);
        }
    }
}
```

Then you initialize the class and use it for your calls, after you create the inner cdp connection, as `createCDPConnection` establishes the WebSocket connection.

```ts
const cdpConnection = await driver.createCDPConnection('page');
const myCdpConnection = new BiDiCDPConnection(driver._wsConnection, driver.sessionId);
//...
let response = await myCdpConnection.execute('Network.getResponseBody', {
    requestId: someRequestID,
});
```

**Comment by JessNah** [comment]
@tenbits I will give this a go, I really really appreciate you taking the time to provide this example. Very helpful, thank you!

**Comment by JessNah** [comment]
@tenbits I will give this a go, I really really appreciate you taking the time to provide this example. Very helpful, thank you!

**Comment by tenbits** [comment]
I use this to monitor ([selenium-query/BrowserNetworkMonitor.ts](https://github.com/tenbits/selenium-query/blob/master/src/webdriver/network/BrowserNetworkMonitor.ts)) and intercept ([selenium-query/BrowserNetworkInterceptor.ts](https://github.com/tenbits/selenium-query/blob/master/src/webdriver/network/BrowserNetworkInterceptor.ts))  requests.  You can take and modify those classes for your initial needs.
