### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by neobis001** [SeleniumHQ/seleniumhq.github.io#1167]
### What happened?

In this [site](https://www.selenium.dev/documentation/webdriver/browser/windows/#create-new-window-or-new-tab-and-switch), in the section "Switching windows or tabs", the bottom of the Python example covers up some of the documentation text. Here's a picture of it.

![text-is-cut-off](https://user-images.githubusercontent.com/10540174/190279796-04e88961-8378-451b-b4c7-964eac7e0d94.png)
 

### What browsers and operating systems are you seeing the problem on?

Google Chrome
Version 105.0.5195.127 (Official Build) (64-bit)
Windows 10 Pro

**Comment by titusfortner** [comment]
Thanks for raising this. We have new code that is supposed to check the contents of the tab and calculate the largest and set the height of all of them to that value. I'll figure out why it isn't detecting the content height properly.

**Comment by neobis001** [comment]
I looked a little at it myself. I saw your [commit](https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1157/commits/73e09e02bdeca1af552d5a6360c0a5d82a2f9412). I didn't know Javascript, but I did know Chrome's Inspect tool. I looked at tabpane-persist.js. I checked the "heightMap" dictionary. For the picture I sent, heightMap["tabs-1-content"] was relevant. It looked correct. Also the Math.max.apply line looked correct. I used a breakpoint to edit the Math.max.apply line to add 100 pixels more to the "tabContent" height. Now the website looks fine.

Here's a picture of me using Inspect. Overall, I think your code is fine. Maybe just add more padding for the height?

![inspect-tool-for-tab-code](https://user-images.githubusercontent.com/10540174/190484292-c4467670-05db-4546-af97-770199d871d9.png)

**Comment by titusfortner** [comment]
yeah, but the vast majority of tabs don't need padding and I have no idea if 100 is always enough. 

I also don't know JS, so I'm a bit at a loss with it. When I put a debug point in the code and loaded the page, and executed maxHeight in the console it gave me the right value, but when I let it execute from the JS file it gave me the wrong value. I have no idea why they would be different. For now I reverted the change. 

Maybe a docsy dev will know what is happening — https://github.com/google/docsy/pull/1227#issuecomment-1248406934
