### ISSUE TITLE
[🐛 Bug]: Miss the language switch in mobile view

### ISSUE THREAD

**Issue by alaahong** [SeleniumHQ/seleniumhq.github.io#1169]
### What happened?

It's fine as below on full size view model
![image](https://user-images.githubusercontent.com/3264250/190881658-80d37c91-8357-4fa9-aefe-1023f5ec43ed.png)

But the language switch missed in mobile view
![image](https://user-images.githubusercontent.com/3264250/190881630-e9b7f223-64ef-4fbb-94d2-c5b80fd0068c.png)

Which means user might have no possible to switch local language on mobile or pad device.

### What browsers and operating systems are you seeing the problem on?

Windows
Edge/Chrome

**Comment by titusfortner** [comment]
Hmm, it's showing up for me on my phone. 

![Screenshot_20220918-083601_Chrome](https://user-images.githubusercontent.com/777185/190904984-c562029d-d09f-41fb-bf5c-bbe3da180399.jpg)

**Comment by titusfortner** [comment]
@alaahong Looks like if you click the 2nd hamburger it will show up. Not ideal, but the option is there. 
I think this is going to be an issue with the Docsy template, so we probably would need to raise it there. 

<img width="483" alt="Screen Shot 2022-09-18 at 9 21 07 AM" src="https://user-images.githubusercontent.com/777185/190911835-c696b97a-3eb2-485d-b974-a79d10df8dfe.png">
<img width="492" alt="Screen Shot 2022-09-18 at 9 21 19 AM" src="https://user-images.githubusercontent.com/777185/190911834-ece8d600-0822-4d9f-b686-af58e3bba423.png">

**Comment by titusfortner** [comment]
Going to close this. You can raise an issue with Docsy if you think the iPhone implementation should be improved. Thanks.
