### ISSUE TITLE
[🐛 Bug]: DeprecationWarning: executable_path has been deprecated, please pass in a Service object   browser = webdriver.Chrome(path

### ISSUE THREAD

**Issue by jishuge334** [SeleniumHQ/seleniumhq.github.io#1181]
### What happened?

我不知道我的路径哪里出了问题，但是当我运行代码的时候，也能打开网页，也不会弹出去，就不知道我的路径是什么问题

### What browsers and operating systems are you seeing the problem on?

谷歌浏览器
![2F07BAKJ0P` EQ_WTD9UQ%O](https://user-images.githubusercontent.com/114509708/192710455-2386fb56-f9f5-4312-9a54-7d7eba9896c0.png)

**Comment by alaahong** [comment]
Hi,

You can follow below guide on first script, seems you just miss the chrome path
https://www.selenium.dev/zh-cn/documentation/webdriver/getting_started/first_script/#1-%E4%BD%BF%E7%94%A8%E9%A9%B1%E5%8A%A8%E5%AE%9E%E4%BE%8B%E5%BC%80%E5%90%AF%E4%BC%9A%E8%AF%9D

**Comment by diemol** [comment]
Closing as we did not get more information.
