### ISSUE TITLE
[🚀 Feature]: Add James Mortensen to the list of docker-selenium committers on the website

### ISSUE THREAD

**Issue by jamesmortensen** [SeleniumHQ/seleniumhq.github.io#1183]
### Feature and motivation

Recently, I've become a committer on docker-selenium.  Is it possible to add me to the website under the docker-selenium committers?  

**Page:**
https://www.selenium.dev/project/structure/#docker_selenium_committers

**Location:**
https://github.com/SeleniumHQ/seleniumhq.github.io/blob/trunk/website_and_docs/content/project/structure/_index.html

**GitHub API Profile:**
https://api.github.com/users/jamesmortensen

Thank you!

**Comment by harsha509** [comment]
Hi @jamesmortensen ,

Its done! :slightly_smiling_face:

Thank you for the work being done to docker selenium!

https://www.selenium.dev/project/structure/#docker_selenium_committers

Thanks,
Harsha
