### ISSUE TITLE
Search form does not work

### ISSUE THREAD

**Issue by shannonpearson** [SeleniumHQ/seleniumhq.github.io#119]
<img width="541" alt="Screen Shot 2019-12-05 at 12 30 33 PM" src="https://user-images.githubusercontent.com/23521216/70258921-1fba7e80-175b-11ea-82b3-2e6310ca5001.png">
<img width="716" alt="Screen Shot 2019-12-05 at 12 30 48 PM" src="https://user-images.githubusercontent.com/23521216/70258928-22b56f00-175b-11ea-82c5-294079dea74b.png">

## 🐛 Bug Report

Did you find something wrong with the site or the documentation? Please describe
your finding in a clear and concise way. 

Search form does not work or show any error messaging.
Typing in the search box results in console errors (see screenshots for Chrome and Safari).
Pressing enter to search causes no change - search is not executed and text remains in the text box.

## To Reproduce

How can we reproduce the issue you found? Please tell us how we can do that. 
Don't forget to add:

* Absolute link where the issue was found
* Screenshot (if needed) 
* The environment you had when the issue was found (see below)

Tell us the detailed steps to reproduce it:

Navigate to any page at https://selenium.dev/documentation/en/
Type text in the search box.
Press Enter to search. 

## Expected behavior

What do you expected to happen? How should have it worked?

When text is entered into the search form and Enter is pressed, the search should be executed and search results should be shown on the page.

## Environment

* OS: OSX Mojave 10.14.6
* Browser: Chrome, Safari, Firefox
* Browser version: Chrome 78.0.3904.108, Safari 13.0.3 (14608.3.10.10.1), Safari 68.0

**Comment by bongosway** [comment]
@shannonpearson don't think this is a defect. It looks like the default way Lunrjs works. 
Looking through the JS, this is implemented as AutoComplete so it simply searches on the visible text on the page and highlights any matches found and was not intended to render an actual page with search results.

I might be wrong and stand to be corrected.

**Comment by diemol** [comment]
Good catch @shannonpearson, it seems there is an issue for multilingual sites in the Hugo theme we use, https://github.com/matcornic/hugo-theme-learn/issues/274, I never saw it because I tried it when it was only in English.

I will try to have a look during the holidays and see how we can help the Hugo theme so multilingual search works.

**Comment by diemol** [comment]
I made some changes in the structure of the translation and the search works now. 

![image](https://user-images.githubusercontent.com/5992658/93714118-dd82f200-fb60-11ea-9a6b-900fe1e40028.png)
