### ISSUE TITLE
[🐛 Bug]: missing word

### ISSUE THREAD

**Issue by jsaponara** [SeleniumHQ/seleniumhq.github.io#1196]
### What happened?

"have had to rely on with all of its frustrations" is missing something.  maybe CDP?
at https://www.selenium.dev/documentation/webdriver/bidirectional/

### What browsers and operating systems are you seeing the problem on?

this is a docs bug.

**Comment by pujagani** [comment]
@jsaponara Yes, you are right. Thank you for catching that. Would you like to help by contributing to our docs to make the fix? Contributions are always welcome!

**Comment by diemol** [comment]
PR was merged, closing this.
