### ISSUE TITLE
[🚀 Feature]: Selenium Manager

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/seleniumhq.github.io#1201]
### Feature and motivation

* Write Blog post before 4.6. Ideas:
    * beta release
    * Limited to Firefox/Chrome/Edge
    * No IE Driver snap support, no M1 support
    * Does not affect existing implementations
    * Delete driver manager / drivers in PATH and it should still "just work"
    * Discuss next steps
    * Link to readme, but no implementation details, yet
* Remove existing driver manager references from examples where possible (IE Driver is the primary exception I think)

**Comment by diemol** [comment]
I think this was already done and published.
