### ISSUE TITLE
[🐛 Bug]: TypeError: command.setParameter is not a function

### ISSUE THREAD

**Issue by Moogamouth** [SeleniumHQ/seleniumhq.github.io#1216]
### What happened?

The selenium-webdriver NPM module seems to be trying to run a non existent function when I run the function
```js
await driver.execute("return performance.getEntriesByType(\"resource\")");
```
Where
```js
driver = await new Builder().forBrowser("chrome").setChromeOptions(new chrome.Options().setChromeBinaryPath(`${__dirname}/Chrome/Application/chrome.exe`)).build();
```
It returns
```
\selenium-webdriver\lib\webdriver.js:737
    command.setParameter('sessionId', this.session_)
            ^

TypeError: command.setParameter is not a function
```

### What browsers and operating systems are you seeing the problem on?

Chrome 107.0.5304.88, Windows 10

**Comment by diemol** [comment]
Please create this issue in the https://github.com/SeleniumHQ/selenium repository. This repository is the documentation.
