### ISSUE TITLE
[🐛 Bug]: Unable to execute request for an existing session: Strategy is not implemented: css selector

### ISSUE THREAD

**Issue by ValzRon** [SeleniumHQ/seleniumhq.github.io#1224]
### What happened?

Im currently running Selenium Grid 4 (v4.5.0) and trying to get it running with Appium 2.0 via Relay.

**Here is the snippet:**

```
    // create a List of multiple elements with id
    @AndroidFindBy(id = "imageView_icon_dashboardTile")
    private List<WebElement> dashboardTitleIcons;
   
    private WebElement getDashboardTile() {
        return dashboardTitleIcons.get(0);
    }
    
    public void clickFirstTile() {
        getDashboardTile().click();
    }
```

**This will result in -->**
org.openqa.selenium.ScriptTimeoutException: Unable to execute request for an existing session: Strategy is not implemented: css selector
For documentation on this error, please visit: https://selenium.dev/exceptions/#invalid_selector_exception
Build info: version: '4.5.0', revision: 'fe167b119a'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_351'
Driver info: org.openqa.selenium.grid.node.CustomLocatorHandler$CustomWebDriver
Command: [d1ffa964-74b5-409f-8f60-9adb5360afda, findElements {using=id, value=imageView_icon_dashboardTile}]
Capabilities {}
Session ID: d1ffa964-74b5-409f-8f60-9adb5360afda
Build info: version: '4.5.0', revision: 'fe167b119a'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.17'
Driver info: io.appium.java_client.android.AndroidDriver
Command: [d1ffa964-74b5-409f-8f60-9adb5360afda, findElements {using=id, value=imageView_icon_dashboardTile}]
.....

**Ive also tried something like -->** 
`private List<WebElement> dashboardTitleIcons = driver.findElements(By.Id("imageView_icon_dashboardTile"));`
same result.
When I run the session directly against Appium all works fine. There was a Problem on Appiums side at one time, where AndroidFindBy couldnt handle Lists anymore and would revert to css selector, but its fixed already -->
 https://github.com/appium/java-client/issues/1621
Also it might not only be limited to Lists of WebElement.

Thnx in advance!

### What browsers and operating systems are you seeing the problem on?

Windows 10
Appium 2.0.0-beta.46 with Espresso Driver
Selenium 4.5.0
Selenium Grid 4 server running on localhost
Tests running against an Android Device API Level 23

**Comment by titusfortner** [comment]
Since "ID" is no longer supported by W3C specification, Selenium maintains w3c compliance and backwards compatibility with the `By.Id` locator by automatically converting it to CSS, which Appium doesn't support. There should be a way to use an Appium locator that doesn't convert ID to CSS.
