### ISSUE TITLE
[🐛 Bug]: selenium popup alert is not working [onclick]

### ISSUE THREAD

**Issue by user-2608** [SeleniumHQ/seleniumhq.github.io#1242]

**Comment by titusfortner** [comment]
This is not the best place to get help with problems like this. 

💬 Please ask questions at:

📫 The [Selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
📮 [StackOverflow](https://stackoverflow.com/questions/tagged/selenium)
🗣 Our [IRC/Slack/Matrix channels](https://www.selenium.dev/support/) where the community can help you as well
