### ISSUE TITLE
[🐛 Bug]: Should we use a lambda expression in the example in Java for FluentWait ?

### ISSUE THREAD

**Issue by JulienBreton** [SeleniumHQ/seleniumhq.github.io#1243]
### What happened?

[In the page explaining the Waits, in the FluentWait part the example in Java contains :](https://www.selenium.dev/documentation/webdriver/waits/#fluentwait)
`````
WebElement foo = wait.until(new Function<WebDriver, WebElement>() {
  public WebElement apply(WebDriver driver) {
    return driver.findElement(By.id("foo"));
  }
});
``````

but when I use it [Sonar Lint](https://www.sonarsource.com/products/sonarlint/) says : 

> Anonymous inner classes containing only one method should become lambdas (java:S1604)
Code smell Major
Before Java 8, the only way to partially support closures in Java was by using anonymous inner classes. But the syntax of anonymous classes may seem unwieldy and unclear.
With Java 8, most uses of anonymous inner classes should be replaced by lambdas to highly increase the readability of the source code.
Note that this rule is automatically disabled when the project’s sonar.java.source is lower than 8.

Should we use a lambda expression in this example ?

```
WebElement foo = wait.until(driver -> {
 return driver.findElement(By.id("foo"));
});
```

### What browsers and operating systems are you seeing the problem on?

Not applicable

**Comment by titusfortner** [comment]
Sounds good. Can you make the PR?

**Comment by JulienBreton** [comment]
Yes I will try to do it.

**Comment by titusfortner** [comment]
Thanks!
