### ISSUE TITLE
[🐛 Bug]: There is a typo in "File downloads" page

### ISSUE THREAD

**Issue by GregoryShen** [SeleniumHQ/seleniumhq.github.io#1244]
### What happened?

There is a type in "File downloads" page:

![File donwloads](https://user-images.githubusercontent.com/1592347/204076807-514f348e-2e76-42e5-8b53-41903dc49ff5.png)

Guess should be "then" instead of "the"

### What browsers and operating systems are you seeing the problem on?

Chrome and Win 10

**Comment by titusfortner** [comment]
please submit a PR to fix?

**Comment by harsha509** [comment]
Fixed with commit https://github.com/SeleniumHQ/seleniumhq.github.io/commit/38871397073cab0fc8a6e831e2fe7cb96256f096 !
