### ISSUE TITLE
[🐛 Bug]: Ruby code example in Browser Options doesn't work

### ISSUE THREAD

**Issue by jlucartc** [SeleniumHQ/seleniumhq.github.io#1246]
### What happened?

Ruby code example from [documentation](https://www.selenium.dev/documentation/webdriver/drivers/options/) didn't run as expected.

### Code example from documentation

```
require 'selenium-webdriver'
caps = Selenium::WebDriver::Remote::Capabilities.chrome
caps.page_load_strategy='normal'

driver = Selenium::WebDriver.for :chrome, :desired_capabilities => caps
driver.get('https://www.google.com')
```

### Expected results
Opening browser and visiting webpage

### Current results
```
/home/luca/.rvm/gems/ruby-3.0.0/gems/selenium-webdriver-4.6.1/lib/selenium/webdriver/common/driver.rb:319:in `create_bridge': unknown keyword: :desired_capabilities (ArgumentError)
	from /home/luca/.rvm/gems/ruby-3.0.0/gems/selenium-webdriver-4.6.1/lib/selenium/webdriver/common/driver.rb:74:in `initialize'
	from /home/luca/.rvm/gems/ruby-3.0.0/gems/selenium-webdriver-4.6.1/lib/selenium/webdriver/common/driver.rb:47:in `new'
	from /home/luca/.rvm/gems/ruby-3.0.0/gems/selenium-webdriver-4.6.1/lib/selenium/webdriver/common/driver.rb:47:in `for'
	from /home/luca/.rvm/gems/ruby-3.0.0/gems/selenium-webdriver-4.6.1/lib/selenium/webdriver.rb:89:in `for'
	from main.rb:21:in `<main>'
```
### My Fix
Changing the original code to the code below fixed the issue. Seems like the Ruby API wasn't updated in the docs.
```
require 'selenium-webdriver'
caps = Selenium::WebDriver::Remote::Capabilities.chrome
caps.page_load_strategy='normal'

# changed from :desired_capabilites to :capabilities
driver = Selenium::WebDriver.for :chrome, :capabilities => caps
driver.get('https://www.google.com')
```

### What browsers and operating systems are you seeing the problem on?

Ruby version: 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]
Gem version: selenium-webdriver 4.6.1
OS: Ubuntu 20.04.3 LTS

**Comment by titusfortner** [comment]
Yes, this should be `Options` not `Capabilities` now. The correct code here is:

```ruby
require 'selenium-webdriver'
options = Selenium::WebDriver::Options.chrome
options.page_load_strategy = :eager

driver = Selenium::WebDriver.for :chrome, options: options
driver.get('https://www.google.com')
```

**Comment by jlucartc** [comment]
@titusfortner It seems that both `Selenium::Webdriver::Options` and `Selenium::WebDriver::Remote::Capabilities` were meant to setup the browser startup configuration, according to the [rubydocs](https://www.rubydoc.info/gems/selenium-webdriver/Selenium/WebDriver/Remote/Capabilities). Is there any document showing the current API's architecture/design, specifying what is currently being used/develop and what is being deprecated?

**Comment by titusfortner** [comment]
"Capabilities" are the old way that we need to deprecate/clean up. "Options" are the new way that are supported going forward. 

tbh, I've been avoiding this work because the Ruby capabilities code is my nemesis and every time I make changes I do something wrong. :)

**Comment by harsha509** [comment]
Updated code samples replacing capabilities with `options` !
