### ISSUE TITLE
[🐛 Bug]: PrintOptions Orientation Enum Wrong

### ISSUE THREAD

**Issue by prestonbarnett** [SeleniumHQ/seleniumhq.github.io#1285]
### What happened?

I'm using headless chrome with Selenium to generate PDFs from HTML content. While setting the preferred orientation, it seems that the enum constants for PORTRAIT and LANDSCAPE are reversed- at least for chrome. 

When using the following print options, the generated PDF will be portrait.
```
PrintOptions printOptions = new PrintOptions();
printOptions.setBackground(true);
printOptions.setOrientation(PrintOptions.Orientation.LANDSCAPE);
```

![image](https://user-images.githubusercontent.com/60716321/213037109-6021a0b5-ac04-41bc-a202-6ba5065245c0.png)

However, when using ```PrintOptions.Orientation.PORTRAIT```, the generated PDF will be landscape.

### What browsers and operating systems are you seeing the problem on?

Chrome: Version 107.0.5304.110 (Official Build) (64-bit)
OS: Ubuntu 22.04.1 LTS

**Comment by diemol** [comment]
Could you please create the issue here https://github.com/SeleniumHQ/selenium/issues/new/choose with a way to reproduce it? Thanks!
