### ISSUE TITLE
[🐛 Bug]: Clarify xpath notation peculiarity //.

### ISSUE THREAD

**Issue by OtterVersion** [SeleniumHQ/seleniumhq.github.io#1290]
### Feature and motivation

In normal xpath usage "./xxxx" is used to search in current node, in selenium notation(python) this gives an error.
Instead ".//xxxx" searches in current element.

I feel this peculiarity should be mentioned in Selenium documentation.
Specifically, under 4.3 in:
https://selenium-python.readthedocs.io/locating-elements.html

I'm however a novice and hope that someone can write a good example.

**Comment by diemol** [comment]
https://selenium-python.readthedocs.io are not the official Selenium docs, https://www.selenium.dev/documentation/ is the official documentation.
