### ISSUE TITLE
[🐛 Bug]: After installing webdriver for chrome, getting exception in running Selenium with Python

### ISSUE THREAD

**Issue by surbhiahuja** [SeleniumHQ/seleniumhq.github.io#1307]
### What happened?

Code used:

from selenium import webdriver
from selenium.webdriver.common.by import By

def test_eight_components():
    driver = webdriver.Chrome()

    driver.get("https://www.selenium.dev/selenium/web/web-form.html")

    title = driver.title
    assert title == "Web form"

    driver.implicitly_wait(0.5)

    text_box = driver.find_element(by=By.NAME, value="my-text")
    submit_button = driver.find_element(by=By.CSS_SELECTOR, value="button")

    text_box.send_keys("Selenium")
    submit_button.click()

    message = driver.find_element(by=By.ID, value="message")
    value = message.text
    assert value == "Received!"

    driver.quit()

test_eight_components()

Expected Result: Chrome driver should open
Actual Result: Getting, selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary

<img width="1354" alt="Screenshot 2023-02-13 at 9 56 13 AM" src="https://user-images.githubusercontent.com/42321035/218370376-061b0858-4e7d-426a-9871-104afa6fd8fa.png">

### What browsers and operating systems are you seeing the problem on?

environment details:
macOS Monterey, version: 12.4
Google chrome : Version 110.0.5481.77 (Official Build) (arm64)
chrome Driver: https://chromedriver.storage.googleapis.com/index.html?path=110.0.5481.77/
Selenium installed using pip3 install selenium

**Comment by diemol** [comment]
The error says you do not have Chrome installed. Please install Chrome as well.

Also, issues related to Selenium should be created here https://github.com/SeleniumHQ/selenium. This is the issue tracker for documentation.

**Comment by surbhiahuja** [comment]
I have installed Chrome and chrome driver already on my system. Still getting this error. I will reopen the issue in the above suggested link. Thanks, @diemol
