### ISSUE TITLE
Wrong SSL Certificate at www.selenium.dev

### ISSUE THREAD

**Issue by fastrde** [SeleniumHQ/seleniumhq.github.io#131]
## 🐛 Bug Report

The SSL certificate shown at **www**.selenium.dev has the common name www.github.com and is not valid for www.selenium.dev

## To Reproduce

Click on [https://www.selenium.dev](https://www.selenium.dev)

## Expected behavior

That the Certificate is valid for the domain https://www.selenium.dev

**Comment by diemol** [comment]
Thanks for reporting this @fastrde, we will have a look.

**Comment by mister-prog** [comment]
Hello! Now is already the 29th of January 2020, but selenium.dev and selenium.org still out of service. What's happened and what to do?
![image](https://user-images.githubusercontent.com/31521586/73334519-f9f2b700-427d-11ea-901d-76b07fb247d0.png)

**Comment by barancev** [comment]
@mister-prog Your issue is not related to certificates, and I can't confirm it.

You can use this service to check if site is down or it's your local misconfiguration: https://downforeveryoneorjustme.com/selenium.dev

**Comment by diemol** [comment]
Thank you for reporting, after a bit of Googling, this was the solution
https://github.com/SeleniumHQ/seleniumhq.github.io/commit/ac73472099a26fa21222940b3fa733eb2b787102
