### ISSUE TITLE
[🐛 Bug]: The source code for languages (java/python/...) is not displayed as formatted text

### ISSUE THREAD

**Issue by interactive-training** [SeleniumHQ/seleniumhq.github.io#1313]
### What happened?

I navigate to the page https://www.selenium.dev/documentation/webdriver/interactions/cookies/
The source code example for Java tab is not displayed correctly. it displays like junk characters. It is not readable.
It displayed correctly when I visited last time.
Now it is displaying as below..
=====
import org.openqa.selenium.*; import org.openqa.selenium.chrome.ChromeDriver; public class getCookieNamed { public static void main(String[] args) { WebDriver driver = new ChromeDriver(); try { driver.get("http://www.example.com"); driver.manage().addCookie(new Cookie("foo", "bar")); // Get cookie details with named cookie 'foo' Cookie cookie1 = driver.manage().getCookieNamed("foo"); System.out.println(cookie1); } finally { driver.quit(); } } }
=======

### What browsers and operating systems are you seeing the problem on?

Chrome version 110, Windows 11

**Comment by diemol** [comment]
Thank you for reporting this. Just made a fix and it should be reflected in the next deployment.
