### ISSUE TITLE
[🐛 Bug]: how to set service field?

### ISSUE THREAD

**Issue by mobile1021** [SeleniumHQ/seleniumhq.github.io#1319]
### What happened?

Which of the two is correct?
webdriver package guide hasn't `executable_path` field.
https://github.com/SergeyPirogov/webdriver_manager#use-with-chrome

but, selenium documentation has `executable_path` field.
![image](https://user-images.githubusercontent.com/90590106/221510551-785898a7-4c03-41d1-8038-5304a37df2d1.png)

### What browsers and operating systems are you seeing the problem on?

Linux/Ubuntu 22.04, headless webdriver

**Comment by diemol** [comment]
From what I see, the two pieces of code are equivalent. `webdriver_manager` is showing it in one line, whereas the Selenium docs shows it in two lines.

**Comment by mobile1021** [comment]
![image](https://user-images.githubusercontent.com/90590106/221530887-270d43b5-bc07-445a-80cc-6b7dcb932e8a.png)
Has the syntax argument changed?
default is `options.add_argument('--headless')`
`options.add_argument('--headless')` and `options.add_argument('--headless=new')`
Does this have the same meaning?

**Comment by diemol** [comment]
https://www.selenium.dev/blog/2023/headless-is-going-away/

**Comment by mobile1021** [comment]
![image](https://user-images.githubusercontent.com/90590106/221535215-a695d09b-7201-42d4-bff7-36d52d6776e7.png)
![image](https://user-images.githubusercontent.com/90590106/221535317-5b0984a2-1b36-42cd-8278-db1cbe79d9e7.png)
thanks,
Let me ask you one more question.
Why is this errors coming out?
