### ISSUE TITLE
[🐛 Bug]: Python sample code issues

### ISSUE THREAD

**Issue by jeffefefef** [SeleniumHQ/seleniumhq.github.io#1329]
### What happened?

The majority of the functions used in the python sample code are incorrect.

for example, in https://www.selenium.dev/documentation/webdriver/elements/finders/ the webdriver.find_element() function takes two strings as is strategy and locator, but the sample code is:

plants = driver.find_elements(By.TAG_NAME, "li")

when it should be:

plants = driver.find_elements("tag name", "li")

this is an issue for large amounts of the sample code.

### What browsers and operating systems are you seeing the problem on?

Firefox, Windows 10

**Comment by titusfortner** [comment]
The `By` class outputs a String and it's the preferred way to use the `find_element()` method.

It is even in the source code:
https://github.com/SeleniumHQ/selenium/blob/selenium-4.8.0/py/selenium/webdriver/remote/webelement.py#L405-L414

**Comment by jeffefefef** [comment]
Sorry for raising the issue then, it was my mistake, I hadn't imported the By class.
