### ISSUE TITLE
[🐛 Bug]: Slack invite broken on website footer

### ISSUE THREAD

**Issue by jbampton** [SeleniumHQ/seleniumhq.github.io#1334]
### What happened?

Slack invite link is broken in the website footer

### What browsers and operating systems are you seeing the problem on?

Brave on Mac

**Comment by harsha509** [comment]
Hi @jbampton,

Thank you for raising the issue. Fixed with commit https://github.com/SeleniumHQ/seleniumhq.github.io/commit/5024e53bfee9a396ec6e412a77524fa268b06cff !

Thanks,
Sri Harsha
