### ISSUE TITLE
[🚀 Feature]: Run nightly test builds in this repo, and add tests for selenium-manager's browser name and browser path args

### ISSUE THREAD

**Issue by snackattas** [SeleniumHQ/seleniumhq.github.io#1347]
### Feature and motivation

This feature request comes from the mind of @diemol in our Fix a bug, become a committer workshop in Chicago!

there are nightly-built selenium bindings. We should:
* Run this repo's tests using those nightly packages
* Add tests for each language to test the selenium-manager a bit more

**Comment by diemol** [comment]
This is working now, each language releases a nightly package, and it gets tested with the examples that live in this repository.
