### ISSUE TITLE
[🐛 Bug]: Selenium Grid 4.8.1 is responding slow

### ISSUE THREAD

**Issue by ayushi-nyk** [SeleniumHQ/seleniumhq.github.io#1348]
### What happened?

Earlier we used to use grid v.3.141.59 on which our 700 test cases were running with 22 parallel nodes and it used to take around 60 to 90 mins .. But now same suit is taking more than 4 hours on grid version 4.8.1 .
We have observed that some test gets stuck on grid for around 1 hour or more ..

What is the reason of slowness .

### What browsers and operating systems are you seeing the problem on?

Chrome with version v.110.0.5481.100

**Comment by diemol** [comment]
This is the repository for the documentation. If you are having an issue, please report it to https://github.com/SeleniumHQ/selenium with a way to reproduce it.
