### ISSUE TITLE
[🐛 Bug]: Documentation for Remote WebDriver is at odds with deprecation warning.

### ISSUE THREAD

**Issue by v-kumar** [SeleniumHQ/seleniumhq.github.io#1366]
### What happened?

Using ruby, for remote driver,  the following example gives deprecation warning.

URL: https://www.selenium.dev/documentation/webdriver/drivers/remote_webdriver/

![image](https://user-images.githubusercontent.com/122798/234408693-447891c2-7e56-43c4-8724-8cca39591146.png)

![image](https://user-images.githubusercontent.com/122798/234408817-acd1cb8c-13ea-43d0-8a30-0054cd4b674b.png)

However, it is not clear how to use Options only instead.

### What browsers and operating systems are you seeing the problem on?

ruby selenium web-driver, v 4.8.x

**Comment by titusfortner** [comment]
Yes, that code example is very much out of date. 

As to the deprecation warning, instead of working with:
```
options = Remote::WebDriver::Capabilities.chrome
```
work with:
```
options = Options.chrome
```

The object has attribute accessors for each of the things you can change (`#browser_version=` & `#platform_name=`), so it should be more straightforward

**Comment by v-kumar** [comment]
It's not still clear how to configure the remote browser based on the above information. Is just passing browser: :remote, good enough?

```ruby
  Capybara::Selenium::Driver.new app, browser: :remote, options: options,
```

**Comment by titusfortner** [comment]
I'm not a capybara expert, but this is the example code I have that works: https://github.com/saucelabs-training/demo-ruby/blob/main/selenium-examples/capybara-rspec/spec/spec_helper.rb#L16-L41

**Comment by ghost** [comment]
Ah yes chromus depricatus

**Comment by shbenzer** [comment]
@harsha509 I think this issue can probably be closed. The Browser Options section, and the referenced example, is no longer present in the [Remote Webdriver Page](https://www.selenium.dev/documentation/webdriver/drivers/remote_webdriver/)

**Comment by harsha509** [comment]
Documentation for using the Options class is now available, along with updated code examples: [Chrome Options](https://www.selenium.dev/documentation/webdriver/browsers/chrome/).

Closing as resolved!
