### ISSUE TITLE
[🚀 Feature]: The first script should not use any unit test library. or assertion. 

### ISSUE THREAD

**Issue by rpallavisharma** [SeleniumHQ/seleniumhq.github.io#1369]
### Feature and motivation

The first script uses unit test library and assertion in the code example. This should be reconsidered. Someone who is new to Selenium, not for the purpose of testing, or even for the purpose of automation, may not understand the code.

**Comment by diemol** [comment]
I think it makes sense to have the first script with a test runner and assertion library because most of the people who come to Selenium, want to test.

However, the very first script that welcomes users to the docs is pure Selenium, https://www.selenium.dev/documentation/. So I wonder if that is a good compromise.

**Comment by rpallavisharma** [comment]
There is a section beneath it which says test runner. Is it a good idea to have these scripts there? And this section which compiles all right steps without any unit test / assertion.

**Comment by titusfortner** [comment]
That was my intent. To have the first example be executable without a test runner. Then to have a section for how to use it in a larger context.

**Comment by rpallavisharma** [comment]
i think that would be helpful and maybe the right way to do it.

**Comment by asolntsev** [comment]
@pallavigitwork Maybe you cold just submit a pull request with your vision how this documentation should look like?

@titusfortner I think we can close the issue (until we get a pull request).

**Comment by titusfortner** [comment]
Yes, let's track the underlying concern on the other issue

**Comment by rpallavisharma** [comment]
The issue 1367 and 1369 are not duplicate of each other. One was for the introduction part of the selenium page which i found more test oriented, a lot of content has changed since then. the other issue talks about the code example, provided in getting started in Selenium. Since the documentation content is undergoing change, and I believe Corina is looking into it. This appears better to me - https://www.selenium.dev/documentation/webdriver/. At the same time there are many hyperlinks which asks users to go to different pages. It appears a busy page. Thats what I feel. Simplifying it, and segregating Selenium from its usage in web test automation I think could be done, and and we can also add information about selenium webdriver ecosystem, as a section.

**Comment by titusfortner** [comment]
We have the code, it's just a matter of where it gets used, which I think is the point of the other one. I do think that we should show how to execute selenium outside of a test runner, but the examples should get executed on our CI as part of a test runner, so it doesn't make sense to do more than just show that it can be done without it. 

Also, I agree it's busy. I think this is the piece Corina and Alicia areworking on.

**Comment by rpallavisharma** [comment]
Sure.
