### ISSUE TITLE
[🚀 Feature]: The example code in this page, should be changed to use selenium website

### ISSUE THREAD

**Issue by rpallavisharma** [SeleniumHQ/seleniumhq.github.io#1370]
### Feature and motivation

This page contains various method examples, and the web page used in them are all different 
https://www.selenium.dev/selenium/web/inputs.html
google
example.
Suggesting that all should link to- https://www.selenium.dev/selenium/web/inputs.html

**Comment by diemol** [comment]
Which page?

**Comment by rpallavisharma** [comment]
this page - https://www.selenium.dev/documentation/webdriver/elements/information/

**Comment by titusfortner** [comment]
Most of the code examples need to be rewritten and referenced from our example projects in github.

**Comment by harsha509** [comment]
looks like the code samples are now updated in this pagehttps://www.selenium.dev/documentation/webdriver/elements/information/

but as Titus mentioned, will modify code samples accordingly!
