### ISSUE TITLE
[🚀 Feature]: Streamline documentation for multiple language with Weblate or similar service

### ISSUE THREAD

**Issue by sulaimangari** [SeleniumHQ/seleniumhq.github.io#1374]
### Feature and motivation

With project as big as Selenium it somehow lack official documentation for multiple language. It will be more easy for locals to contribute on documentation if there is crowd contribute pipeline like Weblate so anyone can easily contribute in the project documentation. Cheers.

**Comment by titusfortner** [comment]
We have documentation in English, japanese, Chinese and Portuguese and dedicated translators to manage the content. Everything is available to update on github.
We appreciate the suggestion, if we decide to change how we do translations at some point, we'll keep this solution in mind.

**Comment by diemol** [comment]
Closing as Titus replied already.
