### ISSUE TITLE
Encoding Issue

### ISSUE THREAD

**Issue by alerem18** [SeleniumHQ/seleniumhq.github.io#1377]
### What happened?

i've downloaded selenium-server-4.9.0.jar and run it on windows server 2019 using java -jar selenium-server-4.9.0.jar standalone

then tried this code:
```python
import requests
import json



url = "http://localhost:4444/wd/hub/session"

headers = {'Content-Type': 'application/json'}
payload = {
    "capabilities": {
        "firstMatch": [
            {
                "browserName": "chrome",
                "goog:chromeOptions": {
                    "args": ["--disable-extensions"]
                }
            }
        ]
    }
}

response = requests.post(url, headers=headers, data=json.dumps(payload))
print(response.text)
```

i get this error {
  "value": {
    "error": "unknown error",
    "message": "Content-Type header does not indicate utf-8 encoded json: application\u002fjson",
    "stacktrace": ""
  }
}

but when i try
headers = {'Content-Type': 'application/json; charset=utf-8'}
it works without issue

while i use docker run -d -p 4444:4444 --name selenium selenium/standalone-chrome
it works without issue no matter if i use charset in headers or not, or even use ascii encoding in headers it works fine, but in my windows 2019 server, it only accepts utf-8 encoding and it must be used in headers
this is while i use the same system to send post request to both docker image and selenium server on my system

how can i run the selenium server that accepts multiple types of encodings? like the server on the docker image

### What browsers and operating systems are you seeing the problem on?

windows server 2019
google chrome Version 112.0.5615.138
selenium-server-4.9.0
ChromeDriver 112.0.5615.49

**Comment by diemol** [comment]
That header is needed for security reasons. However, you can deactivate that check through the flag shown in the[ documentation](https://www.selenium.dev/documentation/grid/configuration/cli_options/#network). 

This is deactivated in the [Docker images](https://github.com/SeleniumHQ/docker-selenium/blob/trunk/Hub/Dockerfile#L22) for backwards compatibility.
