### ISSUE TITLE
[🐛 Bug]:  'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by biaobro** [SeleniumHQ/seleniumhq.github.io#1381]
### What happened?

 when I run code "ChromeDriverManager().install()" , it give me an error and stops : 'str' object has no attribute 'decode'
 
 Then I debug the code, finally I got the root case in library file line 263 and line 279: "C:\Program Files\Python310\Lib\site-packages\webdriver_manager\core\utils.py", 
 
 there are some code to check the version of chrome browser, but the result type of stream.communicate()[0] is Python String, like "113.0.5672.93\n", it can't be decoded directly. 
 
 so the error happens. I modified the src code to "stdout = stream.communicate()[0].**encode()**.decode()", then it works fine.

 however, I think the error is caused by newer version of browser, cause the code run successfully several months ago. 
 
 would you please check it? thanks
 

### My Test Code

```
def test_driver_manager_chrome():
    service = ChromeService(executable_path=ChromeDriverManager().install())
    driver = webdriver.Chrome(service=service)

    driver.get("https://www.baidu.com")
    time.sleep(10)
    driver.quit()
```

### The Src Code
```
def read_version_from_cmd(cmd, pattern):
    with subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            stdin=subprocess.DEVNULL,
            shell=True,
    ) as stream:
        stdout = stream.communicate()[0].encode().decode()
        version = re.search(pattern, stdout)
        version = version.group(0) if version else None
    return version


def determine_powershell():
    """Returns "True" if runs in Powershell and "False" if another console."""
    cmd = "(dir 2>&1 *`|echo CMD);&<# rem #>echo powershell"
    with subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            stdin=subprocess.DEVNULL,
            shell=True,
    ) as stream:
        stdout = stream.communicate()[0].encode().decode()
    return "" if stdout == "powershell" else "powershell"
```

**Comment by biaobro** [comment]
Brower : Google Chrome 113.0.5672.93
OS: window 10

**Comment by titusfortner** [comment]
We're probably going to pull the driver manager code examples soon. The latest version of Selenium will automatically manage drivers for you just as well as the driver managers, so that's what we plan to support going forward.

**Comment by biaobro** [comment]
> We're probably going to pull the driver manager code examples soon. The latest version of Selenium will automatically manage drivers for you just as well as the driver managers, so that's what we plan to support going forward.

got it. thanks

**Comment by diemol** [comment]
So please remove WebDriver Manager and let Selenium handle the browser driver.
