### ISSUE TITLE
[🐛 Bug]: Explicit wait example of Java has coding error

### ISSUE THREAD

**Issue by ClaireTop** [SeleniumHQ/seleniumhq.github.io#1391]
### What happened?

Code link: https://www.selenium.dev/documentation/webdriver/waits/
Under Explicit wait title, the example of Java:
`WebDriver driver = new ChromeDriver();
driver.get("https://google.com/ncr");
driver.findElement(By.name("q")).sendKeys("cheese" + Keys.ENTER);
// Initialize and wait till element(link) became clickable - timeout in 10 seconds
WebElement firstResult = new WebDriverWait(driver, Duration.ofSeconds(10))
        .until(ExpectedConditions.elementToBeClickable(By.xpath("//a/h3")));
// Print the first result
System.out.println(firstResult.getText());
  `
Issue description:
WebDriverWait() second required parameter type is Long. But the type of 'Duration.ofSeconds(10)' is not Long.

### What browsers and operating systems are you seeing the problem on?

Chrome, MacPro

**Comment by diemol** [comment]
You are probably using an old version of Selenium. The code examples are made for Selenium 4.

**Comment by harsha509** [comment]
Hi @ClaireTop,

also adding ref to api docs https://www.selenium.dev/selenium/docs/api/java/org/openqa/selenium/support/ui/WebDriverWait.html the second argument is a `java.time.Duration timeout`!

**Comment by asolntsev** [comment]
I think we should close the issue.
Page https://www.selenium.dev/documentation/webdriver/waits/ describes API of Selenium 4 where parameter type is `Duration`. That page is correct.

![image](https://github.com/SeleniumHQ/seleniumhq.github.io/assets/279773/10888f39-46fc-4bbf-bd18-c0f1a9aa071f)
