### ISSUE TITLE
Program.Browser.Quit() - freeze application 

### ISSUE THREAD

**Issue by roversochi** [SeleniumHQ/seleniumhq.github.io#140]
I installed webdriver version 4 into my visualStudio today.
I launched the application as usual. It does this:

.................
             Program.Browser = new ChromeDriver (options);
             Program.Browser.Manage(). Timeouts(). ImplicitWait = TimeSpan.FromMilliseconds(500); // timeout for searching for items
             Program.Browser.Manage(). Window.Maximize();
.................

Then I do Program.Browser.Quit();
The browser window closes.
But chromedrover.exe does not close. And my application freezes. Only the Stop button in the IDE helps.

In the previous version of webdriver, everything worked fine.

**Comment by corevo** [comment]
[This](https://github.com/SeleniumHQ/selenium) is the correct place for code related issues.

**Comment by corevo** [comment]
This repo is for the website, not WebDriver.

**Comment by roversochi** [comment]
sorry, thank you
