### ISSUE TITLE
[🚀 Feature]: Add details for the new HTTP Client

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/seleniumhq.github.io#1421]
### Feature and motivation

It won't apply after September, but we should have a place to point to this info in our docs and not in the blog:
https://www.selenium.dev/blog/2022/using-java11-httpclient/

We mention some of this for the grid - https://www.selenium.dev/documentation/grid/getting_started/#using-the-java-11-http-client but it doesn't cover what is needed for the client.

I guess it needs to go in the HTTP Client documentation page that doesn't even exist right now. ☹️

**Comment by asolntsev** [comment]
@titusfortner It's already September. May we just close the issue? :)

**Comment by titusfortner** [comment]
Booo.
