### ISSUE TITLE
[🐛 Bug]:Selenium Grid 4 Components image does`t show at the page

### ISSUE THREAD

**Issue by sMichellin** [SeleniumHQ/seleniumhq.github.io#1422]
### What happened?

Open the page https://www.selenium.dev/documentation/grid/components/

<img width="938" alt="Снимок экрана 2023-07-04 в 17 33 12" src="https://github.com/SeleniumHQ/seleniumhq.github.io/assets/48342790/32d3ae26-49ff-4f82-bb38-bb711bf2df62">

There is no any picture and architecture schema on the page

### What browsers and operating systems are you seeing the problem on?

MAC OS Sierra
Chrome 114.0.5735.198 64-bit

**Comment by harsha509** [comment]
Hi @sMichellin ,

Thank you for reporting the issue!

Fixed with commit https://github.com/SeleniumHQ/seleniumhq.github.io/commit/d585f1874314ae8cc9096643ce6fa25eb5eb3b06

The image is visible now!

Thanks,
Sri
