### ISSUE TITLE
[🐛 Bug]: Cannot inspect network, error: "System.InvalidOperationException: 'A command response was not received: Fetch.getResponseBody'"

### ISSUE THREAD

**Issue by shemeshx** [SeleniumHQ/seleniumhq.github.io#1424]
### What happened?

`public static async Task DevToolsTest2(string[] args)
        {

            string urlGridHub = "http://huburl:4444";

            ChromeOptions CHOptions = new ChromeOptions();

            IWebDriver driver = new RemoteWebDriver(new Uri(urlGridHub + "/wd/hub"), CHOptions.ToCapabilities(), TimeSpan.FromSeconds(30));
            INetwork interceptor = driver.Manage().Network;

            try
            {
                interceptor.NetworkResponseReceived += OnNetworkResponseReceived;

                interceptor.StartMonitoring().Wait();
                driver.Navigate().GoToUrl("https://my-app.com/");

                Thread.Sleep(5000);

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
            finally
            {
                interceptor.StopMonitoring().Wait();

                driver.Close();
                driver.Quit();
            }
        }

        private static void OnNetworkResponseReceived(object sender, NetworkResponseReceivedEventArgs e)
        {
            try
            {
                if (!e.ResponseUrl.Contains("leuvmtstsrvbe")) return;
                StringBuilder builder = new StringBuilder();
                builder.AppendFormat("Response {0}", e.RequestId).AppendLine();
                builder.AppendLine("--------------------------------");
                builder.AppendFormat("{0} {1}", e.ResponseStatusCode, e.ResponseUrl).AppendLine();

                foreach (KeyValuePair<string, string> header in e.ResponseHeaders)
                {
                    builder.AppendFormat("{0}: {1}", header.Key, header.Value).AppendLine();
                }

                if (e.ResponseResourceType == "XHR")
                    builder.AppendLine(e.ResponseBody);

                builder.AppendFormat("Content type: {0}", e.ResponseResourceType).AppendLine();

                builder.AppendLine("--------------------------------");
                Console.WriteLine(builder.ToString());
            }
            catch
            {
                return;
            }
        }`

I try to run the following code and i got this error all the time :"System.InvalidOperationException: 'A command response was not received: Fetch.getResponseBody'".

how can i deal with it?

thanks!

### What browsers and operating systems are you seeing the problem on?

the hub is on linux (centos) with selenium 4 Grid latest version and browser is the latest chrome browser.

**Comment by sopansagorkar** [comment]
thanks for highlighting this issue, I was also facing the same ❤️

**Comment by shemeshx** [comment]
it closed my incident. I don't know why :\ @sopansagorkar

**Comment by diemol** [comment]
Because this is the repository for documentation. Have you tried to use the links to ask your question?
