### ISSUE TITLE
[🐛 Bug]: 7. Request element information- KOTLIN CODE WRONG-

### ISSUE THREAD

**Issue by nevinaydin** [SeleniumHQ/seleniumhq.github.io#1427]
### What happened?

Reproduceable Steps:
1.Navigate to "https://www.selenium.dev/documentation/webdriver/getting_started/first_script/",
2. Scroll down until you see "7. Request element information"
3. Click to Kotlin code,
4. The code needs to be something like this "val value: String = message.getText()" instead showing "       driver.get("https://www.selenium.dev/selenium/web/web-form.html")"
Expected Result: val value = message.getText()
Actual Result: driver.get("https://www.selenium.dev/selenium/web/web-form.html")
Browser : Chrome Version 114.0.5735.134 (Official Build) (64-bit)
Severity: Medium

Evidence:
![image](https://github.com/SeleniumHQ/selenium/assets/97362299/78354ab1-acd2-49ce-9858-d2d79c030a43)

### How can we reproduce the issue?

```shell
It is given above.
```

### Relevant log output

```shell
As this is a manual exploratory testing, there is no code snippet.
```

### Operating System

Windows 10

### Selenium version

Java 11

### What are the browser(s) and version(s) where you see this issue?

Chrome Version 114.0.5735.134 (Official Build) (64-bit)

### What are the browser driver(s) and version(s) where you see this issue?

Chrome

### Are you using Selenium Grid?

Nope

**Comment by titusfortner** [comment]
We dynamically reference code in other files and sometimes it gets out of sync.
That display is set here: https://github.com/SeleniumHQ/seleniumhq.github.io/blob/trunk/website_and_docs/content/documentation/webdriver/getting_started/first_script.en.md?plain=1#L199

and is referencing the code here: https://github.com/SeleniumHQ/seleniumhq.github.io/blob/trunk/examples/kotlin/src/test/kotlin/dev/selenium/getting_started/FirstScriptTest.kt

Looks like it needs to reference line 32 and not 18? Would you like to make a PR to fix it?
It needs to be updated in all 4 translations of first_script - https://github.com/SeleniumHQ/seleniumhq.github.io/tree/trunk/website_and_docs/content/documentation/webdriver/getting_started

**Comment by nevinaydin** [comment]
Thanks a lot for the update. I'd love to do the PR and did it already. Yhis
was a pleasure to be helpful for a open source project.
Best,
Nevin

**Comment by diemol** [comment]
Thank you for your PRs, merged and fixed.
