### ISSUE TITLE
[🚀 Feature]: Using Driver Manager

### ISSUE THREAD

**Issue by Vince155** [SeleniumHQ/seleniumhq.github.io#1434]
### Feature and motivation

I was reading through the [Selenium Manager](https://www.selenium.dev/documentation/selenium_manager/) docs and noticed that provided version 4.6 or above is utilized then the manager will automatically be used. I was wondering if this is something that users can opt into even though they may not meet the conditions.

For example, in the driver class, maybe users can have something like 
```
ChromeDriverService service = new ChromeDriverService.Builder()
                .useDriverManager()
                .build();

        driver = new ChromeDriver(service);
```

Another option maybe is allowing the user to write a line to opt out like `.useDefaultDriverManager(false)`.

What I'm getting at is having the choice to use or not use the manager be more explicit and in the application level.

**Comment by diemol** [comment]
If you set the driver on the driver service or the path, then it won't be used. That's the opt in / opt out switch.
