### ISSUE TITLE
[🐛 Bug]: Python "first script" doesn't work

### ISSUE THREAD

**Issue by mbasaglia** [SeleniumHQ/seleniumhq.github.io#1438]
### What happened?

I'm trying to follow the documentation from here: https://www.selenium.dev/documentation/webdriver/getting_started/first_script/

but the first step already fails. when I call `driver = webdriver.Chrome()` the browser is started but it hangs the python script until I close the browser window.

Looking around for solutions every time I solve one issue I encounter another so it would really help having a basic example that works properly

### What browsers and operating systems are you seeing the problem on?

Browser: Chromium Version 114.0.5735.198 (Official Build) snap (64-bit)
Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.15.0-76-generic (64-bit)
Graphics Platform: X11
Processors: 8 × AMD FX(tm)-8320 Eight-Core Processor
Memory: 31.4 GiB of RAM
Graphics Processor: AMD Radeon RX 470 Graphics

**Comment by titusfortner** [comment]
You can turn on logging to see what is happening, but I'm guessing it is downloading the driver and taking longer than you expect to do so.
https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/

That is the correct line of code, so I'm closing this issue, but feel free to reach out to us at https://www.selenium.dev/support/#ChatRoom
