### ISSUE TITLE
[🐛 Bug]: Chrome verion 115 cannot manually import Driver files using Service nor install them using WebDriverManager

### ISSUE THREAD

**Issue by RedCrazyGhost** [SeleniumHQ/seleniumhq.github.io#1449]
### What happened?

At first, I was going to use the code I had written before, but it was deprecated
```python
from selenium import webdriver

driver = webdriver.Chrome(executable_path='/Users/xxx/Code/Python/WebDriver/chromedriver')
driver.get("https://www.google.com")
```

I tried to use a brand new approach, but there was no new driver
```python
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
driver.get("https://www.google.com")
```

I downloaded a new driver for version 115 from chrome but couldn't import it manually
```python
from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromeService

service=ChromeService(executable_path="/Users/xxx/Code/Python/WebDriver/chromedriver")
driver = webdriver.Chrome(service=service)
driver.get("https://www.google.com")
```
I saw that there was talk about it, but nothing worked for me. 

Not being able to use driver files manually makes me feel bad, probably for security reasons.

This issue is hereby opened, and the above content is generated by the translation software.

### What browsers and operating systems are you seeing the problem on?

Chrome verion 115 
selenium version  4.8.0
Mac OS(x64)  13.4.1 (c)

**Comment by RedCrazyGhost** [comment]
Sorry, I found I sent it to the wrong location

**Comment by titusfortner** [comment]
For what it's worth, Chromedriver manager is a 3rd party library and should not be necessary if you upgrade to 4.11
