### ISSUE TITLE
[🐛 Bug]: BiDi Network Interceptors in DotNet halts API Responses

### ISSUE THREAD

**Issue by YumeSa** [SeleniumHQ/seleniumhq.github.io#1468]
### What happened?

Testing on Website: [https://reqres.in/api/users](url) 

**Intercepting Response:**
       
        [Test]
        public void InterceptNetworkResponse_Reqres_POST_RestAPI() {
            var handler = new NetworkResponseHandler();
            handler.ResponseMatcher = httpresponse => httpresponse.Url == "https://reqres.in/api/users";
            handler.ResponseTransformer = http => {
                http.StatusCode = 200;
                http.Body = "Creamy, delicious cheese!";
                return http;
            };

            INetwork networkInterceptor = driver.Manage().Network;
            networkInterceptor.AddResponseHandler(handler);
            networkInterceptor.StartMonitoring().Wait();
            driver.Navigate().GoToUrl("https://reqres.in");
            By element = By.XPath("//li[@data-id='post']");
            driver.FindElement(element).Click();
            networkInterceptor.StopMonitoring().Wait();
        }

API Request Raw: 
POST https://reqres.in/api/users HTTP/1.1
Host: reqres.in
Connection: keep-alive
Content-Length: 34
Pragma: no-cache
Cache-Control: no-cache
sec-ch-ua: "Chromium";v="116", "Not)A;Brand";v="24", "Google Chrome";v="116"
sec-ch-ua-platform: "Windows"
sec-ch-ua-mobile: ?0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Content-Type: application/json
Accept: */*
Origin: https://reqres.in
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: https://reqres.in/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cookie: _gid=GA1.2.1500735321.1694073113; _gat=1; _gat_gtag_UA_174008107_1=1; _ga_CESXN06JTW=GS1.1.1694073112.1.0.1694073112.0.0.0; _ga=GA1.1.193387887.1694073113; _ga_WSM10MMEKC=GS1.2.1694073113.1.0.1694073113.0.0.0; __stripe_mid=431ad665-b677-4b41-8beb-1de940d13505e216df; __stripe_sid=29d58de6-bea7-4ae7-89e6-f4a55d4d5796c5b630

{"name":"morpheus","job":"leader"}

API Raw Response: 

 HTTP/1.1 201 Created
Date: Thu, 07 Sep 2023 07:52:40 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 84
Connection: keep-alive
X-Powered-By: Express
Access-Control-Allow-Origin: *
Etag: W/"54-RzmLbiM8TZLHPET8QmC3TeZxIjA"
Via: 1.1 vegur
CF-Cache-Status: DYNAMIC
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=lbnYVk2XCfyq3OT9ZvAx%2Bt2bYsh4juJb6TzeGXbrStMzkgi20Qo9QRnZY2O7Hbb%2BXOmrdaEu9d%2fHJ6IHhy9VNXrwk2q7sXiSwpApXWkVtNzQ4D%2B1D8718B1hkbJm4kYk8rlnypSt2Q%3D%3D"}],"group":"cf-nel","max_age":604800}
NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
Server: cloudflare
CF-RAY: 802d5fa13dda49fc-SIN

{"name":"morpheus","job":"leader","id":"837","createdAt":"2023-09-07T07:52:40.180Z"}

**Observations:**
While Intercepting the POST response request for the above URI the request halts. Further testing the above issue found that for all API Request without adding the handler also recreates the above issue when the monitoring starts.

### What browsers and operating systems are you seeing the problem on?

Chrome Browser: Version 116.0.5845.180 (Official Build) (64-bit)
Selenium.Support : Version="4.12.4"
Selenium.WebDriver : Version="4.12.4"

![image](https://github.com/SeleniumHQ/seleniumhq.github.io/assets/83526180/2802a6c1-277a-4da1-b9de-17a9875133f4)

**Comment by diemol** [comment]
Please create this issue at https://github.com/SeleniumHQ/selenium
