### ISSUE TITLE
[🚀 Feature]: Add instructions for Ruby in the 'Test Runners' section

### ISSUE THREAD

**Issue by flynnbops** [SeleniumHQ/seleniumhq.github.io#1476]
### Feature and motivation

There are currently no instructions in the [Test Runners](https://www.selenium.dev/documentation/webdriver/getting_started/first_script/#test-runners) section for Ruby. 

I'll raise an MR to fix in https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1477

Similar to other issues in this area.
- https://github.com/SeleniumHQ/seleniumhq.github.io/issues/1457
- https://github.com/SeleniumHQ/seleniumhq.github.io/issues/1474

**Comment by titusfortner** [comment]
I'm hoping to move the test runner section to a different page with #1479

**Comment by flynnbops** [comment]
Sounds good. I'll check it out.

Closing this issue.

**Comment by titusfortner** [comment]
Well, this issue is still valid, I just added a better place to put it (I think).
