### ISSUE TITLE
[🐛 Bug]: Alignment and overflowing elements on the webpage

### ISSUE THREAD

**Issue by SparshKesari** [SeleniumHQ/seleniumhq.github.io#1482]
### What happened?

Encountered some responsiveness issues on the Selenium website. Specifically, certain elements on the website are not aligned properly with the size of the screen viewport, bleeding outside of the viewport, setting a general width for the page that's wider than the viewport, leading to horizontal scrolling. 

Page Url: https://www.selenium.dev/

## Expected Behavior:
All elements should adjust and align properly according to the size of the screen viewport, ensuring a responsive design without the need for horizontal scrolling.

## Screenshots:
<img width="1026" alt="image" src="https://github.com/SeleniumHQ/seleniumhq.github.io/assets/39815871/e15105c5-ed6e-4292-b4d8-8d4586ead522">

<img width="1028" alt="image" src="https://github.com/SeleniumHQ/seleniumhq.github.io/assets/39815871/614ca654-7ef4-421e-9905-96c0e014aed5">

### What browsers and operating systems are you seeing the problem on?

All browsers and OS

**Comment by SparshKesari** [comment]
Hey @diemol, Can you please assign the issue to me?

**Comment by diemol** [comment]
@SparshKesari, we usually do not do that as that hinders others who want to contribute. Your comment is enough to tell others you want to work on it. 

Thank you for raising the issue.

**Comment by SparshKesari** [comment]
sure, thanks @diemol
