### ISSUE TITLE
[🐛 Bug]: Responsiveness on smaller viewport devices

### ISSUE THREAD

**Issue by SparshKesari** [SeleniumHQ/seleniumhq.github.io#1484]
### What happened?

Responsiveness challenges when interfacing on devices with smaller viewports.

Screenshot:
<img width="278" alt="image" src="https://github.com/SeleniumHQ/seleniumhq.github.io/assets/39815871/daea756c-788b-436b-afcf-a30d3d8fa765">

### What browsers and operating systems are you seeing the problem on?

Mobile Devices / Smaller Viewport Devices

**Comment by harsha509** [comment]
Hi @SparshKesari ,

Thank you for raising the issue.

This is fixed with PR https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1534

Thanks,
Sri
