### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by kreamyu** [SeleniumHQ/seleniumhq.github.io#1501]
### What happened?

In the [File Upload page of the document,](https://www.selenium.dev/documentation/webdriver/elements/file_upload/) the third line of Python code should not have a `;`.
![image](https://github.com/SeleniumHQ/seleniumhq.github.io/assets/52658711/dde4151b-b461-4512-afdf-0aa18c61b239)

### What browsers and operating systems are you seeing the problem on?

Chrome 116, Ubuntu 22.04.

**Comment by harsha509** [comment]
Hi @kreamyu ,

Thank you for raising the issue. I have fixed it with a new commit https://github.com/SeleniumHQ/seleniumhq.github.io/commit/4e2ee4d23d79d4d0c6ec948122a05da1caeafcde.

Changes will be reflected after some time!

Thanks,
Sri

**Comment by kreamyu** [comment]
Thank you!
