### ISSUE TITLE
Blank subsection documentation

### ISSUE THREAD

**Issue by Jax05** [SeleniumHQ/seleniumhq.github.io#151]
## 🐛 Bug Report

The following documentation subsections have no written content:

* HTTP Proxies
* Page loading strategy
* Working with web elements

## To Reproduce

[https://selenium.dev/documentation/en/webdriver/http_proxies/](url)
[https://selenium.dev/documentation/en/webdriver/page_loading_strategy/](url)
[https://selenium.dev/documentation/en/support_packages/working_with_web_elements/](url)

This is what each page looks like.

![image](https://user-images.githubusercontent.com/15638299/71380721-f3459580-2595-11ea-9b55-cb8e5492893b.png)

## Environment

OS: Windows
Browser: Chrome

**Comment by manoj9788** [comment]
@Jax05 Thanks for raising this issue, most of our documentation are in WIP(Work In Progress) mode. So those are expected, please feel free to write content and raise a PR - would be happy to look at it!

**Comment by Jax05** [comment]
@manoj9788 that explains it! Thanks for your reply.

**Comment by diemol** [comment]
Page loading strategy has content and Working with web elements has been removed due to a duplication of content, thanks to @Harsha509 for tacking this!

**Comment by Harsha509** [comment]
hi @diemol ,

Can we close this, currently we have some info in each document mentioned above.

Regards,
Harsha

**Comment by diemol** [comment]
Thank you @Harsha509!
