### ISSUE TITLE
[🚀 Feature]: Dark theme for the selenium website

### ISSUE THREAD

**Issue by abhishek4nz** [SeleniumHQ/seleniumhq.github.io#1518]
### Feature and motivation

The pure white theme is outdated and difficult to read.

can you please give an option of a dark theme where the background would be black?

It would be of great help.

Thanks!

**Comment by luisfcorreia** [comment]
Hi, thanks for the request.
We don't have anyone working on that but contributions are welcome

**Comment by titusfortner** [comment]
This would need to be implemented by docsy.
See https://github.com/google/docsy/issues/331
