### ISSUE TITLE
[🐛 Bug]: Potential Issue with "Working with select list elements" documentation

### ISSUE THREAD

**Issue by HarryEastell** [SeleniumHQ/seleniumhq.github.io#1527]
### What happened?

Hello, I was using selenium to test my C# project when I needed to interact with a "select/option". I checked the documentation and several articles online and all said to use the "SelectElement" object like in the example below:

```
 var selectElement = driver.FindElement(By.Name("selectomatic"));
 var select = new SelectElement(selectElement);
```
I tried this however it couldn't find the namespace to use it. I checked Selenium was being referenced properly and made sure it had the right usings at the top and still nothing. Eventually I tried just finding the option I wanted to select and sent the ".Click" interaction which worked. Is the documentation correct or is there something I have missed?

The code which I got to work in the end is below.

```
IWebElement cars = driver.FindElement(By.Id("cars"));
WebDriverWait wait = new WebDriverWait(driver, TimeSpan.FromSeconds(120));
wait.Until(el => cars.Displayed);

IList<IWebElement> selectOptions = driver.FindElements(By.TagName("option"));
foreach (IWebElement selectOption in selectOptions)
{
    if (selectOption.Text == "Audi")
    {
        selectOption.Click();
    }
}
```
Thank You
Harry

### What browsers and operating systems are you seeing the problem on?

Chrome Version 119.0.6045.124 (Official Build) (64-bit)
Microsoft Windows 10 Enterprise 10.0.19044 Build 19044
Selenium.WebDriver 4.15.0

**Comment by titusfortner** [comment]
Good question.
For .NET you need to also require the Selenium Support package https://www.nuget.org/packages/Selenium.Support
