### ISSUE TITLE
[🚀 Feature]: mention the usage of By.xpath in findElement chain

### ISSUE THREAD

**Issue by benyue1978** [SeleniumHQ/seleniumhq.github.io#1539]
### Feature and motivation

Took me quite some time to figure out that I need to use relative path in the xpath expression to chain a By.xpath in the locator.
xpathExpression = ".//b" // this one works
xpathExpression = "//b" // it will find all elements from the root of DOM

It may worth mentioning in the doc 
https://www.selenium.dev/documentation/webdriver/elements/finders/#evaluating-a-subset-of-the-dom 
or 
https://www.selenium.dev/documentation/webdriver/elements/finders/#find-elements-from-element

**Comment by diemol** [comment]
Would you like to send a PR to improve that section of the documentation?

**Comment by shbenzer** [comment]
Covered by commit [61c311f](https://github.com/SeleniumHQ/seleniumhq.github.io/commit/61c311f1b98421ca880400998281df2752fdbfd2)

**Comment by harsha509** [comment]
Hi @benyue1978 ,

Thank you for raising the issue. Looks like changes has been landed with commit https://github.com/SeleniumHQ/seleniumhq.github.io/commit/61c311f1b98421ca880400998281df2752fdbfd2

Thank you @shbenzer for fixing it!

Closing as resolved!
