### ISSUE TITLE
[🚀 Feature]: How to reach API documentation from website?

### ISSUE THREAD

**Issue by raffaelemancuso** [SeleniumHQ/seleniumhq.github.io#1544]
### Feature and motivation

Hello,
the API documentation for Selenium seems to be [here](https://www.selenium.dev/selenium/docs/api/py/api.html).
Can you indicate me the path to reach that website from the [homepage](https://www.selenium.dev/)?
Because clicking on "Documentation" opens a small tutorial.
Best,

**Comment by titusfortner** [comment]
The links to the api docs for each language can be found here
https://www.selenium.dev/downloads/
