### ISSUE TITLE
[🚀 Feature]: Make the website font color black

### ISSUE THREAD

**Issue by matmatias** [SeleniumHQ/seleniumhq.github.io#1546]
### Feature and motivation

The documentation would be more pleasant to read if the font color were black.

Current:
![image](https://github.com/SeleniumHQ/seleniumhq.github.io/assets/38060185/97c91f9f-f5da-4a46-984c-9e8596545573)

Proposed:
![image](https://github.com/SeleniumHQ/seleniumhq.github.io/assets/38060185/0ef565b1-4617-44ac-a930-52138820384a)

**Comment by titusfortner** [comment]
@diemol why did we override this: https://github.com/SeleniumHQ/seleniumhq.github.io/blob/trunk/website_and_docs/assets/scss/_variables_project.scss#L12

Default is bs-gray-900 and we're closer to bs-gray-600

At the very least we should figure out how to make it darker when the background is bs-gray-300

**Comment by diemol** [comment]
> @diemol why did we override this: https://github.com/SeleniumHQ/seleniumhq.github.io/blob/trunk/website_and_docs/assets/scss/_variables_project.scss#L12
> 
> Default is bs-gray-900 and we're closer to bs-gray-600
> 
> At the very least we should figure out how to make it darker when the background is bs-gray-300

There is a style guide https://github.com/SeleniumHQ/www.seleniumhq.org/blob/master/src/main/resources/Selenium%20HQ%20website%20design%20stule%20guide%20v3.2.pdf

**Comment by titusfortner** [comment]
Ah, so it's Petre's fault

**Comment by titusfortner** [comment]
So, it's by design, and we literally paid someone a lot of money to tell us to do it this way.
¯\\_(ツ)_/¯
