### ISSUE TITLE
[🐛 Bug]: Unable to launch Chrome browser in Selenium 4.16.1 Java 17, Selenium Manager unable to find the Binary

### ISSUE THREAD

**Issue by anjalivaswani8614** [SeleniumHQ/seleniumhq.github.io#1551]
### What happened?

Here is the issue:
 I'm facing the issue where getting the error: org.openqa.selenium.WebDriverException: Unable to obtain Selenium Manager Binary at: C:\Users.cache\selenium\manager\0.4.16\selenium-manager.exe
Build info: version: '4.16.1', revision: '9b4c83354e'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.9'
Driver info: driver.version: unknown
at org.openqa.selenium.manager.SeleniumManager.getBinary(SeleniumManager.java:210)
at org.openqa.selenium.manager.SeleniumManager.getDriverPath(SeleniumManager.java:253)

Browser is not launching .
ChromeOptions chromeOptions = new ChromeOptions();
chromeOptions.setCapability("goog:chromeOptions", true);
chromeOptions.addArguments("--no-sandbox");
chromeOptions.addArguments("--remote-allow-origins=*");
chromeOptions.addArguments("--ignore-certificate-errors");
chromeOptions.addArguments("--proxy-server=http://",PROXY_URL_STRING);
chromeOptions.addArguments("--proxy=http://",PROXY_URL);
chromeOptions.addArguments("--start-maximized");

    ChromeOptions ChromeOpt = new ChromeOptions();
    // Pass the ChromeOpt option it takes as a type of Capability.
    String chromeDriverPath = String.valueOf(SeleniumManager.getInstance().getDriverPath(chromeOptions,false));
    System.out.println("chromeDriverPath--" + chromeDriverPath);

    return this.driver= new ChromeDriver(chromeOptions);

Many times selenium chrome driver exe is not getting downloaded without using WebDriver Manager. 

### What browsers and operating systems are you seeing the problem on?

Chrome 119, Windows OS:

**Comment by diemol** [comment]
This is an issue with 4.16.1 which has been fixed and will be released with 4.17.0 in January. 

For now, you can use the nightly version as a workaround: https://www.selenium.dev/downloads/#nightly
