### ISSUE TITLE
[🐛 Bug]: WebDriver' object has no attribute 'get_downloadable_files

### ISSUE THREAD

**Issue by Mrrobi** [SeleniumHQ/seleniumhq.github.io#1553]
### What happened?

I have been trying to use docker hosted selenium standalone chrome container to remotely execute my selenium commands, now the issue is I need to download a file., my remote container is able to download the file properly but the problem occurs when I was trying to download the remotely downloaded file into my local machine, te get_downloadable_files() function kept showing error of 

```'WebDriver' object has no attribute 'get_downloadable_files'```

![image](https://github.com/SeleniumHQ/seleniumhq.github.io/assets/28683261/e327118c-426e-4e7e-8a5b-8e8654b9e326)

### What browsers and operating systems are you seeing the problem on?

I was using the https://hub.docker.com/r/selenium/standalone-chrome
this image to host a remote server of the selenium

**Comment by luisfcorreia** [comment]
What code guide are you following?

**Comment by Mrrobi** [comment]
> What code guide are you following?

@luisfcorreia 

https://www.selenium.dev/documentation/webdriver/drivers/remote_webdriver/

I am following this documentation

**Comment by luisfcorreia** [comment]
can you share the whole code as a gist?

**Comment by Mrrobi** [comment]
> can you share the whole code as a gist?

https://gist.github.com/Mrrobi/2b5f9e22f15b662f40b3fe3b158b9558

here's the code 

CC @luisfcorreia

**Comment by titusfortner** [comment]
Try using `chrome_options.add_argument("--headless=new")`

**Comment by Mrrobi** [comment]
> Try using `chrome_options.add_argument("--headless=new")`

no luck :( same issue.
``'WebDriver' object has no attribute 'get_downloadable_files'``

**Comment by titusfortner** [comment]
The bottom line is that the example code here is executing and passing properly in our CI — https://github.com/SeleniumHQ/seleniumhq.github.io/actions/runs/7351869652/job/20015844161

Please double check the version of Selenium both in the grid and in the client are the latest.
Turn on logging https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/ and see if that gives you insight into what is happening.

If neither of the above tell you why you are having a problem go ahead and open up a new issue in our primary repo (this one is just for the website documentation, which is working as intended) and fill out all of the information requested by the template— https://github.com/SeleniumHQ/selenium/issues/new/choose

Thanks.
