### ISSUE TITLE
[🐛 Bug]: find_element does not work in /html/rabby-kit// section, cannot locate any element from this section

### ISSUE THREAD

**Issue by andriipovkh** [SeleniumHQ/seleniumhq.github.io#1554]
### What happened?

For instance, if you go to the website https://debank.com/ and press "Log in via web3 wallet", you won't be able to locate any element, using find_element, that pop-up in the "connect wallet" window, which is located in /html/rabby-kit// section.
![123](https://github.com/SeleniumHQ/seleniumhq.github.io/assets/33901675/ce845689-30e9-4d46-861d-9a7e3c6c8a3c)
![456](https://github.com/SeleniumHQ/seleniumhq.github.io/assets/33901675/b6a61d7b-e746-46ed-b8dc-61f35ef3c5f0)

### What browsers and operating systems are you seeing the problem on?

Google Chrome Version: 120.0.6099.109 (r1217362)
Windows 10 Pro 22H2

**Comment by diemol** [comment]
This is the repository for the documentation. Here is where you need to create issues in Selenium, filling all the template fields https://github.com/SeleniumHQ/selenium/issues/new/choose
