### ISSUE TITLE
[🐛 Bug]: receive An existing connection was forcibly closed by the remote host when trying to connect selenium using RemoteWebDriver

### ISSUE THREAD

**Issue by lirankremer** [SeleniumHQ/seleniumhq.github.io#1556]
### What happened?

Hi 
I installed selenium 4.16.1 using helm 
the setup is in mode - isolateComponents + ingress
all componence sitting on the same node,
helm --install selenium-grid docker-selenium/selenium-grid --set isolateComponents=true --set ingress.hostname=<name>
I can access the Grid using the address I configured in the ingress and the status shows everything is working as it should
when I ran the RemoteWebDriver I receive the error - "An existing connection was forcibly closed by the remote host"
I verified messages reach the server from networking point of view. 

I didn't found some info about it, but is there some kind of authentication I need to add to the remote?

### What browsers and operating systems are you seeing the problem on?

browser - chrome
the server works on Linux Roky

**Comment by luisfcorreia** [comment]
Please create this issue in https://github.com/SeleniumHQ/selenium as this repo is for Documentation only
