### ISSUE TITLE
[🚀 Feature]: Documentation on docker / kubernetes use

### ISSUE THREAD

**Issue by parholmdahl** [SeleniumHQ/seleniumhq.github.io#1558]
### Feature and motivation

This might be clear for everyone else but me, but I think that the documentation does not really mention how to use grid in docker environment, or kubernetes. How to set things up and so on. 

There are documentations for for example CLI commands, but what are the eqvivalent SE_* environment variable? (some seem to differ from the exact syntax) and so on. 

And i also miss good documentation on the Appium -> Relay -> Selenium Grid functionality, especially good working examples ..

**Comment by luisfcorreia** [comment]
We are most welcome to example contributions

**Comment by diemol** [comment]
All related to Docker can be found at https://github.com/SeleniumHQ/docker-selenium

What are you missing in Relay? What are good examples?

**Comment by parholmdahl** [comment]
> We are most welcome to example contributions

I understand that, and I am most willing to help, when there is time.. But I think that it is very hard to write documentation on something that you dont really understand how it works, or how it is supposed to work..

**Comment by diemol** [comment]
> > We are most welcome to example contributions
> 
> I understand that, and I am most willing to help, when there is time.. But I think that it is very hard to write documentation on something that you dont really understand how it works, or how it is supposed to work..

Have you checked the Docker Selenium repository?

**Comment by parholmdahl** [comment]
> All related to Docker can be found at https://github.com/SeleniumHQ/docker-selenium

Maybe create a webpage on selenium.io that tells the visitor that if you are going to run this in docker, better check the documentation in the git repo?

> What are you missing in Relay? What are good examples?

Maybe just an easy beginner tutorial.. It took me a good day and a half to get a working setup for a mobile phone testing web content.

**Comment by diemol** [comment]
>Maybe create a webpage on selenium.io that tells the visitor that if you are going to run this in docker, better check the documentation in the git repo?

Good idea, would you like to send a PR to add this?

>Maybe just an easy beginner tutorial.. It took me a good day and a half to get a working setup for a mobile phone testing web content.

This could help: http://appium.io/docs/en/2.0/guides/grid/ (you can also send a PR to add this to our docs)

However, most of the complexity in the setup is related to properly understand how Appium is configured, how devices need to be set to have a working environment, and I feel that out of our scope. What did you struggle with?

**Comment by diemol** [comment]
Closing this as we did not see how this could get improved without duplicating the Appium content.

**Comment by VietND96** [comment]
One point relates to ` i also miss good documentation on the Appium -> Relay -> Selenium Grid functionality, especially good working examples ..` that I want to add
Here is an example that configure containerization (Appium -> Relay -> Selenium Grid) https://github.com/SeleniumHQ/docker-selenium?tab=readme-ov-file#node-configuration-relay-commands
