### ISSUE TITLE
[🐛 Bug]: Grid session is not starting if use options.setEnableDownloads(true)

### ISSUE THREAD

**Issue by kalyankumar381** [SeleniumHQ/seleniumhq.github.io#1565]
### What happened?

Grid session is not starting if use options.setEnableDownloads(true) 

### What browsers and operating systems are you seeing the problem on?

Below is the sample code testing download option in grid
@Test
	public void test() throws MalformedURLException {
		ChromeOptions options=new ChromeOptions();
		options.setEnableDownloads(true);
		driver=new RemoteWebDriver(new URL("http://localhost:4444"), options);
	}
	
After running grid session is not starting and displayed

19:05:46.019 INFO [GridModel.release] - Releasing slot for session id 88b5317b8e40b4f847689547e2d3ccab
19:05:46.027 INFO [SessionSlot.stop] - Stopping session 88b5317b8e40b4f847689547e2d3ccab

Successfully running  use below test (comment options.setEnableDownloads(true))

	@Test
	public void test() throws MalformedURLException {
		ChromeOptions options=new ChromeOptions();
//		options.setEnableDownloads(true);
		driver=new RemoteWebDriver(new URL("http://localhost:4444"), options);
	}

**Comment by diemol** [comment]
This repository is for the documentation, please report it to https://github.com/SeleniumHQ/selenium/issues/new/choose
