### ISSUE TITLE
[🐛 Bug]: FAILED tests/drivers/test_remote_webdriver.py::test_downloads - EOFError

### ISSUE THREAD

**Issue by rdinoff** [SeleniumHQ/seleniumhq.github.io#1568]
### What happened?

$ cd seleniumhq.github.io/examples/python/
$ pytest tests/drivers/test_remote_webdriver.py

The code should be updated to use file_names[0] instead of files[0] as files does not get returned in a consistent order which is why the sort is needed in the assert

```
       assert sorted(files) == sorted(file_names)
       downloadable_file = file_names[0]
```

```
[error.txt](https://github.com/SeleniumHQ/seleniumhq.github.io/files/14042672/error.txt)
```

### What browsers and operating systems are you seeing the problem on?

Description:	Ubuntu 20.04.6 LTS
Python 3.8.10
selenium-server-4.16.1.jar

**Comment by titusfortner** [comment]
do you want to PR the fix?

**Comment by rdinoff** [comment]
> do you want to PR the fix?

yes, I will make a PR

**Comment by diemol** [comment]
It seems the PR got merged into your fork.

**Comment by diemol** [comment]
This was already fixed.
