### ISSUE TITLE
[🐛 Bug]: With custom node example, node never see it's registered

### ISSUE THREAD

**Issue by bhecquet** [SeleniumHQ/seleniumhq.github.io#1571]
### What happened?

Hello, 

using your sample code on https://www.selenium.dev/documentation/grid/advanced_features/customize_node/, I noticed that node never see it's registered
It's due to 
```
protected DecoratedLoggingNode(Tracer tracer, URI uri, Secret registrationSecret) {
    super(tracer, new NodeId(UUID.randomUUID()), uri, registrationSecret);
  }
```
where we generate a new NodeId

in https://github.com/SeleniumHQ/selenium/blob/81865828a275ba384bc96fe10493cb1f7ee03f91/java/src/org/openqa/selenium/grid/node/httpd/NodeServer.java#L220

we get node status from node created with

```
Node node = LocalNodeFactory.create(config);
```

which has a different id than our custom node, 
So when getting hub "node-added" registration event

https://github.com/SeleniumHQ/selenium/blob/81865828a275ba384bc96fe10493cb1f7ee03f91/java/src/org/openqa/selenium/grid/node/httpd/NodeServer.java#L143

ids do not match

Instead, constructor should reuse the id of the LocalNode

```
Node node = LocalNodeFactory.create(config);

DecoratedLoggingNode wrapper = new DecoratedLoggingNode(loggingOptions.getTracer(),
				node.getId(),
				uri,
				secretOptions.getRegistrationSecret());
```

### What browsers and operating systems are you seeing the problem on?

chrome / windows

**Comment by diemol** [comment]
@krmahadevan do you have a moment to have a look at this, please?

**Comment by krmahadevan** [comment]
@diemol Sure. Will take a look.

**Comment by krmahadevan** [comment]
@diemol - Observations made by @bhecquet are valid. 

@bhecquet - Would you like to raise a PR for the documentation which makes this change and contribute ?

**Comment by bhecquet** [comment]
@krmahadevan , sure, will do that in a few days

**Comment by bhecquet** [comment]
I've created the PR: https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1576

**Comment by diemol** [comment]
Thanks for contributing, @bhecquet!
