### ISSUE TITLE
[🐛 Bug]: not click the button. at macbook(m version)

### ISSUE THREAD

**Issue by ryujanghyun00** [SeleniumHQ/seleniumhq.github.io#1572]
### What happened?

[🐛 Bug]: not click the button. at macbook(m version)

### What browsers and operating systems are you seeing the problem on?

driver = webdriver.Chrome()
driver.get("https://support-leagueoflegends.riotgames.com/hc/en-us/requests/new?ticket_form_id=21152806417811")
button=driver.find_element(by=By.ID, value="login-dc")
button.click() 

macbook air m2 version

File "/Users/ryujanghyun/Library/Mobile Documents/com~apple~CloudDocs/code/lol ban/lol ban.py", line 9, in <module>
    button.click()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=121.0.6167.139)
Stacktrace:
0   chromedriver                        0x0000000104ca67dc chromedriver + 4040668
1   chromedriver                        0x0000000104c9e9e0 chromedriver + 4008416
2   chromedriver                        0x00000001049116a8 chromedriver + 284328
3   chromedriver                        0x0000000104956330 chromedriver + 566064
4   chromedriver                        0x000000010494b4b8 chromedriver + 521400
5   chromedriver                        0x000000010494aee8 chromedriver + 519912
6   chromedriver                        0x000000010498f048 chromedriver + 798792
7   chromedriver                        0x000000010494974c chromedriver + 513868
8   chromedriver                        0x000000010494a044 chromedriver + 516164
9   chromedriver                        0x0000000104c6ba04 chromedriver + 3799556
10  chromedriver                        0x0000000104c6fee4 chromedriver + 3817188
11  chromedriver                        0x0000000104c54260 chromedriver + 3703392
12  chromedriver                        0x0000000104c70a2c chromedriver + 3820076
13  chromedriver                        0x0000000104c4701c chromedriver + 3649564
14  chromedriver                        0x0000000104c8de3c chromedriver + 3939900
15  chromedriver                        0x0000000104c8dfb4 chromedriver + 3940276
16  chromedriver                        0x0000000104c9e660 chromedriver + 4007520
17  libsystem_pthread.dylib             0x0000000181722034 _pthread_start + 136
18  libsystem_pthread.dylib             0x000000018171ce3c thread_start + 8

**Comment by diemol** [comment]
This is the documentation repository, for Selenium issues please use this repository https://github.com/SeleniumHQ/selenium.
