### ISSUE TITLE
[🐛 Bug]: No scroll_from_origin attribute from ActionChains class

### ISSUE THREAD

**Issue by rena9155** [SeleniumHQ/seleniumhq.github.io#1594]
### What happened?

I was trying to use Selenium to scroll part of a webpage by following an example provided here: https://www.selenium.dev/documentation/webdriver/actions_api/wheel/

Here's the code:
`element = driver.find_element(By.ID,"xxx")
scroll_origin = ScrollOrigin.from_element(element)
ActionChains(driver).scroll_from_origin(scroll_origin, 0, 200).perform()`
And then I got an AttributeError: 'ActionChains' object has no attribute 'scroll_from_origin'

### What browsers and operating systems are you seeing the problem on?

Chrome, Mac

**Comment by diemol** [comment]
This is the repository for the documentation. Also the code shown is passing on a daily basis in our CI. 

Please create this issue at https://github.com/SeleniumHQ/selenium
