### ISSUE TITLE
[🐛 Bug]: Selenium-manager file is x86-64 instead of ARM64 compatible 

### ISSUE THREAD

**Issue by obriankevin11** [SeleniumHQ/seleniumhq.github.io#1595]
### What happened?

I have .net6 project running on Linux/ARM64 (raspberry pi 4)

`<PackageReference Include="Selenium.WebDriver" Version="4.18.1" />`

Dockerfile
```
ARG BUILDPLATFORM=linux/arm64
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
...
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:6.0 AS build
...
```

Projects runs ok until Selenium is involved.

when I log into my container and check selenium-manager:
```
/app/selenium-manager/linux# file selenium-manager 
selenium-manager: ELF 64-bit LSB pie executable, **x86-64**, version 1 (SYSV), static-pie linked, stripped
```
and
```
/app# file WebDriver.dll
WebDriver.dll: PE32 executable (DLL) (console) Intel 80386 **Mono/.Net** assembly, for MS Windows
```

whereas my app.dll is ok (runs ok)
/app# file app.dll
app.dll: PE32 executable (console) Intel 80386 **Mono/.Net** assembly, for MS Windows

Why is the version of selenium-manager x86-64?

### What browsers and operating systems are you seeing the problem on?

/```
app# uname -a
Linux 6cceb71f1fa1 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by diemol** [comment]
You can find the reasons here https://www.selenium.dev/documentation/selenium_manager/#alternative-architectures
