### ISSUE TITLE
[🐛 Bug]: Local edge driver session - session not created exception.

### ISSUE THREAD

**Issue by publicgitsmu** [SeleniumHQ/seleniumhq.github.io#1610]
### What happened?

**Src Code:**
from selenium import webdriver
from selenium.webdriver.common.by import By
driver = webdriver.Edge()
driver.get('https://bing.com/')
driver.quit()

**Root Cause:**
This is observed, that setting below Registry entry via the policy changes
Computer\HKEY_CURRENT_USER\Software\Policies\Microsoft\Edge\RemoteDebuggingAllowed is set to 0

When the above flag is enabled, there is no session error.
But the registries are not supposed to be modified. Can you help with alternatives such that which allows to establish the session without changing the above registry entry.

**Log Message:**
[1710521384.317][INFO]: Failed to connect to msedge. Attempting to kill it.
[1710521384.672][INFO]: [828764adfde14499aea3516269fbaf26] RESPONSE InitSession ERROR session not created: **DevToolsActivePort file doesn't exist**

### What browsers and operating systems are you seeing the problem on?

OS : Windows 11
Browser : MS edge

**Comment by diemol** [comment]
Please report it at https://github.com/MicrosoftEdge/EdgeWebDriver
