### ISSUE TITLE
Documentation, Installing Standalone server 

### ISSUE THREAD

**Issue by agitkaplan** [SeleniumHQ/seleniumhq.github.io#162]
## 🐛 Bug Report

Hi, 

I think this page gives a bit confusion: https://selenium.dev/documentation/en/selenium_installation/installing_standalone_server/ 

It says "The selenium-server-standalone jar is never uploaded, but all the components are available via selenium-server." but i think first link in download page (https://selenium.dev/downloads/ ) which is about Selenium Server (Grid) is standalone.jar file. 

Best regards.

**Comment by diemol** [comment]
Fixed in the referenced commit
