### ISSUE TITLE
[🐛 Bug]:  fix the comma splice

### ISSUE THREAD

**Issue by markhu** [SeleniumHQ/seleniumhq.github.io#1647]
### What happened?

This sentence is not gramatically correct: "WebDriver drives a browser natively, learn more about it." It has a comma-splice. It is the first thing you see at https://www.selenium.dev/documentation/webdriver/

### What browsers and operating systems are you seeing the problem on?

all browsers display this wording issue

**Comment by diemol** [comment]
Would you like to send a pull request to help us?
