### ISSUE TITLE
Need more  detailed explainations for the configurations of selenium-grid

### ISSUE THREAD

**Issue by lzt007** [SeleniumHQ/seleniumhq.github.io#1655]
As is shown in Grid>Configuration>Toml Options>Configuring and customising drivers. We can configure different browsers on a single node by set like the given example：

```
[node]
detect-drivers = false
[[node.driver-configuration]]
max-sessions = 100
display-name = "Firefox Nightly"
stereotype = "{\"browserName\": \"firefox\", \"browserVersion\": \"93\", \"platformName\": \"MAC\", \"moz:firefoxOptions\": {\"binary\": \"/Applications/Firefox Nightly.app/Contents/MacOS/firefox-bin\"}}"
[[node.driver-configuration]]
display-name = "Chrome Beta"
stereotype = "{\"browserName\": \"chrome\", \"browserVersion\": \"94\", \"platformName\": \"MAC\", \"goog:chromeOptions\": {\"binary\": \"/Applications/Google Chrome Beta.app/Contents/MacOS/Google Chrome Beta\"}}"
[[node.driver-configuration]]
display-name = "Chrome Dev"
stereotype = "{\"browserName\": \"chrome\", \"browserVersion\": \"95\", \"platformName\": \"MAC\", \"goog:chromeOptions\": {\"binary\": \"/Applications/Google Chrome Dev.app/Contents/MacOS/Google Chrome Dev\"}}"
webdriver-executable = '/path/to/chromedriver/95/chromedriver'
``` 

We can use a key "moz:firefoxOption" for firefox and "goog:chromeOption" for chrome. My question is, what should I use when configure browsers such as edge, ie or other supported browsers? I can't find a way to check what key-name should I use espically the abbreviations like "moz:","goog:"

There are also same questions in other examples like "networkname:applicationName":"node_1",""appium:platformVersion","gsg:customcap"
I think those kind of key-names like str1:str2 need more detailed  explainations for their meanings. What does str1 and str2 mean or it’s just a no meaning varname with “:” . Where can I find all the supported keys like that for the option？Is those keys same for all type of browsers? If not, what are they.

**Comment by diemol** [comment]
Edge is [`ms:edgeOptions`](https://github.com/SeleniumHQ/selenium/blob/trunk/java/src/org/openqa/selenium/edge/EdgeOptions.java#L48).

IE is [`se:ieOptions`](https://github.com/SeleniumHQ/selenium/blob/trunk/java/src/org/openqa/selenium/ie/InternetExplorerOptions.java#L61).

The last part refers to [custom capabilities for matching](https://www.selenium.dev/documentation/grid/configuration/toml_options/#setting-custom-capabilities-for-matching-specific-nodes).
