### ISSUE TITLE
[🐛 Bug]: Hugo depericate warning "custom params on the language top level was deprecated in Hugo v0.112.0 and will be removed in Hugo 0.126.0"

### ISSUE THREAD

**Issue by chamiz** [SeleniumHQ/seleniumhq.github.io#1697]
### What happened?

After updating hugo v0.125.4 , I'm getting "custom params on the language top level was deprecated in Hugo v0.112.0 and will be removed in Hugo 0.126.0"for several translations. 

**Commad**
hugo server

**Errors**
ERROR deprecated: config: languages.zh-cn.description: custom params on the language top level was deprecated in Hugo v0.112.0 and will be removed in Hugo 0.126.0. Put the value below [languages.zh-cn.params]. See https://gohugo.io/content-management/multilingual/#changes-in-hugo-01120
ERROR deprecated: config: languages.ja.description: custom params on the language top level was deprecated in Hugo v0.112.0 and will be removed in Hugo 0.126.0. Put the value below [languages.ja.params]. See https://gohugo.io/content-management/multilingual/#changes-in-hugo-01120
ERROR deprecated: config: languages.other.description: custom params on the language top level was deprecated in Hugo v0.112.0 and will be removed in Hugo 0.126.0. Put the value below [languages.other.params]. See https://gohugo.io/content-management/multilingual/#changes-in-hugo-01120
ERROR deprecated: config: languages.en.description: custom params on the language top level was deprecated in Hugo v0.112.0 and will be removed in Hugo 0.126.0. Put the value below [languages.en.params]. See https://gohugo.io/content-management/multilingual/#changes-in-hugo-01120
ERROR deprecated: config: languages.pt-br.description: custom params on the language top level was deprecated in Hugo v0.112.0 and will be removed in Hugo 0.126.0. Put the value below [languages.pt-br.params]. See https://gohugo.io/content-management/multilingual/#changes-in-hugo-01120

**Action** 
So if we need to support Hugo's latest versions we need to fix these issues.

### What browsers and operating systems are you seeing the problem on?

Windows 11
Hugo v0.125.4

**Comment by chamiz** [comment]
So as a fix, we need to put the values as suggested.
 [languages.zh-cn.params]

Source
https://gohugo.io/content-management/multilingual/#changes-in-hugo-01120

**Comment by diemol** [comment]
Closed via the linked PR, thank you @chamiz!
