### ISSUE TITLE
[🐛 Bug]: JavaScript issue with Selenium web site (https://www.selenium.dev), throwing JavaScript type error

### ISSUE THREAD

**Issue by sbabcoc** [SeleniumHQ/seleniumhq.github.io#1737]
### What happened?

I'm using **HtmlUnitDriver** for testing, and the JavaScript engine used by **HtmlUnit** is throwing a TypeError loading the pages from the Selenium web site (`https://www.selenium.dev`). The error is:

```
TypeError: redeclaration of const n. (https://www.selenium.dev/js/main.min.0a56205ed1c75268f017591e5418fdb944578a279fe7c7abe3981ebed191c341.js#5)
```

I can work around this issue by disabling the resulting exception in **HtmlUnitDriver**, but it would be good to clean this up.

### What browsers and operating systems are you seeing the problem on?

**HtmlUnitDriver** loading `https://www.selenium.dev`

**Comment by diemol** [comment]
I do not see that error when using the browser, how can I reproduce it manually?

**Comment by sbabcoc** [comment]
Hmmm... Looking closer, this seems more likely to be a Rhino issue. I'll close this Selenium issue and open a new one for Rhino.
