### ISSUE TITLE
[🐛 Bug]: There is no Example code for Local Driver in Driver Sessions.

### ISSUE THREAD

**Issue by itsgoodtobebad** [SeleniumHQ/seleniumhq.github.io#1750]
### What happened?

![20240604174501](https://github.com/SeleniumHQ/seleniumhq.github.io/assets/11895230/fd2068b1-0c2a-410c-9e9b-b524602a422e)

### What browsers and operating systems are you seeing the problem on?

Chrome

**Comment by titusfortner** [comment]
Yes, this is our way of indicating that work needs to be done, there are a bunch of those, and we dint want to track all of them as github issues
