### ISSUE TITLE
[🐛 Bug]: Design of Website is broken

### ISSUE THREAD

**Issue by twistios** [SeleniumHQ/seleniumhq.github.io#1796]
### What happened?

I previously submitted a bugreport to webcompat (see [here](https://github.com/webcompat/web-bugs/issues/138737)).
It actually seem to be an issue with the website as it does happen for both Firefox and Edge on my device.

Open the website www.selenium.dev. Observe the top-menu (see image in linked issue).

### What browsers and operating systems are you seeing the problem on?

Browsers: Firefox 127.0, Edge 126.0
OS: Windows 11.

**Comment by harsha509** [comment]
Hi @twistios ,

Thank you for raising the issue!

Fixed with commit https://github.com/SeleniumHQ/seleniumhq.github.io/commit/ce74a097977e2f273b14ddac7e31b86e8b82c93f

Thanks,
Sri
