### ISSUE TITLE
Remove deprecated Selenium class from Documentation code examples

### ISSUE THREAD

**Issue by marksnelson09** [SeleniumHQ/seleniumhq.github.io#189]
## 🐛 Bug Report
The Selenium class is used in the Documentation code example on the 
'Guidelines > Page object models' page and possibly elsewhere. This was confusing, since I don't recall it being explained or referenced in the Documentation flow prior to this page. Then, I found in the API that the class is deprecated, which explained why it's usage isn't explained.

References to the Selenium class might also occur on other pages. Though, I might be confused by examples that I encountered on other websites.

## To Reproduce
https://selenium.dev/documentation/en/guidelines_and_recommendations/page_object_models/
![Selenium bug](https://user-images.githubusercontent.com/60354885/73191819-bd905100-40ed-11ea-8f77-5e46c0abfb3d.png)

## Expected behavior
Please update the code examples to not reference deprecated classes. Thanks

## Environment
* OS:  Windows
* Browser: Edge
* Browser version: 44.18362.449.0

**Comment by diemol** [comment]
Thanks for raising this @marksnelson09, would you like to give us a hand and send a PR fixing the code samples?

**Comment by marksnelson09** [comment]
I'm brand new to Selenium, and this is my first time using with GitHub. Perhaps, if I grow comfortable with my understanding of Selenium, I can come back around to figure out what the code examples should be.

**Comment by diemol** [comment]
@marksnelson09 why don't you have a look to https://selenium.dev/documentation/en/contributing/? There are clear instructions on how to get started and send us contributions.
