### ISSUE TITLE
[🐛 Bug]: "SELENIUM_CI_TOKEN not set" error when rendering examples

### ISSUE THREAD

**Issue by attila-fazekas** [SeleniumHQ/seleniumhq.github.io#1891]
### What happened?

I followed the [contributing guide](https://www.selenium.dev/documentation/about/contributing/) and ran `hugo server`.

After opening http://localhost:1313/ and checking examples, I faced the following error:
![Screenshot 2024-08-25 at 13 29 30](https://github.com/user-attachments/assets/4e3920a3-fe13-4aea-834a-4e736561a8ca)

For local development, I believe I don't need to render content fetched from the GitHub API, so I'm not sure what steps I should take to solve this issue.

### What browsers and operating systems are you seeing the problem on?

```
❯ hugo version
hugo v0.125.4-cc3574ef4f41fccbe88d9443ed066eb10867ada2+extended darwin/arm64 BuildDate=2024-04-25T13:27:26Z VendorInfo=gohugoio

❯ sw_vers
ProductName:		macOS
ProductVersion:		14.1
BuildVersion:		23B2073
```

**Comment by harsha509** [comment]
HI @attila-fazekas ,

I don't believe this is an error or a warning. It is more like an informational message related to rendering code samples during local development. 

We load code samples from GitHub to ensure that code line numbers are correctly linked to the documentation, which requires an API token to access the samples from GitHub.

For local development, you should be able to work on tasks that aren't directly related to the API.

Thanks,
Sri

**Comment by attila-fazekas** [comment]
Hi Sri,

Thanks for looking into it.

 I see, then I'm closing this issue.
