### ISSUE TITLE
Add new language on site (Korean)

### ISSUE THREAD

**Issue by 0420syj** [SeleniumHQ/seleniumhq.github.io#19]
Hello. I am a university student in Korea. First of all, thank you for your wonderful project and documentation.
I've recently learned about crawler including this for team project, and my friends and I were really impressed by your documentation. And I would like to add Korean to your document. Because there'are lot of people who are interested in crawler this could help more Korean developer to use Selenium.
I am raising an issue because I want to hear your opinion on this. Thank you for reading the long post.

PS. And I have also signed the CLA on this [link](https://github.com/SeleniumHQ/docs/blob/gh-pages/README.md).

**Comment by diemol** [comment]
Hi @0420syj @lionking6792

Thank you for offering to translate our documentation to Korean 🙌 🎉 

Have a look at the contributing guidelines [here](https://selenium.dev/documentation/en/contributing/). If you need any help, please let us know.

**Comment by lionking6792** [comment]
Hi! @diemol 

Thanks for your comment and advice.
I'll PR Korean version of docs as soon as possible!

Thanks :)

**Comment by diemol** [comment]
Fixed via #68, thanks @0420syj
