### ISSUE TITLE
Is page loading strategy should be displayed as a link without any content?

### ISSUE THREAD

**Issue by yingyingshang** [SeleniumHQ/seleniumhq.github.io#190]
###  Could you help to confirm if the page should be displayed as this? I was thinking it may have more descriptions.
![image](https://user-images.githubusercontent.com/52477678/73260354-b1e37e00-4204-11ea-876a-8c8631b8fe6c.png)

**Comment by Harsha509** [comment]
hi @yingyingshang,

most of our documentation is in Work in Progress mode. Please feel free to write content and raise a PR.

Thanks,
Harsha
