### ISSUE TITLE
[🚀 Feature]: Documentation is not available in pdf format

### ISSUE THREAD

**Issue by phonokoye** [SeleniumHQ/seleniumhq.github.io#1935]
### Feature and motivation

The documentation for selenium webdriver can be found [here](https://www.selenium.dev/documentation/), however I cannot find a version for offline reading. I would appreciate that one is created or a step by step approach on what commands to run to build such documentation on a personal computer is given.

I am not aware if this might violate something expected of a feature request. If it does, please tell me and I will correct this post. 

Thank you.

**Comment by diemol** [comment]
We cannot offer that because the documentation constantly changes. 

An alternative is for you to clone the repository and run it locally: https://github.com/SeleniumHQ/seleniumhq.github.io?tab=readme-ov-file#quick-start

**Comment by shamefulCake1** [comment]
> We cannot offer that because the documentation constantly changes.
> 
> An alternative is for you to clone the repository and run it locally: https://github.com/SeleniumHQ/seleniumhq.github.io?tab=readme-ov-file#quick-start

This is a ridiculous excuse. Of course it constantly changes, but nothing prevents the PDF from constantly changing as well.
For example, GNU Texinfo generates multiple formats (html, pdf, etc) from the same source, and pandoc/wkhtmltopdf/htmldoc generate pdf from html.

**Comment by cgoldberg** [comment]
@shamefulCake1 
This is a project run by small group of volunteers. Instead of complaining, you should provide a solution that generates a PDF each time the docs are built and publishes it somewhere online. When you have it working, please submit a PR.

**Comment by shamefulCake1** [comment]
You should not be telling me what to do, and I would not be telling you where to go.

Instead of producing obviously false excuses, you should be grateful to people doing unpaid QA for you.

**Comment by cgoldberg** [comment]
Well... you can complain about it and still have no PDF... or you could contribute a solution and have the PDF along with everyone else.

If this is what you consider "unpaid QA"... then no thank you, we can do without that.
