### ISSUE TITLE
[🚀 Feature]: Add Documentation for PrintOptions

### ISSUE THREAD

**Issue by shbenzer** [SeleniumHQ/seleniumhq.github.io#1941]
### Feature and motivation

From what I've seen, the documentation and use cases for Selenium's PrintOptions class is rather limited. I think the community would benefit from the team expanding on this.

https://www.selenium.dev/selenium/docs/api/java/org/openqa/selenium/print/PrintOptions.html

**Comment by shbenzer** [comment]
@harsha509 do you think this should be added to it's own sub-section in the documentation under WebDriver?

**Comment by shbenzer** [comment]
or we could add a section on "Augmenting the Webdriver" where we also add documentation for classes like WebStorage, Augmenter, etc.

**Comment by harsha509** [comment]
Hi @shbenzer ,

How about adding new section under [Browser interactions](https://www.selenium.dev/documentation/webdriver/interactions/) named "Print Page"

**Comment by shbenzer** [comment]
That works!

**Comment by shbenzer** [comment]
Closed with #1987

**Comment by shbenzer** [comment]
Going to add examples for Python and C# before closing since it's implemented in those languages as well as java. Then put PrintOptions in one section, then actually Printing in another

**Comment by shbenzer** [comment]
Can now be closed - other languages are missing implementations. With completion of implementations in other languages, the badge codes should be sufficient
