### ISSUE TITLE
[🐛 Bug]: WebDriver BiDi Options link to example.com

### ISSUE THREAD

**Issue by Delta456** [SeleniumHQ/seleniumhq.github.io#1951]
### What happened?

The `[enable it in Options](http://www.example.com/)` text in https://www.selenium.dev/documentation/webdriver/bidi/ links to unrelated link `http://www.example.com/`. It should either be removed or an alternative link must be added.

<img width="446" alt="image" src="https://github.com/user-attachments/assets/c6abc6dd-c201-45c9-8c15-d04f60d54438">

### What browsers and operating systems are you seeing the problem on?

Macos, Chrome

**Comment by harsha509** [comment]
HI @Delta456 ,
Thank you for identifying it.

Will update docs accordingly!

Thanks,
Sri
