### ISSUE TITLE
EdgeDriver name doesn't match

### ISSUE THREAD

**Issue by GZLHZ** [SeleniumHQ/seleniumhq.github.io#197]
## 🐛 Bug Report

![image](https://user-images.githubusercontent.com/45257277/73468164-50b3da00-43bf-11ea-89dc-53c017d4cf89.png)

hello,I download the python code by pip3 and then i found that the .exe name is not the same as the file download on the microsoft which named as msedgedriver.exe

So it's different from Chrome And FireFox, they are the same name.

Rename the .exe file can solve the problem.
But I think modify MicrosoftWebDriver.exe to msedgedriver.exe is a good idea.😄
It will be nice to the beginners.
Thank you.

OS: Windows 10
Browser: New Edge
Browser version:79.0.309.71

**Comment by diemol** [comment]
@GZLHZ could you please post this on https://github.com/SeleniumHQ/selenium/issues/new/choose and filling out the complete template please?

**Comment by GZLHZ** [comment]
@diemol   hello, I just suggested changing a name.😂  what do you want to know else? I will explain more clearly.
![image](https://user-images.githubusercontent.com/45257277/73626849-66f2bc00-4685-11ea-8a25-a52464e3c9de.png)
