### ISSUE TITLE
[🌍 Translation]: Japanese Translations Required for WebDriver Page and Subsections

### ISSUE THREAD

**Issue by AishIngale** [SeleniumHQ/seleniumhq.github.io#2015]
### What needs to be translated

WebDriver main page and subsections:
[WebDriver](https://www.selenium.dev/documentation/webdriver/)
[Getting Started](https://www.selenium.dev/documentation/webdriver/getting_started/)
[Drivers](https://www.selenium.dev/documentation/webdriver/drivers/)
[Browsers](https://www.selenium.dev/documentation/webdriver/browsers/)
[Waits](https://www.selenium.dev/documentation/webdriver/waits/)
[Elements](https://www.selenium.dev/documentation/webdriver/elements/)
[Interactions](https://www.selenium.dev/documentation/webdriver/interactions/)
[Actions API](https://www.selenium.dev/documentation/webdriver/actions_api/)
[BiDi](https://www.selenium.dev/documentation/webdriver/bidi/)
[Support Features](https://www.selenium.dev/documentation/webdriver/support_features/)
[Troubleshooting](https://www.selenium.dev/documentation/webdriver/troubleshooting/)

This is the incompletely translated WebDriver main page:
<img width="959" alt="image" src="https://github.com/user-attachments/assets/ce8d9ca9-a2d1-48af-bdc3-9478cb75a235">

**Comment by AishIngale** [comment]
@harsha509 Could you please add a 'hacktoberfest' label to this issue? I am unable to.
I am working on implementing the Japanese translations for WebDriver topic.

**Comment by harsha509** [comment]
> @harsha509 Could you please add a 'hacktoberfest' label to this issue? I am unable to. I am working on implementing the Japanese translations for WebDriver topic.

Sure

**Comment by AishIngale** [comment]
[Japanese translations for WebDriver topics #2029](https://github.com/SeleniumHQ/seleniumhq.github.io/pull/2029/files#diff-3e852f27c226e1c9c7225112069d43d93dea6a09b6257647d8aaea9cd20e984bR1-R341)

**Comment by harsha509** [comment]
changes landed with PR https://github.com/SeleniumHQ/seleniumhq.github.io/pull/2029
