### ISSUE TITLE
Types of Testing page (content)

### ISSUE THREAD

**Issue by boris779** [SeleniumHQ/seleniumhq.github.io#237]
## 🐛 Bug Report

While translating the documentation from English to German, I think that the Types of Testing Page needs a update. Concrete I think that the description for acceptance testing and functionial testion are too similar and it is not clear what the difference is (verification vs. validation)

## To Reproduce

https://selenium.dev/documentation/en/introduction/types_of_testing/

If you want me to rewrite it just tag me to that issue and I will do it. But what happens to the already translated pages (spanish, french, ....)

**Comment by diemol** [comment]
@boris779, good point. 
We would be grateful if you want to give us a hand by proposing something new in those sections 🙌 

About the existing translations, we can just reset the section back to English and put the let the readers know that we need help with the new translation.

**Comment by boris779** [comment]
Ok. I will work on a proposal for that section.
