### ISSUE TITLE
sendkeys - Add list of possible key strokes

### ISSUE THREAD

**Issue by p2635** [SeleniumHQ/seleniumhq.github.io#389]
## 🚀 Feature Proposal for the site or the documentation

The sendkeys only has one example - e.g. ${KEY_ENTER}). It's not very helpful and leads me to guess the other ones like ${KEY_TAB}, is that even valid? A list of valid keystrokes needs to be confirmed for example shift, alt and other things like that.

## Motivation

As above.

## Example

As above.

**Comment by Harsha509** [comment]
Hi @p2635 ,

Thanks for raising an issue. 

Mostly, WebDriver supports all possible keystrokes available in a general keyboard. So, we've provided a precise example with Keystroke `Enter` for sendKeys.

[Here](https://www.w3.org/TR/webdriver/#keyboard-actions) is the list of available keystrokes that WebDriver supports currently.

I've also updated the documentation accordingly!

Regards,
Harsha.

**Comment by p2635** [comment]
Thanks @Harsha509 , please update this page if you haven't already: https://www.selenium.dev/selenium-ide/docs/en/api/commands#send-keys
