### ISSUE TITLE
Libraries or framework section

### ISSUE THREAD

**Issue by ivanrodjr** [SeleniumHQ/seleniumhq.github.io#393]
## 🚀 Feature Proposal for the site or the documentation

Provide a section dedicated to frameworks or libraries both in the JVM and in other languages that use Selenium as its main dependency, under the hood or as supported, e.g. Webdriver.io, Watir

## Motivation

Inform readers after they have read the basic documentation on existing libraries or frameworks that use WebDriver. This could cover users who are not JVM language based to find selenium frameworks that match their current capabilities in languages they feel more comfortable.

## Example
Another section in the side bar or under an existing topic where it would fit e.g.: 3rd party frameworks
- Basic descriptions for frameworks in other languages and links to them
- Similar to [this](https://www.selenium.dev/documentation/en/getting_started_with_webdriver/third_party_drivers_and_plugins/)

**Comment by diemol** [comment]
Hey @ivanrodjr,

This already exists, see https://www.selenium.dev/ecosystem/
