### ISSUE TITLE
selenium-server-standalone dumps Firefox profile on stderr

### ISSUE THREAD

**Issue by amkhlv** [SeleniumHQ/seleniumhq.github.io#404]
## 🐛 Bug Report

When using custom Firefox profile, `java -jar selenium-server-standalone-3.141.59.jar -role node` dumps the whole (zipped?) profile to stderr, as part of Capabilities. This is several Megabytes...

## To Reproduce

`java -jar selenium-server-standalone-3.141.59.jar -role node` 

with `prepareLoadedProfile_` as `ffProfile` (using Haskell bindings)

## Expected behavior

There should be some way of restricting diagnostic messages to something reasonable... One should not have megabytes of data just dumped on `stderr`, especially when there is no actual error.

## Environment

* OS: 
* Browser: 
* Browser version:

**Comment by Harsha509** [comment]
Hi @amkhlv,

Thanks for raising the issue!

But this question is best suitable to ask in [SeleniumHQ/Selenium](https://github.com/SeleniumHQ/selenium/issues)

Only documentation issues goes here. Can you please log the same issue in [SeleniumHQ/Selenium](https://github.com/SeleniumHQ/selenium/issues) 

Regards,
Harsha
