### ISSUE TITLE
Company listing disappeared?

### ISSUE THREAD

**Issue by roydekleijn** [SeleniumHQ/seleniumhq.github.io#412]
## 🚀 Feature Proposal for the site or the documentation

On the old seleniumhq.org website, there was this page: https://github.com/SeleniumHQ/www.seleniumhq.org/blob/master/src/main/webapp/ecosystem/index.jsp A listing of companies providing Selenium WebDriver services.

## Motivation

It would be great to include this page again on the new website.

## Example

So, people have a clear overview of companies providing Selenium WebDriver related services.

![image](https://user-images.githubusercontent.com/1298389/80892568-75279700-8ccb-11ea-8566-fe5f4b15180b.png)

In between those commits, the page disappeared

**Comment by roydekleijn** [comment]
ok, found the commit: https://github.com/SeleniumHQ/seleniumhq.github.io/commit/45a7e575f689a8abf48e90b609ee219fe565c3f0

It was removed for a reason..

**Comment by diemol** [comment]
Hey @roydekleijn 
Right, the commit has the information, you were faster than me to look it up 👍
