### ISSUE TITLE
Unable to Locate Selenium IDE Terms & Conditions

### ISSUE THREAD

**Issue by Dixie9660** [SeleniumHQ/seleniumhq.github.io#417]
Before we're able to acquire **Selenium IDE** software, our Customer (NASA) requires a review of all software Terms and Conditions.  After searching for the Selenium IDE T&C document or link for the past three (3) days, I'm back to square one.  

There is an urgent need to acquire this product, but my hands are tied until I can comply with the Customer's requirement.  Any help would be GREAT** appreciated.  Thanks, Jeff

**Comment by diemol** [comment]
All projects under the Selenium name are licensed under the Apache model, it is visible there at the repo https://github.com/SeleniumHQ/selenium-ide/blob/master/LICENSE

**Comment by Dixie9660** [comment]
Good afternoon Diego, and thanks for getting back to me with this information.

With respect to the screen capture below, under Permissions, I see no mention of Government use.  Would you be able to let me know if we can install on government owned servers/computers too?

[cid:image002.jpg@01D62AB0.AC8CD610]
I really appreciate your help with this.  Please have a FUN/SAFE/HAPPY weekend.


Jeffrey Hennessey
Service Provider
NASA Shared Services Center
Stennis Space Center, MS  39529
228-813-6427  Jeffrey.d.hennessey@nasa.gov<mailto:Jeffrey.d.hennessey@nasa.gov>

**Comment by diemol** [comment]
I am not entitled to give any legal advice, what you can do is take the link provided about which contains the license and check it with your legal department to see if this fits your needs.
