### ISSUE TITLE
WebDrive can't render https://login.proficio.com

### ISSUE THREAD

**Issue by marcozj** [SeleniumHQ/seleniumhq.github.io#422]
## 🐛 Bug Report

Tried following code to navigate to https://login.proficio.com but the page isn't rendered properly. Same for ChromeDirver and Firefox Driver too.

## To Reproduce

Use following code.

package webtest;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.safari.SafariDriver;

class WebTest {

public static void main(String[] args) {
    //WebDriver driver = new ChromeDriver();
    WebDriver driver = new SafariDriver();
      
    // Launch Website  
    driver.navigate().to("https://login.proficio.com");
      
    //Maximize the browser
    driver.manage().window().maximize();

}
}

## Expected behavior

It should render the site properly.

## Environment

* OS: Windows and macOS
* Browser: Chrome, Safari and Firefox
* Browser version: Chrome 81.0.4044.138 and Safari 13.0.5

**Comment by Harsha509** [comment]
Hi @marcozj ,

Thanks for raising an issue. 

This room is for Selenium documentation issues. 

I have seen the issue and looks like it is best suitable to raise in Selenium/issues.
Can you please raise the same issue in [here](https://github.com/SeleniumHQ/selenium/issues)

Thanks,
Harsha.

**Comment by marcozj** [comment]
got it thanks.
