### ISSUE TITLE
Python code examples should use Python3 print() syntax

### ISSUE THREAD

**Issue by cgoldberg** [SeleniumHQ/seleniumhq.github.io#431]
## Expected behavior

Python examples in documentation should all use Python3 syntax, not Python2.

## Actual behavior

Many examples in the docs use the old `print` statement syntax rather than `print()` function.

## Rationale

Python2 is EOL as of January 2020 and support for it will be dropped from the Python language bindings sooner than later (I expect).  Using the old syntax will cause confusion for beginners reading the official documentation.

**Comment by Harsha509** [comment]
Hi @cgoldberg ,

Thank you for providing the information. I will revisit the PY code samples and will do changes accordingly.

Regards,
Harsha.

**Comment by cgoldberg** [comment]
@Harsha509 great, thanks!

**Comment by Harsha509** [comment]
I've revisited PY code samples and made changes accordingly targeting PY3 version. Changes are landed with [this](https://github.com/SeleniumHQ/seleniumhq.github.io/commit/cf5a472a612d221175a78fdcf2b82ac31c27c6d0) commit.

**Note**: If changes are not done/missed in any of document, those will be done eventually when encountered. Also code samples will be accepted once tested in PY3 going further.

Regards,
Harsha
