### ISSUE TITLE
Make Java example in en/index.html compilable

### ISSUE THREAD

**Issue by haqer1** [SeleniumHQ/seleniumhq.github.io#448]
## 🐛 Bug Report

It currently doesn't compile. And according to 
https://www.selenium.dev/selenium/docs/api/java/org/openqa/selenium/support/ui/WebDriverWait.html
WebDriverWait constructor doesn't accept a Duration param, so it needs to be changed it to long (or something else).

## To Reproduce

Try to compile the source code.

## Expected behavior

It doesn't, but should.

## Environment

* OS: Any
* Browser: Any
* Browser version: Any

**Comment by Harsha509** [comment]
Hi @haqer1 ,

Am able to execute code sample successfully. Can you please let me know what is the selenium version you're using.

Note: All code samples are written and tested with latest selenium Alpha versions.

Regards,
Harsha.

**Comment by haqer1** [comment]
I use the latest stable version: 3.141.59.
Projects usually recommend using stable versions, & documentation should target stable versions as well. Is this not the case for Selenium?

**Comment by Harsha509** [comment]
Hi @haqer1 ,

There are few deprecated things in Selenium 4(Like Timeout in seconds in this case) when compared to Selenium 3. Our new documentation targets the code samples tested with Selenium4, this is to make easy for the users when Selenium4 releases.

Regards,
Harsha.

**Comment by Harsha509** [comment]
Hi @haqer1 ,

If you've any more questions/thoughts we can discuss [here](https://seleniumhq.slack.com/join/shared_invite/enQtODAwOTUzOTM5OTEwLTZjZjgzN2ExOTBmZGE0NjkwYzA2Nzc0MjczMGYwYjdiNGQ5YjI0ZjdjYjFhMjVlMjFkZWJmNDYyMmU1OTYyM2Y). Am closing this issue for now.

Regards,
Harsha
