### ISSUE TITLE
some font files giving 404 on the selenium.dev site 

### ISSUE THREAD

**Issue by phanirithvij** [SeleniumHQ/seleniumhq.github.io#465]
## 🐛 Bug Report

some font files giving 404 on the selenium.dev site.
In this page https://www.selenium.dev/documentation/en/grid/

## To Reproduce

Go to selenium.dev and open devtools

![DeepinScreenshot_20200619162802](https://user-images.githubusercontent.com/29627898/85130738-1c986300-b253-11ea-9915-929b657f81eb.png)

## Expected behavior

The font files should not give 404

OS: linux
Browser: Chrome

**Comment by phanirithvij** [comment]
cc @diemol

**Comment by diemol** [comment]
Seems @Harsha509 fixed this through #468
