### ISSUE TITLE
Missing documentation for TakeScreenshot WebDriver Endpoint

### ISSUE THREAD

**Issue by sindhudiddi** [SeleniumHQ/seleniumhq.github.io#482]
## 🚀 Feature Proposal for the site or the documentation

Missing documentation for /Screenshot WebDriver Endpoint.

## Motivation

Explanation for TakeScreenshot, TakeScreenshot for element and availability of code examples will be useful

**Comment by diemol** [comment]
@sindhudiddi would you like to help us with a pull request?

**Comment by sindhudiddi** [comment]
Sure @diemol, I will raise a PR for this.
Thank you.

**Comment by diemol** [comment]
Closed via #483
