### ISSUE TITLE
C# Example on Documentation Home Page Doesn't Compile

### ISSUE THREAD

**Issue by rich-newman** [SeleniumHQ/seleniumhq.github.io#514]
## 🐛 Bug Report

The C# example on the documentation home page ([https://www.selenium.dev/documentation/en/](https://www.selenium.dev/documentation/en/)) doesn't compile, and gives a warning about obsolete code.

## To Reproduce

Steps taken:

- Started VS2019 C# console app (.NET Core)
- Installed NuGet packages Selenium.WebDriver, Selenium.Support, Selenium.Firefox.WebDriver
- Copy/pasted code from [Selenium documentation page](https://www.selenium.dev/documentation/en/), C# tab

This results in:

- An error: The type or namespace name 'SeleniumExtras' could not be found
- A warning: 'ExpectedConditions' is obsolete: 'The ExpectedConditions implementation in the .NET bindings is deprecated and will be removed in a future release.

If you comment out 'using SeleniumExtras.WaitHelpers;', which is the line giving the error, then the code does build and run, and extracts some data from the Google results, although not about cheese.

I guessed that those are the NuGet packages I needed, by the way.  The [only guidance says to install Selenium.WebDriver only](https://www.selenium.dev/documentation/en/selenium_installation/installing_selenium_libraries/), which doesn't work.  Some clarity on that would help as well.

I'm your typical impatient dev who just wants to see something working as quickly as possible, and that code would actually be a really good starting point if it worked cleanly.  The rest of the documentation is quite dense.  I really wanted a 'Selenium in five minutes' page, but that's a different issue.

## Expected behavior

The code should compile.

## Environment

* OS: Windows 10 v2004
* Browser: Firefox
* Browser version: 80.0
* Visual Studio 2019 16.7.2

**Comment by harsha509** [comment]
Hi @rich-newman ,

Thank you for raising the issue. Yes code sample has issues (apologies for that)

As described in issue 
1. `SeleniumExtras`  is a nuget package that is not part of Selenium.
2.  ExpectedConditions are deprecated from Selenium 4.

I've updated the code sample which doesn't not use Selenium Extras and to wait for an element.

Code tested with Selenium aplha -5 nuget package.

Thanks,
Harsha

**Comment by rich-newman** [comment]
The new code works fine for me, thanks - that was an impressively quick turnaround!
