### ISSUE TITLE
Changing language in one sample should reflect across all code samples

### ISSUE THREAD

**Issue by ghost** [SeleniumHQ/seleniumhq.github.io#525]
## 🚀 Feature Proposal for the site or the documentation

When a user changes the (programming) language of a sample, these changes should reflect across all the samples on the current as well as other pages of the documentation too.

## Motivation

I was just reading the docs to get started with selenium for python, but all the code samples over there were for Java by default. It was very frustrating to change the language for each and every sample over there in the docs.Specifically, I have seen this kind of feature in the firebase and gcp documentation, where you change the language once and it reflects across all the samples on all the pages. So, I thought selenium should also have this.

## Example

I don't believe any example would be required.

I guess it can be solved by using something like cookies or HTML5 APIs like `localStorage` or `sessionStorage`

**Comment by pragapraga** [comment]
Shall I works on this? @jalaj-k @diemol ?

**Comment by diemol** [comment]
Sure, it is available for anyone to jump in and contribute!

**Comment by abhi-singhs** [comment]
Hi @diemol,

I have submitted a PR.
It would be awesome if you could review it!

Thanks.

**Comment by diemol** [comment]
I've left a comment for you at the PR.

**Comment by abhi-singhs** [comment]
@diemol Latest UI changes don't incorporate this feature. This issue should be reopened.
Happy to take it up.

**Comment by diemol** [comment]
@abhi2810, good idea.

Could you raise this in https://github.com/google/docsy/, and then when it is fixed there we can downstream it? (Assuming they would accept it).

**Comment by abhi-singhs** [comment]
Ok @diemol.
I will update here if they accept it.
