### ISSUE TITLE
Mention HTML unit in file downloads section

### ISSUE THREAD

**Issue by skyhirider** [SeleniumHQ/seleniumhq.github.io#533]
## 🚀 Feature Proposal for the site or the documentation

https://www.selenium.dev/documentation/en/worst_practices/file_downloads/

HTMLunit has a mature interface for file downloads ( see https://htmlunit.sourceforge.io/apidocs/com/gargoylesoftware/htmlunit/attachment/AttachmentHandler.html )

It could be mentioned as many are looking to use Selenium for web scraping and file downloads and copying a link is not always possible, especially with more complex JavaScript sites.

Not sure if there is a better way to handle file downloads via Selenium currently that to use HTMLunit, it's driver and native input streams

## Motivation

Took me quite a bit of time to figure out how to download files. Having at least a mention in the official docs would probably hell others save time.

## Example

HtmlUnit and its driver can be used to intercept files as input streams and add custom logic that will handle and save them.

See https://github.com/SeleniumHQ/htmlunit-driver and https://github.com/HtmlUnit/htmlunit/blob/master/src/main/java/com/gargoylesoftware/htmlunit/attachment/AttachmentHandler.java

**Comment by diemol** [comment]
@skyhirider, would you like to send us a pull request with that suggestion?

**Comment by skyhirider** [comment]
@diemol I can, but saw there are several language files in the repo.

Presume English is good enough?

Any guidelines on what to write and how?

**Comment by diemol** [comment]
@skyhirider please for all languages, check step 3 of this contribution guide
https://www.selenium.dev/documentation/en/contributing/
You can add the text in English and add a notification asking for translations.
