### ISSUE TITLE
FindElement by XPath returns incorrect value

### ISSUE THREAD

**Issue by krb-vci** [SeleniumHQ/seleniumhq.github.io#546]
## 🐛 Bug Report

When I execute a FindElement by XPath, looking for a specific attribute value, the element returned is not correct. In the case i found it was in a table, so I'll illustrate with 2 tables.

Here's what happens:

Start with 2 tables that both have children with the desired attribute:
`     <table id="first">          
        <tbody>
            <tr>
                <td private-label="ABC">
                    <div>First Text</div>
                </td>
            </tr>
        </tbody>
    </table>
   <table id="second">          
        <tbody>
            <tr>
                <td private-label="ABC">
                    <div>Second Text</div>
                </td>
            </tr>
        </tbody>
    </table>`

(you may need to inspect the element to see the html I typed above)

The following FindElement should return "Second Text" (I am using C# syntax here):
var tableElement = driver.FindElement(By.Id("second");
string elementText = tableElement.FindElement(By.XPath("//*[@private-label='ABC']")).Text;

Instead it returns "First Text".

Also - if I try:
var tableElement = driver.FindElement(By.Id("first");
int elementCount = tableElement.FindElements(By.XPath("//*[@private-label='ABC']")).Count;
I get a count of 2.

**Comment by jimevans** [comment]
This is entirely consistent with the XPath Specification. Using `//` without a context node qualifier means “search from the top of the document. This is true even if you are calling `FindElement` on an element object instead of the driver object. If you want to supply a context node when calling `IWebElement.FindElement`, use `.//` (note the period).

**Comment by krb-vci** [comment]
Thanks. It looks like I need a good, clear, tutorial or reference on the XPath specification.

Sent from my phone

On Oct 28, 2020, at 4:18 PM, jimevans <notifications@github.com<mailto:notifications@github.com>> wrote:


This is entirely consistent with the XPath Specification. Using // without a context node qualifier means “search from the top of the document. This is true even if you are calling FindElement on an element object instead of the driver object. If you want to supply a context node when calling IWebElement.FindElement, use .// (note the period).
