### ISSUE TITLE
Cross buttons should not appear by default in Search bar

### ISSUE THREAD

**Issue by pragapraga** [SeleniumHQ/seleniumhq.github.io#549]
## 🐛 Bug Report

![image](https://user-images.githubusercontent.com/6701828/97784167-986fc800-1bc2-11eb-87b4-ff3d4d132454.png)
Cross button should not be present by default, because it does nothing on clicking 😁 

## To Reproduce

1. Navigate to https://www.selenium.dev/documentation/en/getting_started/
![image](https://user-images.githubusercontent.com/6701828/97784103-17b0cc00-1bc2-11eb-8bde-6754629dc4f8.png)
2. You will find cross button in search bar.

Tell us the detailed steps to reproduce it:

## Expected behavior 
We should not have cross button in two cases
1.  By default when user comes for the very first time
2. When user clears the searched value in the search bar 

What do you expected to happen? How should have it worked?
We should populate the cross button if and only if the user enters something and on clicking, the user entered value should be cleared.

## Environment

* OS:  Pretty much everything (Windows, Linux and MAC)
* Browser: Pretty much everything
* Browser version: Pretty much everything

**Comment by diemol** [comment]
👋 @pragapraga, thank you for reporting this issue.

However, our documentation uses [Hugo Theme Learn](https://github.com/matcornic/hugo-theme-learn), so this should be reported there and see what the maintainer says.

Closing this as the potential fix should not be applied here but in the main theme, and then reused by Selenium.
