### ISSUE TITLE
Correct value must be populated in search bar when choosed from auto complete options

### ISSUE THREAD

**Issue by pragapraga** [SeleniumHQ/seleniumhq.github.io#550]
## 🐛 Bug Report

Correct value must be populated in search bar when choosed from auto complete options

## To Reproduce

How can we reproduce the issue you found? Please tell us how we can do that. 
Don't forget to add:

* Navigate to https://www.selenium.dev/documentation/en/
* Type `Praga` in search bar (You will have below auto complete values)
![image](https://user-images.githubusercontent.com/6701828/97784361-0072de00-1bc4-11eb-8b60-f1e7a44d6b26.png)
* Choose **Page object models**
* Value in the search bar is still - **Praga** as seen in below screenshot
![image](https://user-images.githubusercontent.com/6701828/97784395-534c9580-1bc4-11eb-8d65-ad983d83af47.png)

## Expected behavior
When user searches for a string (autocomplete populates some suggestions to the user) but when user chooses a value from the auto complete , the same should be populated in search bar.

## Environment

* OS:  iOS/Android/OSX/Linux/Windows - Pretty much everything
* Browser: Chrome? Safari? Firefox?  - Pretty much everything
* Browser version: - Pretty much every browser version

**Comment by diemol** [comment]
👋 @pragapraga, thank you for reporting this issue.

However, our documentation uses [Hugo Theme Learn](https://github.com/matcornic/hugo-theme-learn), so this should be reported there and see what the maintainer says.

Closing this as the potential fix should not be applied here but in the main theme, and then reused by Selenium.
