### ISSUE TITLE
API Documentation is no longer available

### ISSUE THREAD

**Issue by vringar** [SeleniumHQ/seleniumhq.github.io#554]
## 🐛 Bug Report

https://www.selenium.dev/selenium/docs/api/py/webdriver_remote/selenium.webdriver.remote.webelement.html
used to link to a python method on the remote webdriver. Now it returns a 404 and I can't find a way to access the
same information piece of information on the website.

## To Reproduce

Try to access the link posted above. I tried to access it with cURL as well as my browser and it returned the same error.

## Expected behavior

I expected to have access to the python documentation to explore the different classes and the methods defined on them.

**Comment by pawel-slowik** [comment]
The same issue affects links in the "Waits" section: 
1. go to https://www.selenium.dev/documentation/en/webdriver/waits/
2. search for `expected_conditions`
3. click the link for _Python’s selenium.webdriver.support.expected_conditions class_
4. https://seleniumhq.github.io/selenium/docs/api/py/webdriver_support/selenium.webdriver.support.expected_conditions.html?highlight=expected
5. 404

Note that the links used to work not so long ago, the Wayback Machine has copies from November 11 or November 12:
https://web.archive.org/web/20201111174737/https://www.selenium.dev/selenium/docs/api/py/webdriver_remote/selenium.webdriver.remote.webelement.html
https://web.archive.org/web/20201112001620/https://www.selenium.dev/selenium/docs/api/py/webdriver_support/selenium.webdriver.support.expected_conditions.html

----
Edit: the same for the Python API Docs link on the "Downloads" page:

1. go to https://www.selenium.dev/downloads/
2. scroll to the _Selenium Client & WebDriver Language Bindings_ table
3. click the _API Docs_ link in the Python row
4. https://www.selenium.dev/selenium/docs/api/py/index.html
5. 404

**Comment by diemol** [comment]
Fixed via https://github.com/SeleniumHQ/selenium/commit/d6bc900d7586a3c507ccdd901079df912ac49cb8
https://www.selenium.dev/selenium/docs/api/py/api.html
