### ISSUE TITLE
Missing sections in 'support classes'

### ISSUE THREAD

**Issue by boris779** [SeleniumHQ/seleniumhq.github.io#584]
## 🐛 Bug Report

The support class pages introduce some topics in the header but only ThreadGuard is descriped.

## To Reproduce

How can we reproduce the issue you found? Please tell us how we can do that. 
Don't forget to add:

* https://www.selenium.dev/documentation/en/webdriver/support_classes/

## Expected behavior

We should remove the undescripted topics until we have a guide with code examples

**Comment by diemol** [comment]
What else would you add, @boris779?

**Comment by diemol** [comment]
We have re-done the website and this section is not there anymore. In any case, we are always open to suggestions.
