### ISSUE TITLE
I can't find add_experimental_option(python selenium) in NodeJS

### ISSUE THREAD

**Issue by granrookey** [SeleniumHQ/seleniumhq.github.io#586]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see https://selenium.dev/support/

Hi.

I have a question about setting option to 'selenium-webdriver/chrome'.

I used option flag in python code like below.

`from selenium import webdriver

options = webdriver.ChromeOptions()
options.add_experimental_option('androidDeviceSocket', 'Terrace_devtools_remote')
options.add_experimental_option('androidExecName', 'Terrace')`

Then I have try to convert python to nodejs, but I can't found option matched with 'add_experimental_option' in python.

Try to set any other options like 'set, addArguments, or setUserPreferences'.
But I got always return code
'UnhandledPromiseRejectionWarning: WebDriverError: unknown error: Failed to get sockets matching: @weblayer_devtools_remote_'

So could you find the option or solution to set socket properly?

**Comment by vFire** [comment]
I can't find it either
