### ISSUE TITLE
Page loading strategy not working as per documentation for Python

### ISSUE THREAD

**Issue by praveendvd** [SeleniumHQ/seleniumhq.github.io#627]
## 🐛 Bug Report

https://www.selenium.dev/documentation/en/webdriver/page_loading_strategy/#:%7E:text=Defines%20the%20current%20session%27s%20page,loading%20takes%20lot%20of%20time

Explains 

```
options.page_load_strategy = 'none'
driver = webdriver.Chrome(options=options)

```

As code for setting page load strategy but it won't work the correct solution is

 ```
    options = ChromeOptions()

    options.set_capability("pageLoadStrategy", "none")
    driver = webdriver.Chrome(options=options)
```
## To Reproduce

```
options = ChromeOptions()
options.add_argument('--disable-blink-features=AutomationControlled')
options.page_load_strategy = 'none'
driver = webdriver.Chrome(options=options)




url = 'https://www.gm-trucks.com/'

print("hi")
```

## Expected behavior

It should print("hi") without waiting to page load

## Environment

* OS: Windows10
* Browser: Chrome
* Browser version: Chrome 88.0.4324.104 (Official Build) (64-bit)

**Comment by praveendvd** [comment]
Could I create a pull request for updating the docuemanttion

**Comment by harsha509** [comment]
Hi @praveendvd ,

Can you please let me know what version of py-selenium you're using.

Thanks,
Harsha.

**Comment by praveendvd** [comment]
> Hi @praveendvd ,
> 
> Can you please let me know what version of py-selenium you're using.
> 
> Thanks,
> Harsha.

3.141.0 ,  installed using pip install selenium

**Comment by harsha509** [comment]
Hi @praveendvd ,

All the code samples in the document are tested with latest Selenium4 alpha version. We encourage users to use driver options to set capabilities as we are deprecating desired capabilities.

Can you please try with latest alpha version of selenium 4 alpha and let me know.

Thank you!

**Comment by praveendvd** [comment]
@JS31096 

   Its working with v4

                    pip install selenium==4.0.0.a7

**Comment by harsha509** [comment]
Thank you!

Closing this as resolved.

FYI. All the other code samples in documentation are written with Selenium4 alpha versions. Please use alpha version to make use of code samples.

Apologies for inconvienece.
