### ISSUE TITLE
BrowserManipulation: TakeScreenshot: Javascript not working

### ISSUE THREAD

**Issue by luapi82** [SeleniumHQ/seleniumhq.github.io#628]
## 🐛 Bug Report

The screenshot is an empty PNG file of 9 bytes.

## To Reproduce

https://www.selenium.dev/documentation/en/webdriver/browser_manipulation/#takescreenshot
Running on fresh install of Ubuntu 20.04.2 LTS

- Copy and paste the JavaScript example into a new file index.js
- Modify the example.com to google.com
- Type 'node index.js' in the terminal window to run it

## Expected behavior

After running node index.js it should have taken a screenshot and saved it to image.png in the same location as the script. The image should be bigger than 9 bytes if we are to expect any data in it.

## Environment

* OS: Ubuntu 20.04.2 LTS
* Browser: Chrome or Firefox
* Browser version: Chrome Version 88.0.4324.146 (Official Build) (64-bit) | Firefox 85.0 (64-bit)

**Comment by harsha509** [comment]
Hi @luapi82 ,

Thanks for raising the issue. 

There was issue with code sample in JavaScript. I have fixed with this [commit ](https://github.com/SeleniumHQ/seleniumhq.github.io/commit/7efa397db38d8c0ba4c9ed1583fa7f2a053a78c0)

Thanks,
Harsha
