### ISSUE TITLE
Documentation request: Java version(s), Hub/Node networking

### ISSUE THREAD

**Issue by pwlandoll** [SeleniumHQ/seleniumhq.github.io#630]
## 🚀 Feature Proposal for the site or the documentation

It would be helpful for the documentation for Grid 4 to list a tested (or suggested) list of Java versions to use for running the server jar. The best I could find in the code or documentation was a version requirement for building, but nothing about running.

Additionally, it would also be helpful to have a more explicitly listed set of requirements for running the Grid 4 Hub and Node on different machines, in particular, networking requirements.

## Motivation

The motivation for this request is that some information that is missing from the documentation could be helpful for setting up Grid and testing the alpha and pre-release builds.

## Example

"Running `java -jar selenium-server-4.0.0-<selenium-version>.jar` requires JDK 11+ to run."

"The node must be able to reach the hub on ports A B C, and the hub must be able to reach the node on ports X Y Z. "

Thanks to the Selenium team for all your hard work :smile:

**Comment by diemol** [comment]
I think this comes from an error we made in an `alpha` release where we shipped some Java 11 code by mistake. We have made sure Grid and Java bindings require only Java 8 to work properly. So there is no need to add that comment in the docs.
