### ISSUE TITLE
Was passed main parameter '--config-help' but no main parameter was defined in your arg class

### ISSUE THREAD

**Issue by camohub** [SeleniumHQ/seleniumhq.github.io#651]
## 🐛 Bug Report

java -jar /opt/selenium-server/selenium-server-standalone-3.141.59.jar --config-help
Exception in thread "main" com.beust.jcommander.ParameterException: Was passed main parameter '--config-help' but no main parameter was defined in your arg class

## To Reproduce

According [documentation](https://www.selenium.dev/documentation/en/grid/grid_4/configuring_components/config_help/) I tired to call --config-help but I am getting error: Was passed main parameter '--config-help' but no main parameter was defined in your arg class

Ubuntu 20.04 
Selenium server 3.141.59

![Screenshot (360)](https://user-images.githubusercontent.com/8393426/111980189-3dedee80-8b06-11eb-87b7-6c9032971913.png)

Tell us the detailed steps to reproduce it:

This issue is related to another issue with -timeout option. According [documentation](https://www.selenium.dev/documentation/en/remote_webdriver/remote_webdriver_server/) I should run command like:
`java -jar selenium-server-standalone-{VERSION}.jar -role hub -timeout=60 -browserTimeout=60`  and this throws the same error. 

## Expected behavior

I need to set up Selenium grid timeouts. What is the right way to do it? Everything I tired from doc throws an error including --config-help.

## Environment

* OS: Ubuntu 20.04
* Browser: Chrome
* Browser version: 89

**Comment by diemol** [comment]
@camohub that is the documentation for Grid 4 and you are using Grid 3. Please head to https://www.selenium.dev/downloads/ to get the Grid 4 jar.

**Comment by camohub** [comment]
But this documentation https://www.selenium.dev/documentation/en/remote_webdriver/remote_webdriver_server/ uses {VERSION} placeholder. The main problem is with -timeout=20 -browserTimeout=60 options. 
Why did you send me to download page? V4 is beta and I have a running system. I dont want to upgrade from 3 to 4.

**Comment by diemol** [comment]
Thank you for pointing it out, @camohub!
That part of the docs is not valid anymore, I've moved it to the legacy section. Grid 3 documentation can be seen here https://www.selenium.dev/documentation/en/grid/grid_3/
If you need any help, please use the communication channels mentioned here https://www.selenium.dev/support/
