### ISSUE TITLE
Do we have the possible to attach IE Driver with version v3.150.1.1 on official site?

### ISSUE THREAD

**Issue by alaahong** [SeleniumHQ/seleniumhq.github.io#653]
### Please note that this issue tracker is not a help form and this issue will be closed.

The latest IE Driver version is v3.150.1.1 , but official site only provide link as 3.150.1.0
https://www.selenium.dev/downloads/

![image](https://user-images.githubusercontent.com/3264250/112591498-65fb8b80-8e3f-11eb-83b1-e67dd7e153f1.png)
![image](https://user-images.githubusercontent.com/3264250/112591521-6f84f380-8e3f-11eb-89f2-d9c3adebe4e7.png)

The latest version had been release more than 7 months, expect to download with latest version from official website.
Thanks.

**Comment by harsha509** [comment]
Hi @alaahong ,

Thanks for raising the issue.!

As per the instructions mentioned in IE changelog, The IE version number follows the below pattern

 "major.minor.build.revision" 

and changes in "revision" field (which is 3.150.1.1 (revision) in this case) indicates private releases checked into the pre-builts directory of the source tree and these revision releases are not generally made available in downloads page.

The users can get the private releases from [here](https://github.com/SeleniumHQ/selenium/tree/trunk/cpp/prebuilt).

Hope this helps!

Thanks,
Harsha

**Comment by alaahong** [comment]
@JS31096  Thanks for your following.
This helps me to understand the version mechanism. 

We're facing some JS execution issues with IE driver, the changelog means there are some JS enhancements on revision version. Raise this question just caused by our internal mirror only sync the binary from official artifactory not the github trunk. As can be seen, the build version had been stayed on 3.150.1 more than two years. 

You can ignore this question if there won't official release plan recently. To know the publish mechanism is fine too. Thanks.

**Comment by harsha509** [comment]
Thank you @alaahong, Will sure update the downloads link if there is any official IE release.
