### ISSUE TITLE
Ruby code snippets about Page loading strategy don't work

### ISSUE THREAD

**Issue by ixolius** [SeleniumHQ/seleniumhq.github.io#657]
## 🐛 Bug Report

The Ruby code snippets in the Site about Page loading strategy don't work in the current selenium-webdriver version. Based on the source code at Github, it seems like they will in Selenium 4.0, but I'm not 100% sure

## To Reproduce

Copy one of the following snippets and execute them with Ruby. They are all from https://www.selenium.dev/documentation/en/webdriver/page_loading_strategy/

```
require 'selenium-webdriver'
caps = Selenium::WebDriver::Remote::Capabilities.chrome
caps.page_load_strategy='normal'

driver = Selenium::WebDriver.for :chrome, :desired_capabilities => caps
driver.get('https://www.google.com')
```

```
require 'selenium-webdriver'
caps = Selenium::WebDriver::Remote::Capabilities.chrome
caps.page_load_strategy='eager'

driver = Selenium::WebDriver.for :chrome, :desired_capabilities => caps
driver.get('https://www.google.com')
```

```
require 'selenium-webdriver'
caps = Selenium::WebDriver::Remote::Capabilities.chrome
caps.page_load_strategy='none'

driver = Selenium::WebDriver.for :chrome, :desired_capabilities => caps
driver.get('https://www.google.com')
```

All scripts will fail with an error similar to: `selenium-fail.rb:3:in `<main>': undefined method `page_load_strategy=' for #<Selenium::WebDriver::Remote::Capabilities:0x000055f56181f860> (NoMethodError)`

## Expected behavior

The Site should load with the specified page loading strategy.

## Environment

* OS: Arch Linux (64 bit)
* Browser: All browsers seem to be affected
* Browser version: All versions seem to be affected
* Ruby version: `ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]`
* selenium version: 3.142.7

## Proposal to fix:

If the snippets run without error, I suggest adding a comment in the snippet, specifying that it won't work with the "normal" version, but only with 4.0.0 and removing the comment once 4.0.0 is officially out. I would submit the corresponding pull requests, if necessary

**Comment by harsha509** [comment]
HI @ixolius ,

Thank you for checking out the code samples for Selenium.

FYI All the code samples documented are tested with Selenium 4 Alpha and beta versions. Can you try with latest Selenium beta release ?

**Comment by diemol** [comment]
Closing as we did not get any replies.
