### ISSUE TITLE
Exception while fetching data - java.lang.reflect.InvocationTargetException Exception

### ISSUE THREAD

**Issue by shmikkil** [SeleniumHQ/seleniumhq.github.io#676]
## 💬 Questions and Help
Applied SSL Certs and started receiving the exceptions when trying to register the nodes when using Selenium Grid 4 - Beta 3. There has been an error while loading the Nodes from the Grid.
Exception while fetching data (/nodesInfo/nodes) : java.lang.reflect.InvocationTargetException

Selenium Grid
Exception while fetching data (/grid/totalSlots) : java.lang.reflect.InvocationTargetException Exception while fetching data (/grid/nodeCount) : java.lang.reflect.InvocationTargetException Exception while fetching data (/grid/maxSession) : java.lang.reflect.InvocationTargetException Exception while fetching data (/grid/sessionCount) : java.lang.reflect.InvocationTargetException

Is this a common error? Could someone please assist? Thank You!
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see https://selenium.dev/support/

**Comment by diemol** [comment]
Please create a complete bug report at https://github.com/SeleniumHQ/selenium
