### ISSUE TITLE
driver.switch_to.new_window can't effective

### ISSUE THREAD

**Issue by zuiyuewentian** [SeleniumHQ/seleniumhq.github.io#688]
driver.switch_to.new_window('tab')

I can't use this code create a new tab or windows .

**Comment by harsha509** [comment]
Hi @zuiyuewentian,

Could you please provide more info on this?

Language bindings:
Version:

Sample code to reproduce this issue http://sscce.org/
Note: The feature only works with Selenium 4 beta versions. Please download the latest beta and try again!

**Comment by harsha509** [comment]
Closing this as we didn't hear back from the OP.

Please raise an issue in [here ](https://github.com/SeleniumHQ/selenium/issues/new/choose) if you still see any issue. 
Hope this helps.

Thanks,
Harsha
