### ISSUE TITLE
left Chrome.exe full of memory 

### ISSUE THREAD

**Issue by z632896862** [SeleniumHQ/seleniumhq.github.io#692]
## 🐛 Bug Report

When I use webDrive for Chrome, there will be some left in my memory. When I use it many times,there will be many proessce named chorme.exe. Every proess will cust 30-50K. Finally they will full of my memory. I have try use drive.quit() to close it,but doesn‘t work

## To Reproduce

How can we reproduce the issue you found? Please tell us how we can do that. 
Don't forget to add:

Use webdriver in cycle, wait for some time. We can find the memory get fulled. We can't see what full of your memory in the taskmanager, even use 'tasklist' in cmd. However,you can use Rammap to find them. Follow is downlond link:
<https://docs.microsoft.com/zh-cn/sysinternals/downloads/rammap>

Tell us the detailed steps to reproduce it:

## Expected behavior

When I use drive.quit(), Chrome should compeletly close in my system.

## Environment

* OS: Windows Server 2019 Datacenter 1809 17763.158
* Browser: Chrome
* Browser version:  90.0.4430.212

**Comment by diemol** [comment]
This repository accepts issues related to the Selenium documentation, if you are having an issue/bug that can be reproduced with a script, please create an issue [here](https://github.com/SeleniumHQ/selenium) and fill out all the information requested on the template.
