### ISSUE TITLE
Misleading/wrong code snippet in docu for "webdriver/driver requirements"

### ISSUE THREAD

**Issue by Haifischbecken** [SeleniumHQ/seleniumhq.github.io#698]
## 🐛 Bug Report

In the Docu under ["webdriver/driver requirements"](https://www.selenium.dev/documentation/en/webdriver/driver_requirements/#firefox) there are two code snipptes. The JS version of the second supposedly shows how to select the **wedriver** binary manually, but the `setBinary` option is used which does set the **browser** binary.
This have been an [issue](https://github.com/SeleniumHQ/selenium/issues/5673) before although not directly related to the documentation.

## To Reproduce

Running the following in node.js does not load the Geckodriver.
```
import firefox from 'selenium-webdriver/firefox.js';
import { Builder } from 'selenium-webdriver';

options = new firefox.Options().setBinary('C:\\util\\geckodriver-v0.29.1-win64\\geckodriver.exe');

(async function myFunction() {
    let driver = await new Builder()
        .forBrowser('firefox')
        .setFirefoxOptions(options)
        .build();
    await driver.get('https://selenium.dev');
})();
```

## Expected behavior

The Geckodriver should be loaded, this code does this correctly:
```
import firefox from 'selenium-webdriver/firefox.js';
import { Builder } from 'selenium-webdriver';

const serviceBuilder = new firefox.ServiceBuilder(
    'C:\\util\\geckodriver-v0.29.1-win64\\geckodriver.exe'
);

(async function myFunction() {
    let driver = await new Builder()
        .forBrowser('firefox')
        .setFirefoxService(serviceBuilder)
        .build();
    await driver.get('https://selenium.dev');

})();
```

## Environment

* OS: Win10
* Browser: Firefox 88.0.1
* npm 6.14.8
* node v14.15.1
* selenium-webdriver 4.0.0-beta.3

**Comment by diemol** [comment]
Thanks for reporting this, @Haifischbecken. Would you like to send a PR to fix the docs?

**Comment by Haifischbecken** [comment]
Yes, @diemol I just created a PR, I am testing the fork locally and remove the "WIP" once I'm done.

**Comment by Haifischbecken** [comment]
Changes are done on my side.
