### ISSUE TITLE
Cannot get value from HTML input in Chrome 91

### ISSUE THREAD

**Issue by andyvanhelsing** [SeleniumHQ/seleniumhq.github.io#703]
## 🐛 Bug Report

Cannot get value from HTML input

## To Reproduce

`driver.findElement(By.id("my-input")).getAttribute("value");`

Previously returned the value in the input element, now returns null 

## Environment

* OS: Windows +  Linux
* Browser: Chrome
* Browser version: 91.0.4472.77

**Comment by diemol** [comment]
Please check https://groups.google.com/g/chromedriver-users/c/L82UzBKy58Q?pli=1

**Comment by andyvanhelsing** [comment]
@diemol thanks for the quick response and link to the forum (this seems like really good resource) -- I am using Selenium in java, is there an equivalent to the get_property() method mentioned in the thread you sent?

**Comment by diemol** [comment]
Apologies, I missed this reply. I think it is `.getDomProperty()` in recent Selenium betas. For more questions, please join us in our Slack/IRC channel https://www.selenium.dev/support/
