### ISSUE TITLE
Relative Locator withTagName() method not working by using latest selenium-java maven repository

### ISSUE THREAD

**Issue by manodipmachinesense** [SeleniumHQ/seleniumhq.github.io#726]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see https://selenium.dev/support/

Hi, 

I have used latest selenium version i.e. 4.0.0-beta-4

<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-java</artifactId>
    <version>4.0.0-beta-4</version>
</dependency>

But this version not support the RelativeLocator withTagName() method. So when I want to use this it throw me an error, but when I downgrade my version its works as expected.

Please look into it, so that we can use this functionality as latest version as well.

**Comment by harsha509** [comment]
Hi @manodipmachinesense,

Relative locator in Java bindings now `starts with any locator, not just tag name`

This change was landed in Selenium4 beta 3, it is also mentioned in changelog in [here ](https://github.com/SeleniumHQ/selenium/blob/trunk/java/CHANGELOG)

The code samples in the documents are updated for the same. You can take reference from [here ](https://www.selenium.dev/documentation/en/webdriver/locating_elements/#above)

Hope this helps!

Thanks,
Harsha

**Comment by manodipmachinesense** [comment]
Hi @harsha509 ,

Thanks for your information, now it's working as expected....
One request from my side in selenium.dev documentation section the link you have shared above, there import of Relative locator need to modify, Please have a look.

![selenium](https://user-images.githubusercontent.com/48321314/125248608-defcf100-e311-11eb-82ec-5185af965e9e.png)

**Comment by harsha509** [comment]
Hi @manodipmachinesense,

Thanks for pointing it out. 

I have updated it!
