### ISSUE TITLE
Removal of multilingual feature

### ISSUE THREAD

**Issue by Catalin-Negru** [SeleniumHQ/seleniumhq.github.io#727]
Hi. 
_**I'm Catalin Negru and I'm a tester, and this is the issue I want to address:**_
____________

**MOTIVATION:**
- I use Selenium a lot at work.
- I read the entire documentation from here.
- Everyone who worked at Selenium deserves appreciation.
- I want to help.

**SITUATION:**
- There are a lot of things that can be improved, and sure many of us have ideas.
- Everybody understands the scope of having a multilingual website. However...
  - Most people who are in the IT industry know basic English; if they do not, they are in the wrong business.
  - the code itself is in English.

**PROBLEM:**
- Documentation can be changed/updated only if that change is made on all corresponding pages in the languages available.
**&**
- Most of us - although it is safe to say all of us - do not know all the languages used/required for a valid update of the documentation.
		-->> Accordingly, **improvements cannot be put into practice and multilingual feature is an obstacle for evolution and improvement.**

**PROPOSED SOLUTION:**
- **Remove the multilingual feature of this documentation.**
____________

_**All the best.**_

P.S.: _I know this sounds radical..._

**Comment by diemol** [comment]
👋 @Catalin-Negru, thank you for creating this issue.

We are working on improving the way contributions can be made to the docs and website. However, our [contribution guidelines](https://www.selenium.dev/documentation/en/contributing/) mention what to do in the cases you refer in your comments.

On the other hand, assuming that everyone must speak English is quite radical and basically limits the users who did not have the privilege to learn this language. In addition, if we were to take a decision like this one, it would be based on metrics and data after measuring the traffic in the site , and not based on assumptions. 

We will keep this issue open as a reason to improve the contribution flow, but not as a reason to remove the docs translations.

**Comment by Catalin-Negru** [comment]
@diemol, thank you for the answer.
I missed that last point from Step 3 described on the _contribution guidelines_ page.
Best.

**Comment by Catalin-Negru** [comment]
@diemol, hi.
_I'm writing this off-topic here because I do not know how/where to ask you in other way._

**I think that the website should have a table of contents.**
But, given that this requires quite some work, I want to know beforehand if it would be accepted.
What do you say?

Best.

**Comment by diemol** [comment]
You can always jump to our Slack/IRC channel to ask questions, links can be seen at https://www.selenium.dev/support/

So, what do you mean by a table of contents?
Also, we are almost done redoing our site, here is the preview https://deploy-preview-730--jovial-austin-42fe02.netlify.app/

**Comment by diemol** [comment]
We just made a few changes addressing this https://www.selenium.dev/blog/2021/docs-translations/
