### ISSUE TITLE
Using selenium capabilities to create electron-like desktop applications in python

### ISSUE THREAD

**Issue by muhammad-bassiouni** [SeleniumHQ/seleniumhq.github.io#733]
I was wondering if I can create electron-like desktop applications in python using selenium. considering that selenium get full control of the browser by executing js code and get the function return back, and so this gives the ability to make like python_js bridge.
I have tried using CEF python, it is great but lacks some functionalities. I see that the combination of both selenium and cef will be great.

my question: is it possible to make desktop applications in python using selenium?

**Comment by harsha509** [comment]
Hi,

This issue tracker is only for Selenium documentation.

This looks like a question that is best suitable in [here](https://github.com/SeleniumHQ/selenium/issues/new/choose) with the template 'Questions / Help'.

Hope this helps!

Thanks,
Harsha
