### ISSUE TITLE
Search field doesn't work

### ISSUE THREAD

**Issue by egor-andrushko** [SeleniumHQ/seleniumhq.github.io#736]
## 🐛 Bug Report

No results displayed after pressing the bttn "Enter" when user is trying to search by something
**Error "Uncaught TypeError: Cannot read property '_index' of undefined" displayed in Console**

## To Reproduce
* https://www.selenium.dev/documentation/getting_started/
* ![image](https://user-images.githubusercontent.com/38658386/128633155-edac082d-8cfc-480a-be39-51a9db8bb9a9.png)

**Steps to reproduce:**
1. Open the link
2. Input text in search bar (ex. "page object")
3. Press the "Enter"

## Expected behavior
Results of the search should be displayed (or screen that nothing was found) after pressing the bttn "Enter" with non-empty search field

## Environment

* OS: Windows 10
* Browser: Chrome 
* Browser version: 92.0.4515.131 (Official Build) (64-bit)

**Comment by diemol** [comment]
At some point I was able to reproduce, but I wanted to have a look today and I cannot anymore. Are you still able to reproduce the issue?

**Comment by egor-andrushko** [comment]
I can't reproduce it anymore
