### ISSUE TITLE
Possibility to come back to the old design

### ISSUE THREAD

**Issue by jargonised** [SeleniumHQ/seleniumhq.github.io#738]
## 🚀 Feature Proposal for the site or the documentation

Option to choose new or old design.

## Motivation

I started using documentation some time ago. Style was clear and easy for reading, modern. It was really nice. Now, it's all bright and the code in frames isn't as pleasant to read as it was.

**Comment by diemol** [comment]
What exactly do you find bright? The code samples or the text background?

These are the available styles for code markup https://xyproto.github.io/splash/docs/all.html

**Comment by diemol** [comment]
Closing as we did not get more feedback.
