### ISSUE TITLE
WebDriver Bidi APIs Java example does not work

### ISSUE THREAD

**Issue by abhi-singhs** [SeleniumHQ/seleniumhq.github.io#740]
## 💬 Questions and Help
The Java Bidi APIs example doesn't work because it is implemented with Firefox and FirefoxDriver doesn't implement the HasLogEvents interface.
https://www.selenium.dev/documentation/webdriver/bidi_apis/
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see https://selenium.dev/support/

**Comment by diemol** [comment]
Please create an issue in the Selenium repo with all the fields from the template filled out.
