### ISSUE TITLE
Scrolling on mobile doesn't work for a few seconds when the page opens

### ISSUE THREAD

**Issue by prafair** [SeleniumHQ/seleniumhq.github.io#742]
## 🐛 Bug Report

Scrolling on mobile doesn't work for a few seconds when the page opens.

## To Reproduce

https://www.selenium.dev/
Open a page and scroll down.

https://user-images.githubusercontent.com/15040493/129101432-9b7b8396-4142-425b-826f-e5eed799f835.mp4

## Expected behavior

The page should scroll from the first seconds.

## Environment

* OS: Android
* Browser: Chrome
* Browser version: 92.0.4515.131

**Comment by diemol** [comment]
This might be an issue with the offline search, when I load the page I can see it takes a while until it loads and interacting with the website is laggy. Probably we need to have a look and switch to Algolia.

**Comment by diemol** [comment]
Hm, seems it is not related to the search, but rather to a download that blocks the main thread. I am having a look soon.

**Comment by diemol** [comment]
So, it is actually related to the offiline search, I am disabling search for a while until we find an alternative, https://github.com/SeleniumHQ/seleniumhq.github.io/pull/749.

**Comment by diemol** [comment]
Ok, this is fixed now. Adding a new search engine will be treated in a different PR.
