### ISSUE TITLE
Switch code example for all in a page

### ISSUE THREAD

**Issue by sbui2** [SeleniumHQ/seleniumhq.github.io#744]
## 🚀 Feature Proposal for the site or the documentation

Switch to one programing language in any example, all other example should be switched to same language too.

## Example

For every help page, we can see in each example, there's some tabs for each programming language.
If I'm using C#, I'll always looking for code of C#, I don't care other language.
I suggest that If I switch to C# language for 1 example, other examples in same page should switch to C# so that
it save time for me to do so.

**Comment by diemol** [comment]
This is being [worked upstream](https://github.com/google/docsy/issues/654) by @abhi2810 (thanks!)

When it gets accepted, we will downstream it.

**Comment by abhi-singhs** [comment]
@diemol Got the PR merged. I think we can pull it downstream from docsy.

**Comment by diemol** [comment]
Thanks for the heads up, I just updated Docsy and deployed the site again. Thank you for working on this, @abhi2810!
