### ISSUE TITLE
Stuck in this link: https://www.selenium.dev/documentation/getting_started/installing_browser_drivers/

### ISSUE THREAD

**Issue by wujr5** [SeleniumHQ/seleniumhq.github.io#750]
## 🐛 Bug Report

![image](https://user-images.githubusercontent.com/7693440/130550046-c1d28d37-196c-47a0-88a7-e5b814034f1a.png)

As shown in figure above, I visit this link: https://www.selenium.dev/documentation/getting_started/installing_browser_drivers/ , and I click `JavaScript` tab, the browser stuck and nothing happens. A few minutes later, the browser prompts me the figure below.

![image](https://user-images.githubusercontent.com/7693440/130550197-6327c96d-399c-4ca4-83ef-47dadb6055c3.png)

## Environment

* OS: MacOS Big Sur 11.5.2 (20G95)
* Browser: Chrome
* Browser version: 92.0.4515.159 Stable (x86_64)

> Sorry for the poor english, I am Chinese, non-native English speaker

**Comment by diemol** [comment]
Thank you for reporting this, it seems this PR is causing the page to block itself 
https://github.com/google/docsy/commit/8b253ac0b65447502f259f11fc888a0363da34ee

I am trying out a local fix and I will send a PR upstream.

**Comment by diemol** [comment]
I created a PR to fix this https://github.com/google/docsy/pull/669

**Comment by diemol** [comment]
@wujr5, no need to apologise! I am not a native speaker either, we are all here learning 🤗

**Comment by wujr5** [comment]
@diemol Thanks for your work.

It seems that you fixed the 'switch tab' problem, but I still stuck in this link:  https://www.selenium.dev/documentation/getting_started/installing_browser_drivers/, the same as this issue #751

**Comment by diemol** [comment]
Yes, the tabs are the ones causing the issue. Our website uses Docsy, a Hugo theme. I sent the PR to Docsy directly and when it gets merged then I can update our website to get the fix.

**Comment by diemol** [comment]
I went back to a [previous commit](https://github.com/SeleniumHQ/seleniumhq.github.io/commit/efd51c2e509e678277b6128c0c70a024a4b054f1) to avoid this issue, so we can close this.
