### ISSUE TITLE
[🐛 Bug]: C# get chrome-version:81.0.4044.138 x64 Session Storage Error

### ISSUE THREAD

**Issue by 312855935** [SeleniumHQ/seleniumhq.github.io#813]
### What happened?

**use Selenium C# get the chrome-version:81.0.4044.138 x64 Session Storage，Exception:Driver doest not support manipulating HTML5 web storage. Use the HasWebStrorage property to test the driver capability**

now:
`
RemoteWebDriver remote=(RemoteWebDriver )selenium;
string vuex=remote.WebStorage.SessionStorage.getItem("vuex");
//the code can use Other Chrome Version:Ex  62  75 
`

### What browsers and operating systems are you seeing the problem on?

chrome-version:81.0.4044.138 x64
Exception:Driver doest not support manipulating HTML5 web storage. Use the HasWebStrorage property to test the driver capability

**Comment by diemol** [comment]
This is the repository for the website and documentation, for core Selenium issues, please open one here https://github.com/SeleniumHQ/selenium/issues/new/choose
