### ISSUE TITLE
[🌍 Translation]: IDE Documentation

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/seleniumhq.github.io#864]
### What needs to be translated

#844 needs translating.

1. Update the placeholder document with translation
2. Remove the `needsTranslation` metadata at the top of the file
3. Commit update and avoid referring to this PR in your commit message, so the issue doesn't automatically close before other translations have been updated
4. Push update directly to `dev`
5. Remove the label from this Issue
6. Last person to remove their label can close the issue

**Comment by kzhirata** [comment]
Translated to Japanese by #893

**Comment by alaahong** [comment]
Translated to Chinese by #911

**Comment by diemol** [comment]
@luisfcorreia do you know someone who wants to help us contribute to this?

**Comment by luisfcorreia** [comment]
Translated via #1222
