### ISSUE TITLE
[🌍 Translation]: Installing Browser Drivers Page

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/seleniumhq.github.io#869]
### What needs to be translated

#825 needs translating. This is a complete content update for working with browser drivers.

**Comment by alaahong** [comment]
Completed zh-cn by #882

**Comment by kzhirata** [comment]
Translated to Japanese by #887

**Comment by harsha509** [comment]
pt-br translation is done with commit https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1046 !

**Comment by harsha509** [comment]
Closing this as all translations are landed!
