### ISSUE TITLE
[🌍 Translation]: Browser Page

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/seleniumhq.github.io#870]
### What needs to be translated

#865 Splits content from one file into multiple. New page titles might need updating.

**Comment by alaahong** [comment]
Completed zh-cn by #882

**Comment by kzhirata** [comment]
Translated to Japanese by #887

**Comment by diemol** [comment]
@luisfcorreia do you know someone who wants to help us contribute to this?
