### ISSUE TITLE
[🐛 Bug]:  ref link display in pageinfo incorrectly

### ISSUE THREAD

**Issue by alaahong** [SeleniumHQ/seleniumhq.github.io#886]
### What happened?

All languages of "chrome_devtools" are meeting such issue.

The ref link is fine in content, but can't display well in pageinfo, source code is as below
`    [WebDriver Bidi APIs]({{< ref "bidi_api.md" >}} `
Screenshot on en page https://www.selenium.dev/documentation/webdriver/bidirectional/chrome_devtools/
![image](https://user-images.githubusercontent.com/3264250/146632186-2bfe195c-3110-4efe-9d72-6aa155550e5f.png)

I try to add ")" in the end, but still not work well.
![image](https://user-images.githubusercontent.com/3264250/146632249-0fc5797b-22ed-465e-a252-14a5e8e1b759.png)

Can't find relative example in Hugo document https://gohugo.io/content-management/cross-references/
Please consider a way to show this as expected.

### What browsers and operating systems are you seeing the problem on?

Win 10
Edge  96.0.1054.57

**Comment by diemol** [comment]
Thank you for reporting this, @alaahong!
