### ISSUE TITLE
[🐛 Bug]: typo in documentation/webdriver/elements/locators/ page

### ISSUE THREAD

**Issue by romesh33** [SeleniumHQ/seleniumhq.github.io#889]
### What happened?

There is a typo 'loctor' instead of 'locator' in the text on the page https://www.selenium.dev/documentation/webdriver/elements/locators/#how-it-works:

> ...but you could swap the ⚠️  loctor ⚠️  in the final method with an element object and it will work the same.

### What browsers and operating systems are you seeing the problem on?

Chrome 96.0.4664.110
Mac OS Monterey 12.1

**Comment by diemol** [comment]
Good catch! Would you like to send a pull request to fix it?

**Comment by harsha509** [comment]
Thank you for raising the issue @romesh33 !

Fixed with this  [commit](https://github.com/SeleniumHQ/seleniumhq.github.io/commit/6f0eafc28a1e1a35e35f6def0991a72693e69af5) !
