### ISSUE TITLE
[🐛 Bug]: linkText and partialLinkText in locators page

### ISSUE THREAD

**Issue by alaahong** [SeleniumHQ/seleniumhq.github.io#891]
### What happened?

As the introduction of https://www.selenium.dev/documentation/test_practices/encouraged/locators/
“Selection strategies based on linkText and partialLinkText have drawbacks in that they only work on link elements. **Additionally, they call down to XPath selectors internally in WebDriver.**”

Are they actually calling as XPath?

Just check the [W3C spec](https://www.w3.org/TR/webdriver/#link-text), I'm not sure the XPath will work as given 4 steps.
And meanwhile, I can't find out further evidence on the XPath calling .
In Java, the LinkText and ParticalLinkText is same as tagName by BaseW3CLocator.

So is that correct as document mentioned? 

Please correct me if this is not the right place to confirm.
Thanks. 

### What browsers and operating systems are you seeing the problem on?

win 10
edge

**Comment by diemol** [comment]
@titusfortner, do you know?

**Comment by alaahong** [comment]
Thanks diego's following.

Just double check the [JavaScript implmentation](https://github.com/SeleniumHQ/selenium/blob/9c748fa68778f5bede17cb16135d3f801deab299/third_party/closure/goog/dom/dom.js#L311), the linkText is implemented by  querySelectorAll a the W3C spec mentioned. 

I can't find out the detail behind of linkText and particalLinkText in Java, but seems no reason to make them based on XPath as locators page said.

**Comment by titusfortner** [comment]
Yes, I think that reference is based off of the original find element atoms that were used when Selenium maintained all of the drivers in our codebase. Now the implementation depends on whatever the browser vendor decides to do.

A lot of things in the test practices section can/should get overhauled/updated/deleted :)

**Comment by diemol** [comment]
Closed via #947
