### ISSUE TITLE
https://www.selenium.dev/selenium/docs/api/py/webdriver_support/selenium.webdriver.support.expected_conditions.html?highlight=expected[🐛 Bug]: 

### ISSUE THREAD

**Issue by sunonmountain** [SeleniumHQ/seleniumhq.github.io#896]
### What happened?

Hello,

The following link in (https://www.selenium.dev/documentation/) has had its contents [removed.](https://www.selenium.dev/selenium/docs/api/py/webdriver_support/selenium.webdriver.support.expected_conditions.html?)
highlight=expected

The link above does work but the section detailing the various python expected conditions has been removed
![Screenshot 2021-12-21 074958](https://user-images.githubusercontent.com/53342604/146891947-60f3e10a-05e3-4721-8e2b-10a5d1ea3032.png)
.
I have found this content to be a useful reference in the past. It would be great if it were put back or an alternative link . Also the sections for webdriver.support have also been removed.
(provided.[https://www.selenium.dev/selenium/docs/api/py/api.html](url))
![Screenshot 2021-12-21 075820](https://user-images.githubusercontent.com/53342604/146892864-1eb2b3db-6ff2-4998-913d-a411db9344ea.png)

Kind regards
Gavin Vadivalloo

### What browsers and operating systems are you seeing the problem on?

Chrome Version 96.0.4664.110 (Official Build) (64-bit) on Windows 10

**Comment by diemol** [comment]
This has been already fixed.
