### ISSUE TITLE
[🌍 Translation]: First Script Page

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/seleniumhq.github.io#903]
### What needs to be translated

PR #875 
The main page I deleted a bunch of code, mostly just needs a link to the new page
The first_script pages needs a full translation

**Comment by alaahong** [comment]
PR #905  for this.

**Comment by kzhirata** [comment]
PR #909 for this.

**Comment by harsha509** [comment]
PT-BR translation is landed with commit https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1044!

**Comment by harsha509** [comment]
Closing as all pages are translated!
