### ISSUE TITLE
[🚀 Feature]: Add Multi-touch documentation

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/seleniumhq.github.io#906]
### Feature and motivation

From https://github.com/SeleniumHQ/selenium/issues/10049

Add description / examples for using 2 pointer inputs and dragging in different directions, etc

**Comment by diemol** [comment]
@titusfortner is there a place where we can get this information?

**Comment by ollie-iterators** [comment]
This is the URL that I mentioned in the original issue: https://www.lambdatest.com/blog/selenium4-w3c-webdriver-protocol/

**Comment by ollie-iterators** [comment]
This is where the Actions API is described: https://w3c.github.io/webdriver/#actions

**Comment by titusfortner** [comment]
After spending a lot more time in Actions class, I don't think it's possible with what we have and that we need to implement this first — https://github.com/SeleniumHQ/selenium/issues/10808

I'd like for this to be part of our next Test Automation Summit, since whatever we do should follow to some extent whatever Appium is trying to do.

As such, I'm going to close this issue as not something we can accomplish at this time. We'll add the docs as part of the new feature.
