### ISSUE TITLE
[🐛 Bug]: First script example

### ISSUE THREAD

**Issue by ajl275** [SeleniumHQ/seleniumhq.github.io#922]
### What happened?

On the page: [https://www.selenium.dev/documentation/webdriver/getting_started/first_script/](url)
The complete script example in Java at the bottom of the page does not compile due to two errors, there is a missing semicolon on the line: `WebElement searchButton = driver.findElement(By.name("btnK"))` and a missing import statement: `import org.openqa.selenium.WebElement; `

### What browsers and operating systems are you seeing the problem on?

Chrome 97.0.4692.71
Windows 10

**Comment by diemol** [comment]
Would you like to send a pull request to help us fix it?
Please check https://www.selenium.dev/documentation/about/contributing/

**Comment by ajl275** [comment]
Sure, I can do that!

**Comment by titusfortner** [comment]
Oops, missed that you were making a PR and fixed it based on just reading the issue. I thought I'd addressed this in the PR that got merged this morning, but I didn't.

Thanks for raising the issue, and we would welcome any future contributions you'd like to make!
