### ISSUE TITLE
[🐛 Bug]: Documentation is Wrong

### ISSUE THREAD

**Issue by JasonHagler** [SeleniumHQ/seleniumhq.github.io#923]
### What happened?

The Documentation says to use find_element(By.*) but Python throws an error saying that By is not defined.

### What browsers and operating systems are you seeing the problem on?

Python 3.9

**Comment by diemol** [comment]
Where do you see that? Can you share the link?

**Comment by dominikb1888** [comment]
Here: https://github.com/SeleniumHQ/seleniumhq.github.io/blob/dev/examples/python/tests/getting_started/test_first_script.py

**Comment by harsha509** [comment]
HI @dominikb1888,

I have executed the code sample with new setup and I didn't see any issue executing it!

Could you please let us know if you're still facing this issue. ?

**Comment by dominikb1888** [comment]
@harsha509 I cannot exactly recall the setting anymore. I just remember, I had the same error message. The working code I ended up using looks equivalent to the example shown. I guess this must have been a package management issue.

**Comment by diemol** [comment]
OK, thanks for letting us know, @dominikb1888. Closing this issue then.
