### ISSUE TITLE
[🐛 Bug]: Outdated documentation: "Fresh browser per test"

### ISSUE THREAD

**Issue by palbr** [SeleniumHQ/seleniumhq.github.io#927]
### What happened?

The documentation at https://www.selenium.dev/documentation/test_practices/encouraged/fresh_browser_per_test/ is recommending to start a new `FirefoxDriver` with a certain `FirefoxProfile`.

If I understand the API correct, Selenium 4.1.1 does not support creating a new `FirefoxDriver` with a `FirefoxProfile` as parameter.
See [Selenium Java API for FirefoxDriver](https://www.selenium.dev/selenium/docs/api/java/org/openqa/selenium/firefox/FirefoxDriver.html).

### How can we reproduce the issue?

```shell
Visit https://www.selenium.dev/documentation/test_practices/encouraged/fresh_browser_per_test/ and compare to https://www.selenium.dev/selenium/docs/api/java/org/openqa/selenium/firefox/FirefoxDriver.html

Or copy this code snipped in your IDE:

FirefoxProfile profile = new FirefoxProfile(new File("pathToFirefoxProfile"));
WebDriver driver = new FirefoxDriver(profile);
```

### Relevant log output

```shell
IDE is telling:
"Cannot resolve constructor 'FirefoxDriver(org.openqa.selenium.firefox.FirefoxProfile)'"
```

### Operating System

Windows 10

### Selenium version

Java 4.1.1

### What are the browser(s) and version(s) where you see this issue?

does not matter

### What are the browser driver(s) and version(s) where you see this issue?

does not matter

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
Thanks for raising the issue, would you like to make a pull request with your solution?
Contributions guide is here — https://www.selenium.dev/documentation/about/contributing/

**Comment by palbr** [comment]
I think, setting up a development environment for Selenium (git clone, git fork, installing hugo, ...) and reading hugo manuals will take more time than I can afford at the moment. And comparing this time consumption against the "real work" of changing two line in the documentation seems to me like a very bad ratio.

**Comment by diemol** [comment]
Strange. Given that you have already contributed in the past, we thought it'd be a nice way to keep giving back to this project.

But ok, we will find a way to make contributions more simple then. Thank you for the feedback.

**Comment by titusfortner** [comment]
Installing Hugo and previewing changes isn't strictly required, though we would appreciate any code updates being made in all 4 of the language files.

And, yes, our hope is that you would continue to help us make the documentation better, which would make the forking/cloning more worth your time. But thank you for raising this issue, either way.

**Comment by jags14385** [comment]
@diemol  Can I pick this issue ?
