### ISSUE TITLE
[🚀 Feature]: Execute Example Code 

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/seleniumhq.github.io#934]
### Feature and motivation

GitHub Actions should execute the example code that has been added.

We should also add a bullet to release process to update the Selenium requirements in each project on every new release.

**Comment by diemol** [comment]
This was implemented by @bonigarcia and I just updated the Wiki.

@titusfortner can you please if the Ruby instructions are correct?
https://github.com/SeleniumHQ/selenium/wiki/Releasing-Selenium#ruby
