### ISSUE TITLE
Missing Documentation.[🐛 Bug]: 

### ISSUE THREAD

**Issue by KyleC69** [SeleniumHQ/seleniumhq.github.io#944]
### What happened?

This page displays link to Advanced configuration options.

https://www.selenium.dev/documentation/webdriver/getting_started/install_drivers/

This page displays no information at all. Advanced configuration options/parameters should be a must have. There are many scenarios that are not covered in any of your documentation and forces users to hunt on the internet for a possible solution. In my humble opinion, software of this caliber should have better documentation and examples. Too much time is wasted problem solving.

### What browsers and operating systems are you seeing the problem on?

Using Ubuntu 20.04/ VS code-insiders. MS Edge Beta

**Comment by diemol** [comment]
Which content are you missing? The page has now content but not sure what the content was when you checked it.

> In my humble opinion, software of this caliber should have better documentation and examples. Too much time is wasted problem solving.

I agree. We "just" need more help from the community to improve these things.

**Comment by diemol** [comment]
Closing as we did not get more information.
