### ISSUE TITLE
Getting black screenshot for internet driver server version 3.14 when executed under node URL (Jenkins)

### ISSUE THREAD

**Issue by Ravichandran-S** [SeleniumHQ/seleniumhq.github.io#95]
Hi Team,
I have upgraded selenium-java version to 3.141.59. IE driver version is 3.14.
I can see Black screenshot and timeout exception occurred under Jenkins.
I have initiated driver before suite and quited after suite.
Time taken to execute 54 test cases is 2.5hrs

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), check more communication channels at https://selenium.dev/support/.
