### ISSUE TITLE
[🐛 Bug]: Missing Documentation for "Override Device Mode" PYTHON

### ISSUE THREAD

**Issue by gigacodr** [SeleniumHQ/seleniumhq.github.io#950]
### What happened?

Documentation for Python in 'Override Device Mode' section missing:

https://www.selenium.dev/documentation/webdriver/bidirectional/chrome_devtools/#override-device-mode

Are dev tools protocol not available for Python?

https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setDeviceMetricsOverride

### What browsers and operating systems are you seeing the problem on?

Chrome Version: 97
Windows 10

**Comment by shbenzer** [comment]
@harsha509 this section of the Documentation no longer exists, and is being deprecated with the BiDi implementation. Should this issue be closed?

**Comment by harsha509** [comment]
> @harsha509 this section of the Documentation no longer exists, and is being deprecated with the BiDi implementation. Should this issue be closed?

HI @shbenzer ,

Thank you for looking into it! 

Also as mentioned in docs, Chrome already has a good API for setting [Mobile Emulation](https://chromedriver.chromium.org/mobile-emulation) through the Options class, which works well for mobile testing.

We’ll go ahead and close this issue as `Won't Fix.`
