### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by mjhymowitz** [SeleniumHQ/seleniumhq.github.io#960]
### What happened?

I am trying to access elements using the xpath and this error showed up in the output
My code: Python
```
#!/usr/bin/env python
# coding: utf-8
from selenium.webdriver import Edge
from selenium.webdriver.edge.service import Service as EdgeService
from webdriver_manager.microsoft import EdgeChromiumDriverManager
from selenium.webdriver.edge.options import Options as EdgeOptions
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

SEATTLEU_FORM = "https://www.seattleu.edu/coronavirus/screening/"
FORM_URL_XPATH = '//*[@id="id1647669"]/div/div/ul/li[1]/a'
short_sleep = 2

# Open Browser
service = EdgeService(executable_path=EdgeChromiumDriverManager().install())
driver = Edge(service=service, options=EdgeOptions())
driver.get(SEATTLEU_FORM)
WebDriverWait(driver, short_sleep).until(EC.presence_of_element_located((By.XPATH, FORM_URL_XPATH)))
form_url = driver.find_element(By.XPATH, FORM_URL_XPATH)
driver.get(form_url.get_attribute('href'))
```

DevTools listening on ws://127.0.0.1:56738/devtools/browser/00c9eb1b-df43-4957-a055-b438dbc0a159
[22352:15004:0222/134637.327:ERROR:fallback_task_provider.cc(123)] Every renderer should have at least one task provided by a primary task provider. If a "Renderer" fallback task is shown, it is a bug. If you have repro steps, please file a new bug and tag it as a dependency of crbug.com/739782.

### What browsers and operating systems are you seeing the problem on?

WDM] - ====== WebDriver manager ======
[WDM] - Current edge version is 98.0.1108
[WDM] - Get LATEST edgedriver version for 98.0.1108 Edge
[WDM] - Trying to download new driver from https://msedgedriver.azureedge.net/98.0.1108.56/edgedriver_win64.zip
[WDM] - Driver has been saved in cache [C:\Users\markh\.wdm\drivers\edgedriver\win64\98.0.1108.56]

**Comment by MrRahulR** [comment]
@mjhymowitz - It would be better if you can add the Title of the Bug.

**Comment by mjhymowitz** [comment]
I solved the problem, somehow.
