### ISSUE TITLE
[🐛 Bug]: Instructions for Install Browser Driver missing steps

### ISSUE THREAD

**Issue by brieshiraz** [SeleniumHQ/seleniumhq.github.io#961]
### What happened?

Summary: When following 'Install Browser Driver' instructions, user is linked to a 'Downloads' page with no information about what to download or how.

Steps to reproduce:
1. As a new Selenium Webdriver user, start at the beginning of the the 'Getting Started' guide at https://www.selenium.dev/documentation/webdriver/getting_started/
2. After installing Selenium library, proceed to 'Install Browser Driver' step at https://www.selenium.dev/documentation/webdriver/getting_started/install_drivers/
3. Read instructions and proceed to Downloads link for 'Chrome/Chromium' browser

Expected Result: Links to driver options with instructions for how to download them and which one to select if unsure (it seems we're supposed to download the one that matches our browser version - so say that?)

Actual Result: List of dozens of links, no instructions, and no way for the user to know what to do next. I intuitively tried the one at the bottom that said LATEST with the most recent time stamp and it took me to a page with no zip files, just text and a version number.

### What browsers and operating systems are you seeing the problem on?

Google Chrome - Version 98.0.4758.102 (Official Build) (arm64)
MacOS Monterey v12.1

**Comment by freesme** [comment]
I ran into the same problem，You can try to add

`
System.setProperty("wdm.useMirror", "true");
`

before


`WebDriverManager.chromedriver().setup();`

**Comment by diemol** [comment]
Download link for Chrome/Chromium should be replaced with https://chromedriver.chromium.org/downloads
