### ISSUE TITLE
[🐛 Bug]: Selenium channel on freenode

### ISSUE THREAD

**Issue by raffaelemancuso** [SeleniumHQ/seleniumhq.github.io#967]
### What happened?

[This webpage](https://www.selenium.dev/selenium/docs/api/py/) says the selenium channel is on freenode, while [this one](https://www.selenium.dev/documentation/about/) says it is on LiberaChat

### What browsers and operating systems are you seeing the problem on?

Firefox

**Comment by luisfcorreia** [comment]
Thanks for noticing, fixed by https://github.com/SeleniumHQ/selenium/pull/10403
