### ISSUE TITLE
File Upload Examples

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/seleniumhq.github.io#975]
Was asked about file uploads in slack today, we don't have any examples.
The one example in Selenium 2 FAQ in legacy section includes an out of date hint that doesn't apply for w3c.

**Comment by titusfortner** [comment]
Here's another issue requesting this info: https://github.com/SeleniumHQ/selenium/issues/10464

**Comment by rpallavisharma** [comment]
[Fileupload.docx](https://github.com/SeleniumHQ/seleniumhq.github.io/files/8499257/Fileupload.docx)
hope this helps

**Comment by diemol** [comment]
@pallavigitwork would you like to send a PR to add this content? If you need help with that, ping me in the Selenium Slack and I am happy to help you run the site locally so you can send the PR.

**Comment by rpallavisharma** [comment]
okay @diemol i will ping you on slack.

**Comment by diemol** [comment]
@pallavigitwork I saw you sending some PRs, do you think you can also send PRs for this, please?

**Comment by rpallavisharma** [comment]
Sure, i will do this.

**Comment by diemol** [comment]
Thank you, @pallavigitwork!

https://www.selenium.dev/documentation/webdriver/additional_features/fileupload/
