### ISSUE TITLE
[🐛 Bug]: Explicit Wait Python examples are missing the required `timeout` argument

### ISSUE THREAD

**Issue by nicolas-chan-42** [SeleniumHQ/seleniumhq.github.io#976]
### What happened?

In the section of [Explicit Wait](https://www.selenium.dev/documentation/webdriver/waits/#explicit-wait), the Python example code uses `WebDriverWait(driver)` but according to the [API reference of `selenium.webdriver.support.wait`](https://www.selenium.dev/selenium/docs/api/py/webdriver_support/selenium.webdriver.support.wait.html#selenium.webdriver.support.wait.WebDriverWait), the `timeout` argument, which is missing in the examples, has no default value and should be required.

Hence, running the Python example code for Explicit Wait may lead to an error.

To be explicit, I mean the following two examples:
```python
from selenium.webdriver.support.ui import WebDriverWait
def document_initialised(driver):
    return driver.execute_script("return initialised")

driver.navigate("file:///race_condition.html")
WebDriverWait(driver).until(document_initialised)  # <== This line.
el = driver.find_element(By.TAG_NAME, "p")
assert el.text == "Hello from JavaScript!"
```
and
```python
from selenium.webdriver.support.ui import WebDriverWait

driver.navigate("file:///race_condition.html")
el = WebDriverWait(driver).until(lambda d: d.find_element_by_tag_name("p"))  # <== This line.
assert el.text == "Hello from JavaScript!"
```

I suggest to make it consistent with the examples shown for other languages, and use `WebDriverWait(driver, 3)` or `WebDriverWait(driver, timeout=3)`.

Thank you.

### What browsers and operating systems are you seeing the problem on?

Chrome 99 on Windows 10

**Comment by diemol** [comment]
@nicolas-chan-42, would you like to send a PR to fix this?

**Comment by nicolas-chan-42** [comment]
@diemol I am not planning to send a PR for this. Thank you.

But the fixed code examples should be as follows, in case someone is interested for sending a PR:

```python
from selenium.webdriver.support.ui import WebDriverWait
def document_initialised(driver):
    return driver.execute_script("return initialised")

driver.navigate("file:///race_condition.html")
WebDriverWait(driver, timeout=10).until(document_initialised)
el = driver.find_element(By.TAG_NAME, "p")
assert el.text == "Hello from JavaScript!"
```

and 

```python
from selenium.webdriver.support.ui import WebDriverWait

driver.navigate("file:///race_condition.html")
el = WebDriverWait(driver, timeout=10).until(lambda d: d.find_element_by_tag_name("p"))
assert el.text == "Hello from JavaScript!"
```

Please notice the addition of "`, timeout=10`" in both examples.

**Comment by ghost** [comment]
I've made a PR: https://github.com/SeleniumHQ/seleniumhq.github.io/pull/998
