### ISSUE TITLE
[🐛 Bug]: the parameter should be 'caps' instead of 'capabilities'

### ISSUE THREAD

**Issue by GregoryShen** [SeleniumHQ/seleniumhq.github.io#977]
### What happened?

In chapter "Upgrade to Selenium 4", The parameter of CSharp version should be 'caps' instead of 'capabilities', capture as below:
![image](https://user-images.githubusercontent.com/1592347/160853399-efcd4e9b-23d1-4d1b-83c8-49ceca656f4d.png)

### What browsers and operating systems are you seeing the problem on?

browser: Chrome
OS: Windows 10

**Comment by luisfcorreia** [comment]
Can you please add a link to the specific page where you found that?

Thanks
