### ISSUE TITLE
[🚀 Feature]: Tracing docs need a lot more info

### ISSUE THREAD

**Issue by ibodog** [SeleniumHQ/seleniumhq.github.io#982]
### Feature and motivation

Wanted to try this out, but there is not enough info to get this working outside of the --trace logging to the console.  Easy to get Jaeger running. But not clear how to export traces in the dockerized grid & node-docker.

**Comment by diemol** [comment]
This has been fixed directly in the docker selenium repository, instructions are there now.

Related PR is https://github.com/SeleniumHQ/docker-selenium/pull/1711
