### ISSUE TITLE
[🐛 Bug]: Documentation CLI '--hub' option not documented

### ISSUE THREAD

**Issue by gidonk-pr** [SeleniumHQ/seleniumhq.github.io#985]
### What happened?

spent hours trying to configure node-hub connection.
setup a toml config file on my node with:
```
[node]
grid-url = "http://hub-address:4444"
```
only to find out that I need to replace `grid-url` with `hub` which is not even mentioned on the page I was following (https://www.selenium.dev/documentation/grid/configuration/cli_options/#node)

moreover - manually setting `publish-events`& `subscribe-events` have no effect on running config
### What browsers and operating systems are you seeing the problem on?

--not relevant

**Comment by diemol** [comment]
Duplicate of #788
