### ISSUE TITLE
[🐛 Bug]: https://www.selenium.dev/documentation/webdriver/bidirectional/ : Last paragraph is not easy to understand and has grammar mistakes

### ISSUE THREAD

**Issue by rohitb123** [SeleniumHQ/seleniumhq.github.io#993]
### What happened?

https://www.selenium.dev/documentation/webdriver/bidirectional/ : Last paragraph is not easy to understand and has grammar mistakes

Quoting the last paragraph : "Because it’s a bad idea to tie your tests to a specific version of a specific browser, the Selenium project recommends using WebDriver BiDi wherever possible. However, until the spec is complete there are many useful things that the CDP offers. To help keep your tests independent and portable, Selenium offers some useful helper classes. At the moment, these use the CDP, but when we shall be using WebDriver Bidi as soon as possible"

Here what do we mean by CDP? 
Last statement in paragraph has so many grammatical mistakes

### What browsers and operating systems are you seeing the problem on?

Chrome, Windows 11

**Comment by diemol** [comment]
@rohitb123 would you like to send a PR to improve it? 
Also, by CDP, it means https://chromedevtools.github.io/devtools-protocol/
